---
title: "Memoirs of Colonel Bugeaud - translated and edited by Charlotte Mary Yonge (1884)"
year: 1877
slug: "A_man_of_other_days-Marquis_Henry_Joseph_Costa"
format:
  html:
    toc: true
---


#### Costa de Beauregard, Henry-Joseph, marquis de (1752-1824) – Officier supérieur sarde  
Un homme d'autrefois.

#### Souvenirs recueillis par son arrière-petit fils, le marquis Albert Costa de Beauregard

#### Paris, 1877, 480 p.

#### A man of other days.

#### Recollections of the Marquis H.J. Costa de Beauregard,  
selected from his papers, by his great grandson the Marquis Marie Charles Albert Costa de Beauregard

#### Edited by Charlotte Mary Yonge.  
2 vols.  
London, 1877

#### Charles COSTA de BEAUREGARD (1835-1909)

Chevalier de la Légion d'honneur

**Œuvres  
**Discours et travaux académiques  
Historien, homme politique Biographie

Né à La Motte-Servolex (Savoie), le 24 mai 1835.Il a été élu à l'Académie le 23 janvier 1896 au deuxième tour par 19 voix contre 12 à Émile Deschanel en remplacement de Camille Doucet et reçu le 26 février 1897 par Édouard Hervé.Officier, blessé pendant la guerre, député en 1871, il vint siéger à Versailles en se soutenant encore avec des béquilles ; historien il écrivit l'Histoire de Charles Albert, en deux volumes.Mort le 15 février 1909.

#### Œuvres de Charles COSTA de BEAUREGARD

#### 1877 Un homme d’autrefois

#### 1888 Mémoires historiques sur la maison de Savoie  
1889 La jeunesse du roi Charles-Albert  
1890 Les dernières années du roi Charles-Albert  
1892 Le roman d’un royaliste sous la Révolution, souvenirs du comte de Virieu  
1895 Prédestinée  
1896 La charité sociale en Angleterre  
1900 Émigration, souvenirs tirés des papiers du comte A. de La Ferronays  
1902 Courtes pages  
1904 Liberté, Égalité, Fraternité  
1907 Madame Loyse de Savoie  
1908 Comment mon oncle le général mérita la Croix de Marie-Thérèse  
1909 Pages d’histoire et de guerre

