---
title: "Abbeychurch, or Self control and self conceit"
sort_title: "Abbeychurch, or Self control and self conceit"
year: 1844
gutenberg_url: "https://www.gutenberg.org/ebooks/4267"
slug: "abbey_church"
format:
  html:
    toc: true
---


*1844*


[Read free online at Project Gutenberg](https://www.gutenberg.org/ebooks/4267)

---


'Never think yourself safe because you do your duty in ninety-nine points; it is the hundredth which is to be the ground of your self-denial, which must evidence, or rather instance and realize, your faith.'

Newman's Sermons

#### PREFACE  
to the second (1872) edition

Rechauffes are proverbially dangerous, but everyone runs into them sooner or later, and the world has done me the kindness so often to inquire after my first crude attempt, that after it has lain for many years 'out of print,' I have ventured to launch it once more -- imperfections and all -- though it is guilty of the error of pointing rather to a transient phase of difficulty than to a general principle. The wheels of this world go so quickly round, that I have lived to see that it would have been wiser in the clergyman to have directed rather than obstructed the so-called 'march of intellect.' I have lived also to be somewhat ashamed of the exuberant outpouring of historical allusions, which, however, were perfectly natural among the set of girls from whom my experience was taken: but these defects, as well as the more serious one of tyrannical aversion to vulgarity, are too inherent in this tale to be removed, and the real lesson intended to be conveyed, of obedience and sincerity, of course remains unchanged.

The later story was a rather hasty attempt to parody the modern sensation novel, as Northanger Abbey did the Radclyffe school, but it makes the mistake of having too real a mystery. However, such as they are, the two stories go forth in company, trusting that they may not prove too utterly wearisome to be brought forward this second time.

Charlotte Mary Yonge May 9th, 1872,

### **Online text of*Abbeychurch***

[Click here to reach the latest version of](https://www.gutenberg.org/ebooks/4267)[***Abbeychurch***from Gutenberg](https://www.gutenberg.org/ebooks/4267)  

[Click here to reach the latest version of](https://www.gutenberg.org/ebooks/4267)[***Abbeychurch***from the Internet Archive](https://archive.org/details/abbeychurchorse00yonggoog/page/n10/mode/2up)  

### Publication details, summary and further reading

(Text kindly supplied by Julia Courtney)

James Burns, London, and Mozley, Derby, prefaced by passage from Newman’s*Sermons*: ‘Never think yourself safe because you do your duty in ninety nine points: it is the hundredth which must be the ground of your self-denial, which must evidence, or rather instance and realise, your faith’.

The action of*Abbeychurch*takes place in the few days preceding and immediately following the dedication of St. Austin’s Church in Abbeychurch St. Mary’s, an expanding town in which the ‘new great workshop of all nations’ meets ‘the remains of old respectable England’.

Typically, Yonge barely describes the Consecration ceremony since ‘such thoughts and scenes are too high to be more than touched on in a story of this kind’ Instead she conveys the feelings and comments on the spiritual and emotional development of a group of young people drawn together by the sacred event, whose excitements ‘only those who have shared in the joys of church building can know’. Elizabeth (Lizzie) Woodbourne, still ‘under seventeen’, and her younger sisters, worldly Katherine and sententious Helen, are the daughters of the Vicar and his saintly, but now defunct, first wife. Four younger children, mainly represented by Dora, an extremely clear-sighted seven year old, have been born to the second Mrs. Woodbourne: the gentle, inoffensive and generally useless Mildred, Visitors to the Vicarage include family relative Lady Merton, paragon and moral arbiter of the novel, and her children Anne and Rupert Merton. Anne is Lizzie’s great friend and shares her passion for tales of chivalry; Rupert, whose delayed arrival adds tension to the plot, is a nineteen year old undergraduate distinguished by missing front teeth (lost in a playground accident), a talent for ‘paper games’ and the habit of teasing the girls. Less welcome guests are the Hazleby family, referred to as The Hazlebies and led by abrasive ‘Scotch’ Mrs. Hazleby, insensitive, dishonest Harriet, downtrodden Lucy and the egregious canine Fido.

Trouble is likely to result from this mixture of personalities, especially given Lizzie’s character: ‘upright, noble, spirited’ but intellectual, untidy and impatient: ‘such an exciteable, impetuous creature is not likely to escape going wrong, without steady control from herself or someone else’, diagnoses Lady Merton.

Impelled by a mixture of antiquarian curiosity and personal rivalry the girls decide to attend a lecture on Chivalry at the local Mechanics’ Institute; the escapade demonstrates a moral line up as Helen, Lucy and Dora refuse to enter the Institute, leaving Lizzie, Anne and Harriet to encounter vulgarity and humiliation within. Back home, Lizzie longs to confess her shame and consults her stepmother, who reveals that Mr. Woodbourne has sworn that no member of his household should cross the threshold of the seditious Mechanics’ Institute. Lizzie ‘has transgressed a command of which she was ignorant’, but her stepmother will explain all to the Vicar when he is less busy.

Meanwhile, Lucy Hazleby meekly bears the blame for the disappearance of Fido, missing since the visit to the Institute; the dog’s drowned corpse is later found by Rupert. Lucy achieves the silent moral victory in the Hazleby family, since Harriet persists in deceit to the end.

In the emotional climax of the novel, Mr. Woodbourne reads the local newspaper’s gloating account of the girls’ ill-fated visit to the lecture; his wife has forgotten to pass on Lizzie’s confession, but Lizzie’s distress wins her father’s forgiveness; Helen also receives much-needed praise while Kate is reprimanded.

*Abbeychurch*ends with greater self-knowledge all round, achieved with the help of Lady Merton’s wise advice and Mr. Woodbourne’s ‘stern kindness'.

