---
title: "Stories in collections - Charlotte Mary Yonge"
slug: "all_stories_in_collections"
format:
  html:
    toc: true
---


Austin, Stella;  
Baring-Gould, Sabine, 1834-1924;  
Birley, Caroline

#### Jack Frost's little prisoners. A collection of stories for children from four to twelve years of age.

By Stella Austin. S. Baring-Gould. Caroline Birley. Lord Brabourne. (E.H. Knatchbull-Hugessen.) Mrs. Massey. Mrs. Molesworth. Mrs. Richmond Ritchie. (Miss Thackeray.) Ethel M. Wilmot-Buxton.**Charlotte M. Yonge**.  
Fourth edition. . 4th edition  
Imprint: Skeffington & Son, 163, Piccadilly, W.. 1887

London, 1887  
Pagination: [10],163,[5]p. 8o

Notes: With a 4-page advertisement for works published by Skeffington & Son

British Library Shelfmark: 12806.p.26

Fiche Quantity: 2 fiches; 11x15 cm

Fiche Number: 6.1.646

Adams, Henry Cadwallader, 1817-1899;  
Ballantyne, Robert Michael, 1825-1894;  
Baring-Gould, Sabine, 1834-1924

#### Stories jolly: stories new: stories strange & stories true.  
A series of new and original tales for boys and girls from six to fourteen years old.

By H.C. Adams. R.M. Ballantyne. S. Baring-Gould. Fanny Barry. Frances Clare. Alice Corkran. G. Manville Fenn. Agnes Giberne. Mrs. A.M. Goodhart. G.A. Henty. Katharine S. Macquoid. Mrs. Molesworth. Helen Wilmot-Buxton. Emma Wood.**Charlotte M. Yonge**.

Imprint: Skeffington & Son, 163, Piccadilly, W.. 1889Place of Publication: LondonDate of Publication: 1889Pagination: viii,265,[3]p., ill., 5 plates. 8oNotes: With a half-title and a 32-page advertisement for works published by Skeffington & SonBritish Library Shelfmark: 12807.t.7

Also in Devon library / Local Studies Service  
Stories jolly : stories new : stories strange and stories true/ by H.C.Adams et al. - London : Skeffington & Son , 1889. - 265p : frontis ; 19cm.  
(Record no: 33236) WSL: s823/STO

#### Title: [Collection of English children's stories].

Published: [London? : Groombridge and Sons? 186-] Description: ca. 700 p. : ill. ; 17 cm. Location: BEINECKE (Non-Circulating) Call Number: Bryher Z8 M24 Status: Not Checked Out Notes: On spine: Magnet stories, 2. Variant and related titles: Magnet stories. Contents: The story of Nelson / W.H.G. Kingston -- Coraline, or, "After many days" / Author of "A trap to catch a sunbeam" -- The orphans of Elfholm / Frances Browne -- The story of a pebble / L.A. Hall -- The sea spleenwort / Author of "The heir of Redclyffe" [i.e. C.M. Yonge] -- The Christmas rose / H.J. Wood -- Ellis Gordon, of Bolton Farm / Emily Taylor -- The grateful Indian / William H.G. Kingston -- Fanny's fancies / Mrs. S.C. Hall -- Sweet spring-time / Thomas Miller -- Havering Hall / G.E. Sargent -- The clockmaker of Lyons / E.M. Piper -- The Merivales / Sara Wood -- Caldas / Julia Corner.

#### The Magnet stories, for summer days and winter nights.

By the authors of "A...  
Title: The Magnet stories, for summer days and winter nights. By the authors of "A trap to catch a sunbeam," "The heir of Redclyff," etc., etc. ...  
Published: New York, J. Miller, 1863-  
Description: v. fronts., illus., plates. 18 cm.  
Location: LSF-Request for Use at Any Yale Library  
Call Number: Ib82 t860mb  
Status: Not Checked Out  
Library has: 1-2  
Notes: Added t.-p.'s, illus.  
Vol. 2: New series.  
Published in England in 8 v., 1860-65.  
Contents: v.1. When we were young, by the author of "A trap to catch a sunbeam," etc. Lottie's half-sovereign, by Mrs. Russell Gray. Mamma Milly, by Mrs. S.C. Hall. Havering hall, by G.E. Sargent. Blind Ursula, by Mrs. Webb. The clock-maker of Lyons, by E.M. Piper. The mice at play, by the author of "The heir of Redclyffe," etc.--v.2. Coraline; or, "After many days," by the author of "A trap to catch the sunbeam," etc. The orphans of Elfholm, by Frances Brown. Cousin Annie's story, by the author of "The heir of Redclyffe." The story of a pebble, by L.A. Hall. The town of toys, by Sara Wood. Lost beauty, by Mrs. S.C. Hall.  
Subjects (Library of Congress): English fiction.

#### Stories for boys / by W.H.G. Kingston, Mark Lemon, and other authors.

Title: Stories for boys / by W.H.G. Kingston, Mark Lemon, and other authors.  
Published: London : Groombridge and Sons, 1879.  
Description: ca. 500 p., [1] leaf of plates : ill. (1 col.) ; 17 cm.  
Location: BEINECKE (Non-Circulating)  
Call Number: Bryher Z8 S814  
Status: Not Checked Out  
Local notes: BEIN: Advertising matter: [2] p. at end not included in collation. (Bryher Z8 S814)  
Contents: The boatswain's son / William H.G. Kingston -- Havering Hall / G.E. Sargent -- The story of Nelson / W.H.G. Kingston -- The clockmaker of Lyons / E.M. Piper -- The pedlar's hoard / Mark Lemon -- Hereward the brave / Julia Corner -- No-Man's-Land / Thomas Miller -- Purples and blues / Emily Taylor -- Which was the bravest? / L.A. Hall -- The little trapper / W. Heard Hillyard -- The apple of discord / Author of "The Heir of Redclyffe" [i.e. C.M. Yonge]  
Subjects (Library of Congress): Children's literature, English.  
Also listed under: Kingston, William Henry Giles, 1814-1880.  
Lemon, Mark, 1809-1870.

#### Stories ofheroism from the world's history.

Stories by E.S. Brooks--Charlotte M. Yonge--Jacob Abbot--Israel Potter--Katharine Birdsell--W.F. Livingston.  
Published: New York, London : G.P. Putnam's Sons, [189-?]  
Description: viii p., 1 l., 407 p. front. plates, ports. 20 cm.  
Location: SML, Stacks, Yale Classification  
Call Number: Bd4 13p  
Status: Not Checked Out  

#### The Junior Classics, Various

#### Subtitle: Volume 7, Stories of Courage and Heroism

Editor: William Patten  
[Introduction: Charles W. Eliot]  
[Reading Guide: William Allen Neilson]  

Contains six stories by Charlotte Yonge

[To download from Gutenberg click here](http://onlinebooks.library.upenn.edu/webbin/gutbook/lookup?num=6302)

How Phidias Helped the Image-Maker by Beatrice Harraden  
**The Fight at the Pass of Thermopyle by Charlotte M. Yonge  
****The Bravery of Regulus by Charlotte M. Yonge  
**The Rabbi Who Found the Diadem by Dr. A. S. Isaacs  
How Livia Won the Brooch by Beatrice Harraden  
Julius Caesar Crossing the Rubicon by Jacob Abbott  
**Fearless Saint Genevieve, Patron Saint of Paris by Charlotte M. Yonge  
**The Boy Viking--Olaf II of Norway by E. S. Brooks  
The Boy-Heroes of Crecy and Poitiers by Treadwell Walden  
**The Noble Burghers of Calais by Charlotte M. Yonge  
**The Story of Joan of Arc, the Maid Who Saved France by Anonymous  
How Joan the Maid Took Largess from the English by Anonymous  
Death of Joan the Maid by Anonymous  
**How Catherine Douglas Tried to Save King James of Scotland by Charlotte M. Yonge  
****The Brave Queen of Hungary by Charlotte M. Yonge  
**The Story of Christopher Columbus for Little Children by Elizabeth Harrison  
A Sea-Fight in the Time of Queen Bess by Charles Kingsley  
A Brave Scottish Chief by Anonymous  
The Adventure of Grizel Cochrane by Arthur Quiller-Couch  
The Sunken Treasure by Nathaniel Hawthorne  
The Lost Exiles of Texas by Arthur Oilman  
The Boy Conqueror--Charles XII of Sweden by E. S. Brooks  
The True Story of a Kidnapped Boy as Told by Himself Peter Williamson  
The Prisoner Who Would Not Stay in Prison by Anonymous  
A White Boy Among the Indians, as Told by Himself John Tanner  
Evangeline of Acadia by Henry W. Longfellow  
Jabez Rockwell's Powder-Horn by Ralph D. Paine  
A Man Who Coveted Washington's Shoes by Frank R. Stockton  
A Famous Fight Between an English and a French Frigate by Rev. W. H. Fitchett  
The Trick of an Indian Spy by Arthur Quiller-Couch  
The Man in the "Auger Hole" by Frank R. Stockton  
The Remarkable Voyage of the _Bounty_ by Anonymous  
The Two Boy Hostages at the Siege of Seringapatam by Anonymous  
The Man Who Spoiled Napoleon's "Destiny" by Rev. W. H. Fitchett  
A Fire-Fighter's Rescue from the Flames by Arthur Quiller-Couch  
How Napoleon Rewarded His Men by Baron de Marbot  
A Rescue from Shipwreck by Arthur Quiller-Couch  
Rebecca the Drummer by Charles Barnard  
The Messenger by M. E. M. Davis  
Humphry Davy and the Safety-Lamp by George C. Towle  
Kit Carson's Duel by Emerson Hough  
The Story of Grace Darling by Anonymous  
The Struggles of Charles Goodyear by George C. Towle  
Old Johnny Appleseed by Elizabeth Harrison  
The Little Post-Boy by Bayard Taylor  
How June Found Massa Linkum by Elizabeth S. Phelps  
The Story of a Forest Fire by Raymond S. Spears

