---
title: "Astray"
slug: "astray"
format:
  html:
    toc: true
---


Review of Astray by Oscar Wilde

(Pall Mall Gazette, October 28, 1886.)

Astray: A Tale of a Country Town, is a very serious volume. It has taken four people to write it, and even to read it requires assistance.Its dulness is premeditated and deliberate and comes from a laudable desire to rescue fiction from flippancy. It is, in fact, tedious from the noblest motives and wearisome through its good intentions. Yet the story itself is not an uninteresting one. Quite the contrary. It deals with the attempt of a young doctor to build up a noble manhood on the ruins of a wasted youth. Burton King, while little more than a reckless lad, forges the name of a dying man, is arrested and sent to penal servitude for seven years. On his discharge he comes to live with his sisters in a little country town and finds that his real punishment begins when he is free, for prison has made him a pariah. Still, through the nobility and self-sacrifice of his life, he gradually wins himself a position, and ultimately marries the prettiest girl in the book. His character is, on the whole, well drawn, and the authors have almost succeeded in making him good without making him priggish. The method, however, by which the story is told is extremely tiresome. It consists of an interminable series of long letters by different people and of extracts from various diaries. The book consequently is piecemeal and unsatisfactory. It fails in producing any unity of effect. It contains the rough material for a story, but is not a ompleted work of art. It is, in fact, more of a notebook than a novel. We fear that too many collaborators are like too many cooks and spoil the dinner. Still, in this tale of a country town there are certain solid qualities, and it is a book that one can with perfect safety recommend to other people.

Source[http://www.readeasily.com/oscar-wilde/00202/002020049.php](http://www.readeasily.com/oscar-wilde/00202/002020049.php)  


