---
title: "Aunt Charlotte's Stories of English History for the Little Ones"
sort_title: "Aunt Charlotte's Stories of English History for the Little Ones"
year: 1873
gutenberg_url: "https://www.gutenberg.org/ebooks/4769"
slug: "Aunt_English"
format:
  html:
    toc: true
---




Yonge's*Aunt Charlotte's Stories of English History*is available on microfiche from**The Nineteenth Century**(this site gives you free access to an online catalogue of over 25,000 nineteenth-century works available on microfiche)

#### Aunt Charlotte's Stories of English History

#### Chapter titles

1. Julius Caesar. B.C. 55.

2. The Romans in Britain. A.D. 41–418.

3. The Angle Children. A.D. 597.

4. The Northmen. A.D. 858–958.

5. The Danish Conquest. A.D. 958–1035.

6. The Norman Conquest. A.D. 1035–1066.

7. William the Conqueror. A.D. 1066–1087.

8. William II., Rufus. A.D. 1087–1100.

9. Henry I., Beau-Clerc. A.D. 1100–1135.

10. Stephen. A.D. 1135–1154.

11. Henry II., Fitz-Empress. A.D. 1154–1189.

12. Richard I., Lion-Heart. A.D. 1189–1199.

13. John, Lackland. A.D. 1199–1216.

14. Henry III., of Winchester. A.D. 1216–1272.

15. Edward I., Longshanks. A.D. 1272–1307.

16. Edward II., of Caernarvon. A.D. 1307–1327.

17. Edward III. A.D. 1327–1377.

18. Richard II. A.D. 1377–1399.

19. Henry IV. A.D. 1399–1413.

20. Henry V., of Monmouth. A.D. 1413–1423.

21. Henry VI., of Windsor. A.D. 1423–1461.

22. Edward IV. A.D. 1461–1483.

23. Edward V. A.D. 1483.

24. Richard III. A.D. 1483–1485.

25. Henry VII. A.D. 1485–1509.

26. Henry VIII. and Cardinal Wolsey. A.D. 1509–1529.

27. Henry VIII. and his Wives. A.D. 1528–1547.

28. Edward VI. A.D. 1547–1553.

29. Mary I. A.D. 1553–1558.

30. Elizabeth. A.D. 1558–1587.

31. Elizabeth (continued). A.D. 1587–1602.

32. James I., A.D. 1602–1625.

33. Charles I., A.D. 1625–1645.

34. The Long Parliament. A.D. 1649.

35. Death of Charles I. A.D. 1649–1651.

36. Oliver Cromwell. A.D. 1649–1660.

37. Charles II. A.D. 1660–1685.

38. James II. A.D. 1685–1688.

39. William III., and Mary II. A.D. 1689–1702.

40. Anne. A.D. 1702–1714.

41. George I. A.D. 1714–1725.

42. George II. A.D. 1725–1760.

43. George III. A.D. 1760–1785.

44. George III. (continued). A.D. 1785–1810.

45. George III. The Regency. A.D. 1810–1820.

46. George IV. A.D. 1820-1839.

47. William IV. A.D. 1830–1837.

48. Victoria. A.D. 1837–1855.

49. Victoria (continued). A.D. 1855–1860.

50. Victoria (continued). A.D. 1860–1872.

