---
title: "Life of John Coleridge Patteson, Missionary Bishop of the Melanesian Islands"
sort_title: "Life of John Coleridge Patteson, Missionary Bishop of the Melanesian Islands"
year: 1873
subtitle: "1873"
gutenberg_url: "https://www.gutenberg.org/ebooks/4952"
slug: "bishop_patteson"
format:
  html:
    toc: true
---



**Summary of Patteson's life**Patteson / Melanesian Links


### **John Coleridge Patteson 1827–1871**

Born in London (9 Gower St., Bedford Square) 1 April 1827  
Eldest son of John Patteson and Frances Duke Coleridge.  
Educated at Eton, 1838-45, and Balliol College, Oxford, 1845-8, graduated 1849 (*Literae Humaniores*).  
Fellow of Merton College, Oxford, 1852-71.  
Ordained deacon, 1853, priest, 1854.  
Curate at Alfington, Devon, 1853-4.  
Chaplain to Bishop Selwyn in New Zealand and the Melanesian Islands, 1855-61.  
Anglican Bishop of Melanesia, 1861-71  
Killed 20 September 1871 on the island of Nukapu.

### More on Patteson

#### **  
**BOOKS****

**Patteson of Melanesia; a brief life of John Coleridge Patteson, missionary bishop  
**Frank Hume Lyall Paton (no date)

**Patteson memorial chapel, Norfolk Island : an account of its building based on R.H. Codrington's letters ... and an eyewitness account of its consecration  
**Ed. Sir John Gutch and J. Pinder.

**Patteson of the isles  
**Mary H. Debenham,  
Publisher London : Humphrey Milford, 1921  
Description: 159 p., [7] leaves of plates : ill.  
Series: Pathfinder series  

**Patteson of the South Sea Islands**  
Norman James Davidson, b. 1860.  
Publisher Lond, 1931  
Series: Seeley's missionary lives for children

**Patteson's papers at Selwyn College Cambridge**  
Papers, 1854-70, comprising: diaries, 1866 and 1870; correspondence, 1854-69; prayer book and bible

####   
THESES

#### ["A Selection of Fundamentals":  
The Intellectual Background of the Melanesian Mission of the Church of England, 1850-1914  
](http://anglicanhistory.org/oceania/sohmer1988/)By Sara Harrison Sohmer  
*A Dissertation submitted to the graduate division of the University of Hawaii  
in partial fulfillment of the requirements for the degree of Doctor of Philosophy in History, May 1988.*

[Liturgical Spirituality under the Southern Cross  
A Study of the Impact of the Anglo-Catholic Tradition on the Anglican Church in Melanesia  
](http://anglicanhistory.org/oceania/vunagi1998/)By the Rev. David V. Vunagi, B.Ed., Dip. Ed., B.Th.  
A thesis submitted to the Graduate Studies Committee of the Vancouver School of Theology in partial fulfilment of the requirements for the Degree of Master of Theology.

####   
PAPER

["Unpretending labours": Julia Farr and the Melanesian Mission](http://anglicanhistory.org/oceania/crawford_farr2004.pdf)  
By Janet Crawford  
*Paper presented at the First Biennial TransTasman Conference: ANZ Missionaries, At Home and Abroad 2004*

#### ********  
**MEMORIALS****

Memorial window to Patteson in the south window of the Trinity Episcopal Cathedral, Omaha, Nebraska

Memorial pulpit (1877) to Bishop Patteson in Exeter Cathedral

**Solomon Islands and Norfolk Islands commemorative postage stamps**  
Issued in 1999 to commemorate the 150th Anniversary of Melanesian Mission  
In the Solomon Islands stamp set, Bishop Patteson appears on a $1.00 stamp in the set.  
On the far right we see the mission schooner "Southern Cross" which was constructed for the Melanesia mission work.

This set of stamps may still be available from the**Solomon Islands Philatelic Bureau**

There is also an apparently identical Norfolk Islands version of this stamp set, though the value of the Bishops' stamps is only 45 cents.

