---
title: "The Caged Lion by Charlotte Mary Yonge"
slug: "caged_lion"
format:
  html:
    toc: true
---


### Online text of this book

[Click here to reach the latest version of***The Caged Lion*online**from Gutenberg](http://digital.library.upenn.edu/webbin/gutbook/lookup?num=2573)  
(Many thanks to Sandra Laythorpe and others)

### Publication details, summary and further reading

(Kindly supplied by Amy de Gruchy)

#### Publication

#### Contents

The novel opens in the year 1421. England, though engaged in warfare in France, enjoys peace and prosperity at home, but Scotland is in a state of anarchy. Its king, James I, the caged lion of the title, has been a prisoner in England since boyhood, though the king, Henry V, treats him as a friend.

The chief character, Malcolm Stewart, is a timid, sickly, scholarly youth, who feels that the best way to protect his tenants and his sister is to give her in marriage to their soldierly cousin Patrick, and himself become a monk. This is found to be no solution. Lilias is placed in a nunnery, Patrick goes to fight the English in France, and Malcolm enters the service of his royal kinsman, James I.

The tale is partly concerned with Malcolm's spiritual journey, partly with historical events, Henry V's last expedition to France and his death, and King James' return to Scotland. The historical characters are major not background figures. Most of the action takes place in France.

While in England Malcolm improves in health and falls in love with Esclairmonde, who is vowed to a nun's life, and rejects him. He succumbs to the temptations of camp life in France, but repents and is able to save Esclairmonde from her wicked relatives. Returning to Scotland, he finds that his sister has been stolen from her convent, rescues her and restores her to Patrick who marries her. Malcolm gives up a life of peaceful scholarship to help King James bring order to Scotland. After the king's murder, he goes on pilgrimage to the Holy Land but dies on his return, having seen Esclairmonde again, and told her of the vision he has had of the two kings.

The historical characters reveal themselves in their relationships with each other and with the fictitious ones. Both kings are shown as enjoying the company of their ordinary subjects, both are stern judges. However, James is less pious and more easy-going than Henry, and this is revealed as they deal with Malcolm's shortcomings.

The novel shows a detailed knowledge of the customs and events of the period, but C.M. Yonge's admiration of the two kings leads her to a degree of historical distortion.

#### Further Reading

*For contemporary reviews see:*

**L. Madden**  
*J.B. Shorthouse and C.M. Yonge*  
Unpublished thesis  
University of London Diploma in Librarianship, 1964.

For other reviews or comments see:

**Romanes, Ethel**  
*Charlotte Mary Yonge. An appreciation*  
A.R. Mowbray & Co., London 1908

**Battiscombe, Georgina  
***Charlotte Mary Yonge. The story of an uneventful life.*  
Constable, London 1943  

**Alice Fairfax Lucy  
**'The other Miss Yonge', in*A Chaplet for Charlotte Yonge*.  
Edited for The Charlotte Yonge Society by Georgina Battiscombe and Marghanita Laski.  
The Cresset Press, London 1965

###   
Charlotte Yonge's own Preface to*The Caged Lion*

When the venture has been made of dealing with historical events and characters, it always seems fair towards the reader to avow what liberties have been taken, and how much of the sketch is founded on history. In the present case, it is scarcely necessary to do more than refer to the almost unique relations that subsisted between Henry V. and his prisoner, James I. of Scotland; who lived with him throughout his reign on the terms of friend rather than of captive, and was absolutely sheltered by this imprisonment throughout his nonage and early youth from the frightful violence and presumption of the nobles of his kingdom.

James's expedition to Scotland is wholly imaginary, though there appears to have been space for it during Henry's progress to the North to pay his devotions at Beverley Minster. The hero of the story is likewise invention, though, as**[Froissart](http://www.nipissingu.ca/department/history/muhlberger/froissart/tales.htm)**ascribes to King Robert II. 'eleven sons who loved arms,' Malcolm may well be supposed to be the son of one of those unaccounted for in the pedigrees of Stewart. The same may be said of Esclairmonde. There were plenty of Luxemburgs in the Low Countries, but the individual is not to be identified. Readers of Tyler's 'Henry V.,' of Agnes Strickland's 'Queens,' Tytler's 'Scotland,' and Barante's 'Histoire de Bourgogne' will be at no loss for the origin of all I have ventured to say of the really historical personages. Mr. Fox Bourne's 'English Merchants' furnished the tradition respecting Whittington. I am afraid the knighthood was really conferred on Henry's first return to England, after the battle of Agincourt; but human – or at least story- telling – nature could not resist an anachronism of a few years for such a story. The only other wilful alteration of a matter of time is with regard to the Duke of Burgundy's interview with Henry. At the time of Henry's last stay at Paris the Duke was attending the death-bed of his wife, Michelle of France, but he had been several times in the King's camp at the siege of Meaux.

Another alteration of fact is that Ralf Percy, instead of being second son of Hotspur, should have been Henry Percy, son of Hotspur's brother Ralf; but the name would have been so confusing that it was thought better to set Dugdale at defiance and consider the reader's convenience. Alice Montagu, though her name sounds as if it came out of the most commonplace novelist's repertory, was a veritable personage – the heiress of the brave line of Montacute, or Montagu; daughter to the Earl of Salisbury who was killed at the siege of Orleans; wife to the Earl of the same title (in her right) who won the battle of Blore Heath and was beheaded at Wakefield; and mother to Earl Warwick the King-maker, the Marquis of Montagu, and George Nevil, Archbishop of York. As nothing is known of her but her name, I have ventured to make use of the blank.

For Jaqueline of Hainault, and her pranks, they are to be found in Monstrelet of old, and now in Barante; though justice to her and Queen Isabeau compels me to state that the incident of the ring is wholly fictitious. Of the trial of Walter Stewart no record is preserved save that he was accused of '*roborica*.' James Kennedy was the first great benefactor to learning in Scotland, and founder of her earliest University, having been himself educated at Paris.

The Abbey of Coldingham is described from a local compilation of the early part of the century, with an account of the history of that grand old foundation, and the struggle for appointments between the parent house at Durham and the Scottish Government. Priors Akefield and Drax are historical, and as the latter really did commission a body of moss-troopers to divert an instalment of King James's ransom into his own private coffers, I do not think I can have done him much injustice. As the nunnery of St. Abbs has gone bodily into the sea, I have been the less constrained by the inconvenient action of fact upon fiction. And for the Hospital of St. Katharine's-by-the-Tower, its history is to be found in Stowe's 'Survey of London,' and likewise in the evidence before the Parliamentary Commission, which shows what it was intended by Queen Philippa to have been to the river-side population, and what it might have been had such intentions been understood and acted on – nay, what it may yet become, since the foundation remains intact, although the building has been removed.

C. M. Yonge.  
November 24, 1869

### The Caged Lion

#### Chapter titles

#### Contemporary Reviews

#### LITTELL’S LIVING AGE.  
No. 1350, April 16, 1870, page 160

#### The Caged Lion

By Charlotte M. Yonge, author of “The heir of Redclyffe.” (Macmillan and Co.)

There are very few women (or men) of our day so well read in mediæval history as Miss Yonge. From childhood the study seems to have been her passion, and in her “[Cameos](cameos.qmd)” she displays a familiarity with character and scenery which is rare and remarkable. In historical fiction she is also often successful; and if ever she fails, it is through the want of power to place her readers at her own point of view. Some of the characters and scenes in the*Caged Lion*will command sympathy, and they are clearly and graphically put. Thus, our Henry V. is sure to inspire the interest he deserves. We are not so sure about the Lion himself, James I. of Scotland. Yet we suppose, it is merely that he is overshadowed by his English friend and guardian King Henry. Less is known about James than could be wished. The history of his early life and training at Windsor, his genius, his beautiful poem of the “King’s Quhair” and his strong attachment to his native land, in spite of the gains of his captivity, require to be fully brought out, as well as the passages of his after life and disastrous death. Miss Yonge, who now (we believe, for the first time,) places her name on the title-page, gives us her authorities and points out her deviations from literal history in her preface. We think the book deserves to be well read, and that it will be much enjoyed.

Spectator.

### ***The Athenaeum***

*The Caged Lion*was reviewed in 1870 in*The Athenaeum*by Almaric Rumsey.  
Reference : 2215 (April 9,1870), 482 – 483

