---
title: "Cameos of English History, from Rollo to Edward II"
sort_title: "Cameos of English History, from Rollo to Edward II"
year: 1868-1899
slug: "cameos"
format:
  html:
    toc: true
---

### ****I.From Rollo to Edward II(1868)  
II. The Wars in France (1871)  
III. The Wars of the Roses (1877)  
IV. Reformation Times (1879)  
V. England and Spain (1883)  
VI. Forty Years of Stewart Rule (1887)  
VII. The Rebellion and Restoration (1890)  
VIII. The End of the Stewarts (1896)  
IX. The Eighteenth Century (1899)  
********

### ****

**Online text of**  
*Cameos of English History I*******–**From Rollo to Edward II****

[Click here to read the text of***Cameos of English History I***from Making of America books](http://www.hti.umich.edu/cgi/t/text/text-idx?type=boolean&subtype=bib&c=moa&sid=73b72f9dd127a4639b290c060f5327ca&q1=yonge%2C%20charlotte&rgn=author&view=toc&cc=moa&idno=ABA0299.0001.001&start=1&size=25)**  
**

### C A M E 0 S

### OF

### THE HISTORY OF ENGLAND.

### PREFACE

THE "Cameos" here put together are intended as a book for young people just beyond the elementary histories of England, and able to enter in some degree into the real spirit of events, and to be struck with characters and scenes presented in some relief.

The endeavour has not been to chronicle facts, but to put together a series of pictures of persons and events, so as to arrest the attention and give some individuality and distinctness to the recollection, by gathering together details at the most memorable moments. Begun many years since, as the historical portion of a magazine, the earlier ones of these Cameos have been collected and revised to serve for school-room reading, and it is hoped that, if these are found useful, they may ere long be followed up by a second volume, comprising the wars in France, and those of the Roses.

February 28th, 1868.

### INTRODUCTION

YOUNG people learn the history of England by reading small books which connect some memorable event that they can understand, and remember, with the name of each king—such as Tyrrell's arrow-shot with: William Rufus or the, wreck of the White Ship with Henry I. But when they begin to grow a little beyond these stories, it becomes difficult to find. a history that will give details and enlarge their knowledge, without being too lengthy. They can hardly be expected to remember or take an interest in personages or events left, as it were, in the block. It was the sense of this want that prompted the writing of the series that here follows, in which the endeavour has been to take either individual characters, or events bearing on our history, and work them out as fully as materials permitted, so that each, taken by itself, might form an individual Cameo, or gem in full relief; and thus become impressed upon the mind.

The undertaking was first begun sixteen years ago, for a periodical for young people. At that time, the view was to make the Cameos hang, as it were, on the thread furnished by ordinary childish histories, so as to leave out what might be considered as too well-known. However, as the work made progress, this was found to be a mistake; the omissions prevented the finished parts from fitting together, and the characters were incomplete, without being shown in action. Thus, in preparing the Cameos for separate publication, it has been found better to supply what had previously been omitted, as well as to try to correct and alter the other Cameos by the light of increasing information.

None of them lay claim to being put together from original documents; they are only the attempt at collecting, from large and often not easily accessible histories, the more interesting or important scenes and facts, and at arranging them so that they may best impress the imagination and memory of the young, so as to prepare them for fuller and deeper reading.

Our commencement is with the Dukes of Normandy. The elder England has been so fully written of, and in such an engaging manner for youthful readers, in the late Sir Francis Palgrave's "History of the Anglo-Saxons", that it would have been superfluous to expand the very scanty Cameos of that portion of our history. The present volume, then, includes the history of the Norman race of sovereigns, from Rollo to Edward of Carnarvon, with whose fate we shall pause, hoping in a second volume to go through the French wars and the wars of the Roses. Nor have we excluded the mythical or semi-romantic tales of our early history. It is as needful to a person of education to be acquainted with them, as if they were certain facts, and we shall content ourselves with marking what come to us on doubtful authority.

#### Literary Notes  
in  
Appletons' journal: a magazine of general literature.  
Volume 6, Issue 139, Nov 25, 1871, pp. 611–612

#### (Making of America Journal Articles)

In a review of Miss Yonge's "Cameos of English History," the London Spectator remarks: " We confess to grudging Miss Yonge to the writing of history, and none the less that her history is so well and picturesquely written. What we want from her is another sort of chronicle; that of the domestic life of the upper middle-class in England in the latter half of the nineteenth century; for, considered in its nobler and more religious aspects, no one describes it for us so truly. That her range is a very limited one she would be the first to acknowledge. The limitation is due, we suspect, to a deliberate intention. She is too true an artist to care to plunge into subjects which she has had no adequate opportunity of realizing to herself; and a certain severity of moral taste, which is as much a part of some natures as an objection to musk, makes her shrink from dealing with that which is not innocent. It is to the honor of our English homes that they have afforded honest matter to so genuine an artist. We think a great deal of the 'Paston Letters,' which are, if we rightly recollect, an earliest record of a purely domestic nature (of the reign of Edward IV.). What would we not give for a novelette from a Miss Yonge of the fifteenth century, telling us really how the well-born dames of that day dwelt in their moated manors? Be it noted that they were neither stupid nor illiterate, being the contemporaries of Margaret Beaufort. Had we their story truly told, how much else could we not infer of the state of men and manners? If Cuvier from a fossil bone could reconstruct the entire beast, the philosophic historian from one truly-tinted zone might be helped to recreate the various colors of national life at a given epoch. In the interest of future generations, and in order that they may not think that forging widows, golden-haired baronets, wives who have committed bigamy, dairy-maids who escape the gallows by a hair's-breadth, and gentlemen who shut up mad spouses in their attics, made the staple of English society in 1850 (we allude, as will be seen, to four of our greatest works of fiction by four famous hands), let us entreat Miss Yonge to give us as many varied pictures as possible of that peculiarly gracious English family life which is quite as true in its own way as any thing else in our time and country; which is the genuine outcome of certain religious forces proper to England; of which the home at Hursley was the great type and example, and its sainted master, John Keble, both a cause and a result.

