---
title: "The Castle Builders or the Deferred Confirmation"
sort_title: "Castle Builders or the Deferred Confirmation"
year: 1854
slug: "castle_builders"
format:
  html:
    toc: true
---


[Online text of : The Castle Builders](https://archive.org/details/castlebuilderso00yonggoog/page/n6/mode/2up)

Google scans  
PDF file available for download from the Google webpage.

#### *Text for this page kindly provided by Julia Courtney*

The castle builders are teenage sisters Emmeline and Kate Berners. As the novel opens their main "castle in the air" is to be reunited with their mother, who has been living in India, and their elder sister Constance, currently visiting Italy with their consumptive husband, the aristocratic clergyman Lord Herbert Somerville.

Dream become reality when the sudden return of the girls' mother, with her second husband and four young children, provides Emmie and Kate with a "ready made family". But their hasty removal from school prevents them from receiving the sacrament of Confirmation, so that the "wavering unstable Emmeline and unreflecting, easily-led Katherine" are left to face moral and physical dangers without the benefit of divine grace. Mama is worldly and indolent; her husband, Sir Francis Willoughby, is brusque and prosy, while the children range from the uncontrollable Alfred and Edwin to the screaming Cecilia and the whining unloved Janet. Unguarded among these difficulties, the sisters dabble in local charity work and indulge in fanciful daydreams while neglecting their home duties, until Sir Francis' son, Frank, comes to stay.

Aged seventeen, no intellectual, and an inveterate tease, Frank nevertheless has a real vocation to the Anglican priesthood. This cuts across Sir Francis' ambitions for his son, and after a severe spiritual struggle Frank agrees to abandon his clerical plans and follow filial duty into a Guards regiment. Even this fails to satisfy Sir Francis: High Church practices such as daily services and frequent Communion, must be given up as "new-fangled fancies" and perverseness, and Frank's refusal to yield results in a bitter impasse between father and son.

At this point Frank, Kate, Emmeline, and little Edwin spend an afternoon on the beach and are cut off by the rising tide. Frank dies a hero's death while the girls' narrow escape has a decisive effect on their subsequent lives. Kate, the more down-to-earth but hitherto more emotionally dependent sister, realises the essential importance of Confirmation and Communion; but once again the Sacrament is deferred, this time through the family's departure for the London Season.

While Emmeline, restless and dissatisfied, is enervated by the social "whirl", Kate is able to welcome elder sister Constance and brother-in-law Lord Herbert, High in rank, principles and church practice.

This clerical couple accept a living in a sordid, unromantic seaport very different form the rural parish of the young sisters' fantasies, but here Emmeline finally confronts her spiritual malaise, and at last the girls are to be Confirmed. One last sacrifice remains as they give up a family trip to Paris in order to attend the ceremony, but the novel ends with the sisters "in the full consciousness of our own weakness and of the all-sufficient grace".

#### THE CASTLE BUILDERS.  
By the author of "Heartsease."

#### in  
Notices of New Works  
Southern literary messenger; devoted to every department of literature and the fine arts  
Volume 21, Issue 5, May 1855, pp. 328  

#### (Making of America Journal Articles)

Miss Charlotte Yonge, the author of this work, has won for herself, by several previous novels of decided popularity, as wide a circle of admirers as any other lady writer of the day. The "Heir of Redcliffe" excited a sensation among the lovers of fiction which is without a parallel for the tears, copious and briny, that came during its perusal to all eyes. Perhaps there never was a volume that called for so constant an employment of the mouchoir or which passed from the hands of the overwhelmed reader in such a condition of dampness. "The Castle-Builders" makes no such large draughts on the lachrymal ducts, yet among a certain class of readers – the Episcopalians – it is likely to prove an edifying and pleasant affair. The design of it seems to be to show the importance of the rite of confirmation, and the sister-heroines are conducted along that beautiful valley of domestic life that lies between the world and the church, the shining heights of Fashion and the Delectable Mountains. The end of their pilgrimage is the altar, not however as all young ladies like to be led to it for the Solemnization of Matrimony, but for taking upon themselves the vows aforetime given by their sponsors in baptism. They are confirmed, not married :– have we a right to say of that other ceremony –*cela viendra*? Miss Yonge must determine.

