---
title: "Chantry House - Charlotte Mary Yonge"
year: 1886
slug: "chantry_house"
format:
  html:
    toc: true
---


###   
**Online text of***Chantry House*****

[Click here to reach the latest version of*Chantry House*from Gutenberg](https://www.gutenberg.org/ebooks/7378)  
(Many thanks to Sandra Laythorpe and others)

### Publication details, summary and further reading

(Kindly supplied by Amy de Gruchy)

**Publication**

1886 by Macmillan

Contents

*Chantry House*is a family chronicle narrated in his old age in the 1880s by Edward Winslow, a crippled semi-invalid. It commences with his recollections of his early childhood and that of his brothers Grif and Clarence.

The novel has two plots, linked by the theme of restoration. This theme also appears in the effect on the lives and actions of the characters of the Oxford Movement, which saw as its aim the restoration of the Church of England to its former dignity and influence.

In the first plot the second son, Clarence is court-martialled and dismissed from the Navy for petty offences when a sixteen year old midshipman. He atones for his wrong-doing by many years of uncongenial work, struggles against temptation and at length regains the love and esteem of his parents, finally becoming ‘a merchant prince’ renowned for good works and the head of his family. This is his moral restoration.

He is also instrumental in restoring the Chantry House Estate to its rightful owners, the second plot. When his father inherits the estate from a distant relative, the family are unaware that a hundred years earlier there had been a grave miscarriage of justice. Early in the 18th century Margaret Fordyce, the heiress of the estate married a Mr Winslow, and had been coerced into leaving it to her stepson rather than to her Fordyce relatives, and had then died in suspicious circumstances. Her ghost haunts the house, but apart from vague traditions these events and the subsequent feud between the two families have been forgotten. When the 19th century Winslow family take possession the Fordyce family consist of a father and son, both squarsons on the neighbouring estate and the wife and two daughters of the latter, Ellen and Anne. Friendship soon springs up between the families which is cemented when Grif Winslow rescues the Fordyces from a rioting mob. Grif and Ellen Fordyce fall in love and it would seem that the ghost is appeased. However Grif’s unworthy behaviour causes the Fordyce’s to break off the engagement. In pique he marries an extravagant young widow and Ellen dies of consumption and grief while the ghost resumes her annual visits.

Clarence, being psychic, has actually seen the ghost and can enter into her feelings. After Grif’s early death and that of his father, Clarence becomes the owner of the estate, and resolves with his younger brothers and sister that it must be restored to the Fordyces. To make a fortune large enough to keep themselves he goes to China for some years and returns rich but shattered in health, though able to carry out his plan. However Ellen’s father, Parson Frank points out that neither family has the right to the estate as the Fordyces acquired it at the Dissolution of the Monasteries, and it should be given to the Church. This is done. The Chapel is restored, and the house becomes an orphanage and convalescent home. Martin the youngest Winslow brother marries Ellen’s younger sister and the ghost is at rest at last.

Clarence, the hero, is constantly contrasted with his elder brother Grif. Grif is brave and popular, but selfish and shallow, a cheerful extrovert. Clarence is timid and humble, devout and self effacing. As a child his parents mistrust him. He is bullied at school and in the Navy and easily led astray by stronger characters. However his deep religious feelings overcome his weakness and while remaining gentle, loving and unselfish he develops into a strong determined man. Grif meanwhile deteriorates and as his weakness becomes apparent he becomes a burden to his family.

Edward the narrator is highly intelligent and perceptive. His portraits of his parents, stern and loving, the children’s harsh but loyal nurse, proud and pious Mrs Fordyce and her jolly and warm-hearted husband, Parson Frank, are all highly credible. However, as is natural, he has his blind spots. To him Ellen Fordyce is all that a young girl should be, purely good, deeply religious and romantic. He sees no fault in her love for Grif, though it reveals her poor judgement, which contrasts with that of her friend Emily Fordyce, who is also romantic but gives her love to a man who is of high moral and religious character. Edward’s blindness is understandable, for while revealing Grif’s faults to the reader, he seems almost unaware of them himself. Thus C M Yonge uses Edward’s pictures of others to reveal his own character.

A considerable amount of travel takes place in the novel, giving variety of scene, but the chief setting is the Chantry House itself with its haunted chamber and ruined chapel. The early part of the novel is set in the period of C M Yong’s early youth, and that of her parents, so there is much authentic detail. Historical events such as the battle of Navarino and the Captain Swing riots play a part in the narrative. Even more central is the role of the Oxford movement from its infancy onwards. Clarence is deeply moved by its teaching and influences his family. Parson Frank is also affected by it and in consequence leaves his comfortable country parish for a demanding one inn a seaside town in the north east, and as has been seen, restores Chantry House to the church.

The religious element in the novel is however well balanced. The Winslows were originally of the old High Church persuasion, but their children had a gentle Evangelical governess who greatly influenced Clarence and in her old age saved him from a grave temptation.

The moral teaching is implicit, not explicit. Religion can make the weak strong and turn the coward into a hero. Past wrongdoing can be atoned for, and its effects reversed, even if it takes many years or even centuries.

Further Reading

For contemporary reviews see L Madden*J B Shorthouse and C M Yonge*, unpublished thesis, University of London Diploma in Librarianship 1964.  
Katherine M Briggs “Folklore in the works of Charlotte Yonge”, Occasional papers of the K B Club, No 1, 1990.  

### Charlotte Yonge's Gothic Murder

### Ruth Bienstock Anolik – Haverford College

### **Ruth Bienstock Anolik**presented the following paper, then entitled***Charlotte Yonge's Gothic Murder***  
at the IGA Conference 2001 "Gothic Cults and Gothic Cultures".

Professor Anolik has since kindly provided us with the abstract and full text of this paper.  
Both are reproduced below.

ABSTRACTFULL PAPER

#### Gothic Murder: Containment of Horror in Charlotte Yonge’s Chantry House

#### Abstract

Charlotte Yonge is generally considered by critics to be the exemplar of conservative Victorian domestic fiction, representative of the middle class reaction to nineteenth century upheavals. Yet, it is possible to see in Yonge's seemingly settled and staid position the kind of paradoxical thinking that finds expression in the tense and unsettled Gothic mode. And indeed, Yonge does seem very much at home writing in the genre. Her immensely popular novel, The Heir of Redclyffe (1855), though largely a novel of middle class domestic life, the story of a noble, Christ-like character and his influence on a Victorian family, reveals a debt to the Gothic tradition.

An even more striking and sustained invocation of the Gothic narrative, still couched within a conventional Victorian narrative of domestic life, may be found in Yonge's later novel Chantry House (1886), less well-known today than Redclyffe. In this Gothic text, Yonge constructs a vehicle suited to her reconciliation of conflicting narrative strategies and, a text that evokes the typical Gothic struggles in order to settle them. In faithfully evoking all the Gothic conventions (murder, appropriated property, the besieged woman, dark family history, feuding families) in Chantry House, Yonge paradoxically constructs a safe, comfortably familiar, re-enactment of the mode, that allows her to endorse her conservative world view. Yonge thus succeeds in appropriating a typically unstable mode, a mode whose power derives from its instability, for stable ends.

In this, Yonge taps into a central paradox of the Gothic: the essential narrative strategy of this shocking and suspenseful mode is internal and external repetition. Horrifying and excessive though the tropes may be, the very nature of their unchanging repetition contains and dissipates their impact. One of the great pleasures of reading the Gothic derives from the paradox that Burke uncovers when he points out that sensations of pain and danger, when distanced by art, result in the pure delights of the sublime. Yet Yonge's narrative demonstrates that the comforts of the Gothic, providing the reader with safe frissons of horror in a comfortably familiar setting, can be taken to the extreme of denaturing the sublime.

The disabling of the conventions in Chantry House renders this Gothic text susceptible to the totalizing stability of the moral plane, the plane, upon which all dynamic struggles are deconstructed. In this, then, Yonge adds a new dimension to the Gothic text. While conventional Gothic texts struggle between the demands of reason, articulated through the imperatives of law, and the demands of imagination, articulated through the subversions of fantasy, Yonge's text subsumes the two poles on the moral plane. Rather than struggling to resolve the question of whether possession of Chantry House will be legally effected or dispossession imaginatively accomplished, Yonge's text posits the moral synthesis that will erase all questions of possession or dispossession, of reason or imagination.

Yonge's morality, in incorpating conflicting planes within the totalizing plane of Christian morality, lends an atypical solidity to the closure of her Gothic narrative. The moral plane becomes the totalizing plane on which all struggles and tensions are synthesized and subdued. This results in a closure that, while perhaps more pleasantly comfortable and more morally satisfying, is ultimately less dynamic than that of the typically disruptive Gothic text. Yonge discovers a way to successfully subdue all Gothic struggles and, in doing so constructs a narrative that fixes and kills the power of the genre. The Gothic is defined by the failure or refusal of the Gothic narrative to sustain the stability that most narratives endorse. In positing a plane where all struggles end, Yonge drains her Gothic narrative of its essential tension. Her Gothic narrative is, ultimately, Gothic in form only and, as Ruskin says of Gothic architecture, "It is not enough that it has the Form, if it have not also the power and life." (159) Yonge succeeds, then, in producing a text that heralds the death of the vibrant and complex Gothic mode, a death that is, ultimately, more horrifying than anything found in Walpole or Reeve.

Notes

[1] Later echoed in the bleak hope of Guy’s grandfather “that his sins would not be visitd on the head of his only descendant” (79).

[2] “Another branch of church reform promoted by mid-centiury Tractarians was the restoring of ancient religious buildings to functions appropriate to the present day” (Dennis 151).

[3] Recalling the site of Austen’s Gothic parody.

[4] That is, the law of 1707 when Margaret Fordyce writes her will and the law of the 1830’s when the action of Chantry House occurs. By the time of the writing of Chantry House, the Married Woman’s Property Act, which “secured to a woman as her separate property ‘all real and personal property which shall belong to her at the time of the marriage ’”had been enacted – in 1882 (Perkin 305).

[5] There is also a biographical explanation for Yonge’s preference for female property transmission: Yonge’s family inherited her beloved childhood home Otterbourne from her maternal grandmother; Yonge herself was displaced from the line of inheritance because of her gender.

### Gothic Murder: Containment of Horror in Charlotte Yonge’s Chantry House

### Ruth Bienstock Anolik – Haverford College

### FULL TEXT OF THIS PAPER  
(see above for abstract)

Charlotte Yonge is generally considered by critics to be the exemplar of conservative Victorian domestic fiction, representative of the middle class reaction to nineteenth century upheavals: the political upheavals that swept Europe in 1848, outbreak of the Crimean War, the Indian Mutiny of 1857, the crisis in the cotton mills of Northern England as a consequence of the American civil war, the publication in 1859 of Darwin's*Origin of Species*and the ongoing problem of Ireland and beginning in mid-century the movement for women's rights (Boas). Yonge, who was an enormously popular influence on middle class women readers, writes novels driven by virtue and morality. In writing of her politics, Sturrock states, "Yonge was no feminist; her response to the possibility of social change is invariably conservative" (15) "Her novels show an endless engagement with the subject of proper femininity" (27). As Sturrock notes Yonge's strong religious convictions, based on her association with the Oxford Movement, through her "quasi-filial relationship with John Keble who was vicar of Otterbourne" (21) were a clear source of her conventional world view, including the traditional role of women; Yonge was never associated with the early waves of feminism of the nineteenth century. And yet, as Sturrock also notes, Yonge's "religious convictions, formed, first by her father's High Church teachings and later by John Keble's Tractarianism, drove her to reject certain 'worldly' values" (16); her conservative religion paradoxically led her to discard certain Victorian conventions, for example, "to see that respectabiltiy was not the supreme moral virtue" (25).

So it is possible to see in Yonge's seemingly settled and staid position, the kind of paradoxical thinking that finds expression in the eternally tense and unsettled Gothic mode. And indeed, Yonge does seem very much at home writing in the genre. Her immensely popular novel (one of Yonge's few novels still in print today), The*Heir of Redclyffe*(1855), though largely a novel of middle class domestic life, the story of a noble, Christ-like character and his influence on a Victorian family, reveals a debt to the Gothic tradition. Among the Gothic motifs to be found in*Redclyffe*are the massive ancestral home, the ancestral curse, contested property, questions of inheritance, suspicions of ghosts, conflation of marriage and death, as well as an invocation of the lines that might well be the mantra of the Gothic (cited by both Walpole and Hawthorne in the prefaces to their Gothic texts and by Collins in*The Woman in White*): "the sins of the fathers shall be visited on the children" (71)(footnote 1).

An even more striking and sustained invocation of the Gothic narrative, still couched within a conventional Victorian narrative of domestic life, may be found in Yonge's later novel*Chantry House*(1886), less well-known today than*Redclyffe*. Yonge's affinity for the belated, nostalgic, Gothic text, that yearns to return to the idylls of the past, can be partially explained by her stance as as a conservative novelist. Yonge, too, is driven by nostalgia, the desire to return to simpler, better times. In*Chantry House*, Yonge personalizes Gothic nostalgia, revisiting her own childhood experience of Otterbourne, the site of the Yonge family home in the 1820's before the time when "church restoration was settling in" (Chantry House 2.120).(footnote 2). Battiscombe writes

In*Chantrey House*, a story of rural England in the days of George IV, she recaptured for a moment the atmosphere of that lotus-eating time before steam-engines ruined the peace of the country-side or*The Tracts for the Times*blew a blast loud enough to wake even the Church of England from slumber The years preceding the publication of*Chantry House*saw changes at Otterbourne [that] must have recalled her childhood to her with peculiar and rather bitter vividness. In 1884, a year before the publication of*Chantrey House*, Julian Yonge [Charlotte's brother] sold Otterbourne House and moved away from the neighborhood, and Charlotte knew that after her death there would be no member of her family to carry on the tradition of public service and private piety. (154)

But*Chantry House*is not only an outburst of nostalgia for a lost past; in the Gothic text, always susceptible to tense struggle, Yonge discovers a vehicle suited to her attempt to reconcile conflicting narrative strategies and ideologies, resulting in a text that evokes the typical Gothic struggles in order to settle them.

*Chantry House*is quite firmly located within the Gothic tradition, evincing all the familiar, and by the late nineteenth century, clichéd trappings, that began as eighteenth century conventions. Chantry House, the home of the Winslows, is clearly located in the Gothic landscape. Built upon an ancient abbey, erected in 1434 (footnote 3), the house reveals an interesting blend of modern and Gothic architecture. Although built in Queen Anne style, it features a "Gothic porch and a flagrantly modern Gothic porch it was, flanked by two comical little turrets there was [a] modern addition in Gothic taste, i.e.with pointed arches filled up with glass over the sash-windows"(1.73). In this early description of the house, it is possible to see an emblem for the strategy of Yonge's narrative; her tactic for balancing the competing demands of conservative domestic realism and the subversiveness of the Gothic mode. For, rather than present a dark, tension between conflicting styles, she negotiates them with humor: the porch, in which Gothicism is tempered by the influence of Victorian architecture, becomes a comical image of synthesis rather than a tragic image of struggle.

Chantry House reveals itself to be an appropriately Gothic structure in being suitably haunted. The mullion rooms in the older end of the house, with "deep mullioned windows and very handsome groined ceilings" (1.74) are regularly visited by the ghost of a previously dispossessed inhabitant, Margaret Fordyce. Margaret, as the Winslows discover, had lived at the turn of the eighteenth century and had been the second wife of a Winslow ancestor. After the death of her husband, her stepsons imprisoned and killed her. Margaret makes a series of appearances, generally to Clarence, the second son of the Winslows, who is himself displaced by virtue of birth order and family events, a subtle critique of the dispossessing effects of primogeniture. These appearances culminate in the ghostly re-enactement of Margaret's imprisonment and death. But here too, Gothic excess and tension is mitigated by Yonge's text. Margaret's appearances are goverened by the rule of order: her ghost appears in a regular, predictable way, always around the New Year.

The course of Yonge's narrative follows the typical narrative pattern of the Gothic text, tracing the Winslow family's discovery of Margaret's buried story. Not until the conclusion of the novel is the last piece of evidence, Margaret's body, uncovered. In the course of preparing for one of the weddings with which the novel conventionally concludes, workers, digging in the foundations of the house discover, "an old chest, and within lay a skeleton, together with a few fragments of female clothing, a wedding ring ghastly confirmation to connect the bones with Margaret" (2.224). On "the ensuing night there was a strange, quiet funeral service at Earlscombe church" (2.225); the narrative is safely laid to rest with the burial of Margaret's bones. This unburial and reburial, indeed, any kind of burial, is typical of the Gothic. It recalls scenes in Reeve's eighteenth century*The Old English Baron*,*Wuthering Heights*, and countless other Gothic texts. This trope is frequently given a psychological interpretation, as representing the return of the repressed; and, indeed, that reading is quite satisfactory. However, Yonge's Christian context allows for another way to read this trope, one that may be applied to its appearance in Gothic texts by other writers as well. This focus reveals the Christological roots of the trope of the restored and reburied body in which the restoration of the dead body leads to the establishment of a new order.

Margaret's history demonstrates the deployment of another Gothic convention: the misappropriated property. The Winslow brothers killed Margaret to steal her property (inherited by her from her family), Chantry House. Suppressing a will that bequeaths the estate out of the Winslow family, they renew an earlier, invalidated, will to legitimize their claims. Immediately, we can see in this narrative the typical Gothic conflation of fantasy and law. The two brothers, who have no problem murdering their stepmother, resort to legal (though invalid) documents to support their property claims. The resulting suspicion on the part of the Fordyce family regarding their relative and property leads to a feud between the two competing families, representing another conventional motif. Additionally, the Winslows learn from an old witch-like woman that there is "a course on you all! The poor lady as was murdered won't let you be! It's well known as how the curse is on the first-born. The Lady Margaret don't let none of 'em live to come after his father" (1.153 -4). This instance of supernatural is also contained and rationalized by the legal written word; the Winslows consult "the registers" (1.154) and discover that in every recorded branch of the Winslow family, including their own, the first born has died. Subsequent discussions lead to another opportunity to contain disorder through words. A family friend, Henderson, "had some very interesting talks with us two over ancestral sin and its possible effects." However, his context is not the Gothic; Henderson evokes "the 18th of Ezekial as a comment on the Second Commandment" (1.155). Henderson counters the words of the Second Commandment, the threat to visit "the iniquity of the father upon the children " (Ex. 20. 5) with the more temperate words of Ezekial: "The son shall not bear the iniquity of the father with him" (18.20). Yonge thus evokes the Bible, her primary text and influence to reconcile two ideologies that compete within the Bible as well as within the Gothic text: irrational vengeance and rational justice. Here too Yonge reveals her faith in the organizing, rationalizing powers of the written word, and most particularly, the Word.

Yonge works to expand the context of disrupted inheritance in her Gothic narrative, once again reverting to the conventions of the Gothic. Margaret's curse is directly responsible for the Winslow's surprising inheritance of Chantry House, having eliminated family members more directly in the line of inheritance. But this is just the last in a long line of disruptions that have broken the line of orderly property transmission. The original abbey built as a chapel in 1434, "was granted to Sir Harry Power" (1.65). This neutral "granting" suppresses the true meanings of this event: the appropriation of Catholic property during the Reformation. As Edward, the son of the family who narrates the story acknowledges, the family cherishes "the broken bits of wall and stumps of columns, remnants of the chapel" as charming garden elements, never "troubl[ing] ourselves about the desecration" (1.75). The retrospective awareness of Edward, who tells the story as an old man, that neutral "granting" was accompanied by destructive "desecration" discloses Yonge's endorsement of the passage of time to balance two competing views: the placid conservative acceptance of the young Edward and the more skeptical awareness of the abuses of power of the older, wiser Edward. Yet another disruption in transmission occurs as the property passes "through two heiresses" the last of whom, Margaret Fordyce dies "childless, leaving the estate to her stepson, Philip Winslow, our ancestor" (1.65).

In proper Gothic fashion, the various matches that are proposed to unite the competing families and consolidate the claim to property are consistently interrupted. The earlier engagement of Griff, the eldest surviving son of the Winslows to Ellen, the daughter of the Fordyces, is interrupted due to Griff's dissipation (the cause of the deferral of the marriage in Radcliffe's*Mysteries of Udolpho*); the match is finally cancelled by Griff's ill-judged marriage and Ellen's subsequent death. The plan by Clarence, the second Winslow son, to marry the younger Fordyce daughter, Anne, is deferred by a particularly nineteenth century obstacle; Clarence goes off to Hong Kong, "which was then newly ceded to the English and where the firm wished to establish a house of business" (2. 184). The narrative does manage to end with the typical Gothic closure of consolidating marriage: the two youngest children of the Winslow and Fordyce families marry. In arranging her marriages, Yonge adheres to a convention that appears in the female Gothic from Radcliffe on: although the marriages effect dynastic goals, they are based on love, not economics. Although the union of Ellen and Griff would have settle the property dispute, it was a love-match, made before the dispute was revealed. Martyn and Anne marry because they realize that "what they had felt for each other all their lives was love" (2. 221).

Yonge, then, evokes all the Gothic conventions to unfold her story, constructing an appealing, comfortable and, ultimately, safe re-enactment of the mode. In this, it is possible to see why the Gothic mode appeals to Yonge, allowing her to endorse her conservative world-view. Yonge succeeds in appropriating a typically unstable mode, a mode whose power derives from its instability, for stable ends. Her text so closely follows Gothic convention that it lacks any suspense or surprise. In her careful re-enactment of the myriad conventions of the Gothic mode, a catalog of conventions that are more than a century old when deployed in*Chantry House*, murder and theft become comfortingly familiar. In this, Yonge taps into a central paradox of the Gothic: the essential narrative strategy of this shocking and suspenseful mode is internal and external repetition; the Gothic is defined by a set of recurring conventions. Horrifying and excessive though these conventions may be, the very nature of their unchanging repetition serves to contain and dissipate their impact. One of the great pleasures of reading the Gothic derives from the paradox that Burke uncovers when he points out that sensations of pain and danger, when distanced by art, result in the pure delights of the sublime. Yet Yonge's narrative demonstrates that the comforts of the Gothic, providing the reader with safe frissons of horror in a comfortably familiar setting, can be taken to the extreme of denaturing the sublime.

In Yonge's text, the disabling of the conventions renders the Gothic text susceptible to the totalizing stability of the moral plane, the plane upon which all dynamic struggles are deconstructed. There are a number of occasions in Yonge's text in which competing ideologies of possession are reconciled on the moral plan. These episodes represent the only significant revisions that Yonge makes in the conventional Gothic narrative. As the Winslows come to discover the unsavory origins of their inherited property, Yonge deploys the imperatives of morality to reconcile competing demands for property and to trump those of law and tradition. Even subversive feminism can be absorbed by Yonge's totalizing morality. The Winslows discover that the last rightful owner of the property was Margaret Fordyce and that it thus belonged by rights to the Fordyce family. Significantly, Margaret acquired her property by inheriting it from her family, not, as was more typical of woman in the eighteenth century, though marriage. Morever, Margaret inherited her property from another woman. It becomes clear that the real crime of the Winslows is that they have disrupted a female line of property succession, making Margaret's curse, which blasts the male line of primogeniture, a particularly apt vengeance and a particularly horrifying instance of the power of female speech. Yonge's particular indictment of primogeniture in the instance of Margaret's curse and Clarence's struggles reflect a historical struggle of her times, a struggle whose moral undertones would have appealed to Yonge. Primogeniture was identified as "the root of evil" in the Free Trade in Land literature of the 1870's because it led to concentrations of large estates held by a small minority of the population (Offer 40).

Yonge painstakingly constructs a character who explicitly emblemizes herself to make an explicit pronouncement on the issue. The Winslows are visited by Miss Selby, a kind "elderly spinster" (1.104), much like Charlotte Yonge. It is she who declaims to Edward: "Margaret Fordyce was the heiress, and had every right to dispose of her property" (1.105). By the lights of tradition and law (footnote 4) this is patently untrue; by the lights of feminism, couched as morality, this is indeed correct and this is , in fact, the resolution that the narrative endorses. (footnote 5) Feminism, law and traditon are all reconciled by the simply moral statement of a kindly old lady.

The larger claims of morality supersede Margaret's legal and feminist claims as well; the property, the source of struggle and discord, as is all Gothic property, is disposed of in a particularly harmonious way. In her deployment of the trope of destroyed Gothic property, Yonge introduces an important variation of the theme. The ultimate solution to the conflicts surrounding Chantry House, is accomplished, not with the conventional compromise of dynastic marriage, but with a uniquely moral disposal of the Gothic property. In Yonge's moral formulation, the family is dispossessed of the House because they willfully give it up to be used as an orphanage, a cheerfully Victorian version of a tragic Gothic ending. In this, then, Yonge adds a new dimension to the Gothic text. While conventional texts struggle between the demands of reason, articulated through the imperatives of law, and imagination, articulated through the subversions of fantasy, Yonge reconciles the two on the moral plane.

The central conflict in Chantry House becomes, then, not the question of who will win, whether possession will be legally effected or dispossession imaginatively accomplished; Yonge's text considers how to effect the moral approach that will erase all questions of possession or dispossession. The Winslows struggle with this question from the time the discovery of the misappropriation is made. When Clarence Winslow, thinking on the legal plane, declares that Margaret's newly discovered will "will hardly invalidate our possession after a hundred and thirty years," Emily, his sister, rebuts the law with the moral view. The central quandary for the Winslows becomes how to restore the property to the Fordyce's. Even imperialism is subsumed under the umbrella of morality. In Hong Kong Clarence's actions serve to conservatively endorse the appropriating ideology of empire, or at least empire as practiced with a moral religious sensibility; he achieves great success and wealth "without soiling his hands with the miserable opium traffic" (2.192). Moreover, Clarence's enterprises in Hong Kong are revealed to be inspired by his moral desire to earn enough money to pay the Fordyce's for the appropriated property.

Yonge's morality, in incorporating conflicting planes within the totalizing plane of Christian morality, lends an atypical solidity to the closure of her Gothic narrative. The moral plane becomes the totalizing plane on which all struggles and tensions are synthesized and subdued. This results in a closure that, while perhaps more morally satisfying, is ultimately less dynamic and interestingly tense than that of the typical disruptive Gothic text. Yonge discovers a way to successfully subdue all Gothic struggles and, in doing so constructs a narrative that fixes and kills the power of the genre. The final failure of both the utopian subversive vision and the conservative vision of restoration is itself the defining moment of the Gothic mode and is, finally, the source of horror and delight in the Gothic. The Gothic is defined by the failure or refusal of the Gothic narrative to sustain the stability that most narratives endorse. In positing a plane where all struggles end, Yonge drains her Gothic narrative of its essential tension. Her Gothic narrative is, ultimately, Gothic in form only and, as Ruskin says of Gothic architecture, "It is not enough that it has the Form, if it have not also the power and life." (159) Yonge succeeds, then, in producing a text that heralds the death of the vibrant and complex Gothic mode, a death that is, ultimately more horrifying than anything found in Walpole or Radcliffe.

