---
title: "Le Chateau de Melville"
sort_title: "Le Chateau de Melville, ou Recréations du cabinet d'étude"
year: 1839
slug: "chateau_de_melville"
format:
  html:
    toc: true
---



#### The following items are all take from: Mitchell, Charlotte; Jordan, Ellen; Schinske, Helen:  
  
[The Letters of Charlotte Mary Yonge](http://hdl.handle.net/10065/337)[(1823-1901) - Letters to 1859](http://hdl.handle.net/10065/337)

  
Editors' explanatory note about*Le Chateau de Melville*

*Le Château de Melville*was a frame story, constructed around Charlotte Yonge's tale 'The Young Ladies', into which are inserted her French translations of eight stories from various sources, including Lucy Lyttelton Cameron,*The Faithful Little Girl*(1826), some version of or sequel to Friedrich Wilhelm Carové,*Das Märchen ohne Ende*, and a fairy tale by Catherine Talbot (1721-1770). ... Some characters in Yonge's*Scenes and Characters, or, Eighteen Months at Beechcroft*(1847) were based on those in*Le Château de Melville*.

  
Extract from a letter: Charlotte Mary Yonge to Anne Yonge [March 1836]

  
Extract from a letter: Charlotte Mary Yonge to Anne Yonge [ late December 1838 or early January 1839 ]  

... I think you will be surprised to hear of your old friends the Young Ladies being in print. The truth is, that we were somewhat in despair about the Girls' School. We would have another bazaar if we had not thought that people would be tired of it; so mamma and I were one day looking over my French translations which had all been duly corrected by the old Monsieur. They consisted of the Faithful Little Girl, Corylla, Mamma's New Story without an End, a Fairy Tale of Miss Talbot's, etc., which, using the Young Ladies as a peg to hang them upon, we thought would do very well to publish for the benefit of the School, so the Young Ladies really made a very pretty story, with the nonsense being taken away as much as we could. The papa is a Colonel at first and then Jules goes into the army, and the story ends with Aunt Selina, Henrietta, Rosalie and Pauline setting off to join them at Paris, just after Waterloo. I hope the story is not very foolish, but I am in hopes that it has a little better moralité than the French stories by the French themselves usually have.

Now the cost of printing 300 copies will be £30, and when we can get 109 copies taken at 5s. 6d. apiece, the printing will be paid for, and the rest will be clear gain to the School; but as we do not mean to run any risk, it is not to be printed till we have 100 copies promised to be taken, and I want to know how many you think you will be able to dispose of for us. I hope, Anne, you do not think me horribly vain and presumptuous, but I am sure I should be glad to be able to do the slightest thing for the School, and if you find anything very nonsensical, you must remember it was written by your shatter-brained cousin of fifteen. It is to be called*Le Château de Melville*, ou Recreations [sic] du Cabinet.d’Étude1. I am going to have the sheets looked over by M. de Normanville. About thirty copies we can reckon upon.  

####   
Extract from a letter: Frances Mary Yonge to Mary Anne Dyson [June 14, 1849]

My dear Miss Dyson

If developments interest you, you should begin with Charlotte long before*Abbey Church*, and trace the dawnings, not only of herself, but of some of the*Beechcroft*young ladies in the*Château**de Melville*. Let me send you one if you have not seen it, and if ever you begin to teach your herd to low in French, we can furnish a complete stock. The French is probably good enough for beginners, and it is at all events free from any breach of the third commandment, a fault that seemed to belong to all French books for children when I knew anything about them.

####   
Extract from a letter: Charlotte Mary Yonge to Mary Anne Dyson {June 1849]

I send a*Château de Melville*, and if you do not stick fast in it I should be amused to hear if you can identify the people with the Magnanimous Mohuns in their youth, that is to say, tell which is the origin of which. I have a most funny series of MSS. connecting them, which my executors may hereafter publish as a curious piece of literary history- I don’t mean that I keep them for the purpose, only they are so comical that I cannot find it in my heart to throw them away, such absurd pieces of advice as the old people do give! and the pathetic parts so ridiculous. You will meet with the origin of Ben and Philip there.  
  
(*.. the Mohun family in Scenes and Characters (1847) are descendants of the characters in Le Château de Melville*)  
  

#### Extract from[John Keble's Parishes](john_keble_parishes.qmd)by Charlotte M Yonge

... A school for the boys was built on a corner of the ground intended as churchyard, and a larger room added to the girls’, the expense being partly defrayed by a bazaar held at Winchester, and in part by Charlotte Yonge’s first book,*The Château de Melville*, which people were good enough to buy, though it only consisted of French exercises and translations.

#### What about therealChateau de Melville?

#### [It's in Saint-Martin-Les-Langres](http://www.tourisme-langres.com/page.php?rub=99&surb=&ssurb=&w_table=patrimoine_culturel&id=PCUCHA5280003006&lg=fr)- click here to see more details ...

