---
title: "The Chosen People by Charlotte Mary Yonge"
year: 1862
slug: "chosen_people"
format:
  html:
    toc: true
---


### **Online texts of*****The Chosen People***

[Click here to reach a nice version of**The Chosen People**from Making of America books](http://www.hti.umich.edu/cgi/t/text/text-idx?type=boolean&subtype=bib&c=moa&sid=367abe2f2ba9f48e6391dbffce2ec7c8&q1=yonge%2C%20charlotte&rgn=author&view=header&cc=moa&idno=AJG2915.0001.001)  

or

[Click here to reach**The Chosen People**from Google Book  
](http://books.google.com/books?vid=0P4T3_AaYs0ufZ6M&id=kJ8CAAAAQAAJ&pg=RA1-PA1&dq=charlotte%2Byonge&as_brr=1&hl=en#PPP10,M2)Google scan of a Bodley copy: includes downloadable PDF  

#### Charlotte Yonge's own Preface toThe Chosen People

IN drawing up this little book, at the request of several friends, the Author has been chiefly guided by experience of what children require to be told, in order to come to an intelligent perception of the scope of the Scripture narrative treated historically. Since a general view can hardly be obtained without brevity, many events have been omitted in the earlier part, and those only touched upon which have a peculiar significance in tracing the gradual preparation for the work of Redemption; and though one'great object has been'the illustration of Prophecy, the course of types has been passed over, lest the plain narrative should be confused, since types are rather subjects of devotional contemplation than of history, and they should be perfectly comprehended as facts, before being treated as allegorical.

The next portion is little save an abridgement from Prideaux's Connexion, taken in connection with the conclusions drawn by modern discoveries, as detailed in Mr. G. Rawlinson's valuable edition of Herodotus. It is hoped that by thus filling up the interval between the New and Old Testaments, that children may thus be fairly able to understand what they read in the Gospels of the Roman dominion, the relation to Herod, the mutual hatred of the Pharisees and Sadducees, and the enmity to the Samaritans.

The concluding lessons are offered with great diffidence, and with many doubts whether the absence of detail may not prevent them from being easily remembered; but it has been felt important that the connection of the actual Church with that of the Apostles and Martyrs, should be made evident to the general mind, and the present condition of the Church accounted for. The choice of subjects has been very difficult; but it is hoped that those selected may be those most needful to be known as evidence that our present-Church has every claim to the promise of Him Who will abide with her for ever.

If older and more critical persons than those for whom the little work is intended should cast an eye over it, the author hopes that they will bear in mind how the need of being both brief and clear is apt to render statements apparently bolder, and sometimes harsher, than where there is room for qualification or argument; and that they will not always accuse the work of unthinking boldness of assertion, where the softening is omitted for fear both of wearying and perplexing the young reader.

The chronology, for the sake of the convenience of teachers and scholars, is that of the margin of our Bibles.

The questions at the end are chiefly intended to direct the mind of the learner to the point of each lesson. It will be perceived that the answers must be prepared as well from the Bible as from the book; and in most cases the teacher will in use have to multiply, and perhaps to simplify them. One of their especial objects has been to show the ever brightening stream of prophecy, and afterwards, its accomplishment alike with regard to heathen nations, to the history of the Jews, of the Church, and, above all, to the Life of our Blessed Lord; and it is hoped that those who examine into them, cannot fail to be struck with the full and perfect accordance of the beginning with the end; and if they learn no other lesson, will have it impressed on them, how "the counsel of the Lord endureth for ever."

Two tables have been added for the convenience of the scholar, one giving the contemporary kings and prophets, the other the course of historical chapters, with, as far as possible, the prophetical, didactic, or poetical books, of the same date ranged in parallel lines. It is hoped that these may be found useful in arranging lessons for upper classes or pupil teachers.

May 20th, 1859.

