---
title: "The Clever Woman of the Family by Charlotte Mary Yonge"
slug: "clever_woman_of_the_family"
format:
  html:
    toc: true
---


#### Online textNew printed editionShort summary  
Full summaryArticle by Janice Fiamengo  
Dissertation by Diana Pharaoh FrancisContemporary review

### Online text of The Clever Woman of the Family

Click here to reach the latest version of[The Clever Woman of the Family](http://onlinebooks.library.upenn.edu/webbin/gutbook/lookup?num=3292)from Gutenberg  
(Many thanks to Sandra Laythorpe and others)

  
**The Clever Woman of the Family**on paper

Broadview Press republished this book in an edition by Clare A. Simmons (September 2001) .  
[Click here to see the publisher's information page](https://broadviewpress.com/product/the-clever-woman-of-the-family/#tab-description)including contents list and limited preview (retrieved 29 April 2022).

### The Clever Woman of the Family (1865)

### Short summary

#### *Text for this summary kindly provided by Celia Bass*

The time of the novel is approximately the 1860’s; the place, Avonmouth, a sea-side resort; the unlikely heroine, Rachel Curtis, pedant, frustrated social reformer, self-styled old maid. The plot charts the stages of her downfall from a position of confident intellectual superiority to humble acceptance of her limitations both as a thinker and as a philanthropist. The method used by Charlotte Yonge to reveal the absurdity and danger of her assumptions is dramatic, usually comic, irony.

Through her cousin, the gentle, recently widowed Fanny Temple, whose arrival in Avonmouth initiates the action, Rachel meets a number of people who challenge her ideas. They shake her unwarranted confidence in her own judgment but rescue her from the consequences of her folly. Ironically, Rachel has patronised, snubbed or suspected every one of them . Yet she admires and trusts the chance-met, sinister Mauleverer. He takes advantage of her desire to help the young lacemakers of the town, with disastrous consequences for them and for her. Yet the novel ends on a cheerful note with two weddings, plus the revelation that it is not Rachel but the poor cripple, Ermine Williams, sister of the Temples’ governess, who is the true ‘Clever Woman’ of the title.

*Back to top of page*

### Full summary

#### *Text for this summary kindly provided by Celia Bass*

Rachel Curtis is the ‘clever woman’ of the title. She is an unlikely heroine: a solemn pedant and would-be social reformer, a misfit in the staid society of the sea-side town where she has reigned as intellectual queen for most of her twenty-five years, to the mingled admiration and irritation of her neighbours, her timid mother, and her sensible, conventional sister, Grace.

The first challenge to her powers comes with the arrival of her cousin, the gentle, recently widowed Fanny Temple together, with her many charming but undisciplined children, whom Rachel undertakes to educate - with no success whatsoever. Fanny finds a governess. The confrontation between Rachel and the defiant boys and their no less defiant mother is the first of many encounters in which Rachel, to the reader’s amusement, realises her limitations too late. Her discomfiture is made the more absurd by her jealous, ill-founded suspicions of Fanny’s friend and trusted adviser, Colonel Colin Keith, formerly*aide de camp*to Fanny’s husband, General Temple. She is equally suspicious of another of Fanny’s entourage, Captain Alexander Keith, whom she despises as a ‘carpet knight’. He is a V.C.

The ironies are compounded when Rachel, egged on by Alexander Keith’s sister, the charming, disingenuous Bessie, puts her trust in a chance-met stranger, the sinister Mr Mauleverer. He encourages her to put her theories of social reform into practice by establishing a school to improve the lot of the child lace-workers of the town, with disastrous consequences.

In counterpoint to the tragi-comic vicissitudes of Rachel is a subplot concerning the thwarted love of Colonel Keith and the governess’ sister, Ermine Williams. Ermine is crippled, poor, confined for much of the time to one small room. However, she is not the victim that she seems. She is, in fact, the true ‘clever woman’, as the reader - but not Rachel - soon realises.

The two plots are gradually brought together as Rachel learns, partly from her own mistakes, partly from the advice and good example of others, that though she is less clever than she thought, she is much more loveable.

In consequence, despite two deaths and a nightmare trial, the novel ends happily.

*Back to top of page*

*Forms of Suffering in Charlotte Yonge's The Clever Woman of the Family*  
Victorian Review, Volume 25, Number 2 (Winter 2000) pp. 80-105.

*Back to top of page*

Diana Pharaoh Francis  

Ph.D. English Ball State University, 1999  

DISSERTATION:  
"Models to the Universe": Victorian Hegemony and the Construction of Feminine Identity  
Ball State University, 1999

*This paper is available online as a PDF (retrieved April 29 2022)*.

In 1860s Victorian England the ideology of the domestic angel collided head on with a competing feminine reality challenging the normalization of the domestic angel.

Drawing on the theories of Michel Foucault, Pierre Bourdieu, and Albert Memmi, this dissertation examines the characterizations of women in light of the beleaguered domestic angel ideology, focusing on Emily Eden¹s The Semi-attached Couple,**Charlotte Yonge¹s The Clever Woman of the Family**, Margaret Oliphant¹s Miss Marjoribanks, Ellen Wood¹s East Lynne, and Mary Elizabeth Braddon¹s Lady Audley¹s Secret.

What is revealed is the underlying structure of power which inculcated women into a system of coerced self-regulation, encouraging cooperation and complicity through surveillance, punishment and reward. Yet despite this exposure of the constructed nature of women¹s roles, these novels finally serve hegemony, valorizing the domestic angel version of 'true womanhood' while condemning and censuring those women characters who, for whatever reason, fail to conform.

### Contemporary Review from*The Athenaeum*

*The Clever Woman of the Family*was reviewed in 1856 in*The Athenaeum*by John Cordy Jeaffreson (variant spelling Jeffreson).  
Reference : 1954 (April 8,1865), 489

