---
title: "The Constable's Tower, or, the Times of Magna Carta"
sort_title: "Constable's Tower, or, the Times of Magna Carta"
year: 1891
slug: "constables tower"
format:
  html:
    toc: true
---


[Click here to reach the latest version of*The Constable's Tower*](http://ia340905.us.archive.org/1/items/constablestowero00yong/)  

### Charlotte Yonge's own Preface to***The Constable's Tower***

HUBERT DE BURGH, a man of unflinching faith, courage, and loyalty, is one of the few fCharta on behalf of the king, but he did not take part with the Barons when John attacked them, holding himself bound by his faith to the king.

For fifteen weeks Dover Castle was held against Louis the Lion; but it must here be explained that there is no authority for Hubert's then having had a daughter, though he could not have been at that time a very young man; but it was not till after the troubles of John's reign, when he was Justiciary of England, that he is known to have married the sister of the Scottish king.

The events of the close of the siege, and the threat to execute Thomas de Burgh before his brother's eyes, are matter of history. The relief by Pencester belongs to the story of the Castle, and likewise that Pencester succeeded to the government of it, and left a tower called by his own name.

During the minority of Henry III., all went well with Hubert, and he recovered for the crown much that had been alienated under John, but his stern uprightness offended many of the nobles, and the Bishop of Winchester was his bitter enemy. This man, whose French name was Pierre des Roches, had been designated by the great Friar Bacon as a dangerous person in the saying, 'Beware of stones and of rocks.' He gained the ear of the foolish young king, whom he actually persuaded to proceed against Hubert for having gained his affections by sorcery, with other equally frivolous charges. Hubert took sanctuary at Merton Abbey, and the king actually ordered the Lord Mayor to take a body of men and remove him by force. The Archbishop of Dublin, however, protested against such an act of sacrilege, and messengers were sent to stop the Mayor. While the good archbishop secured that four months should be granted to Hubert in which to prepare his defence, during which time he was to be at large.

Nevertheless, when he set out to see his wife at St. Edmund's Bury, the king was persuaded to send his old enemy, Geoffrey de Crawcombe, leader of the Black Band, to seize him on the way. De Burgh was in bed at the little town of Brentwood in Essex when he received warning, and fled, still unclothed, to the church, where, with the crucifix in one hand and the Host in the other, he stood by the altar. The Black Band were not, however, thus to be withheld. They rushed in with drawn swords, dragged him out, and fetched a smith to put fetters on him.

The brave blacksmith, however, stood firm, declaring that he would rather die the worst of deaths than put irons on the man who had saved Dover and driven away the French fleet.

However, these shameless men put this great and valiant knight on horseback, just as he was, and carried him to the Tower of London. At this, such a storm was raised by the clergy on the violation of sanctuary, that Henry was forced to send him back to Brentwood Church, but at the same time was dastard enough to command the Sheriff of Kent to blockade him there on pain of death. A palisade was erected round the churchyard, a trench dug, and the Black Band watched day and night, but it was not till the fortieth day that he was starved into surrendering.

He was taken back to the Tower, and by-and-by was stripped of all save his own hereditary possessions, and sent a captive to the Castle of Devizes. There he remained nearly a year, when, learning that his worst enemy, Pierre des Roches, had obtained the castle, he resolved to escape at any risk, and in the middle of a dark night he climbed over the battlements, and dropped into the moat, whence he proceeded to a country church. Again he was beleaguered by the sheriff of the county, but a party of horsemen sent by the barons came down and rescued him, and carried him off into Wales.

Finally, his lands and honours were restored, and he was again admitted to the king's council, ending his days in peace and honour.

May 30, 1891.

