---
title: "The Cook and the Captive, or Attalus the Hostage"
slug: "cook_and_captive"
format:
  html:
    toc: true
---


This story, so far as the captivity and escape of Attalus, and Leo's devotion to him are concerned, is literally true in very point, and stands on the authority of the noted contemporary, the historian of the time, St. Gregory, Bishop of Tours. It may be read in Thierry's*Récits des Temps Mérovingiens*, and in Madame Guizot de Witt's*Histoire de France en Chroniques*; or, more accessibly to English readers, the adventures are given in[*Golden Deeds*](golden_deeds.qmd).

In one respect I have ventured to vary. Both the French versions call Attalus*le neveu de Grégoire*; but as the Latin*nepos*stands both for a nephew and a grandson, and as the good Bishop had formerly been married, and Tetricus was his son, it seems most probable (as well as most convenient to the story-teller) that Attalus was his grandson.

The other characters are necessarily imaginary, but such wandering and eccentric Celtic pilgrims as Gilchrist were wonderfully numerous throughout the sixth and seventh centuries, and did much to prepare the way for more systematic missionary work. They were not often in full orders, but would be able to baptize. Roswitha, too, has many examples among the early Frank ladies.

The period is very little known, when Gaul had been divided between the various tribes of conquerors, Goths, Burgundians, and Franks. Most professed Christianity, but remained very savage and violent, the Franks especially so. The cities were, however, almost entirely Gallo-Roman, and within them all the Christianity, education, and civilisation of the Latins were still preserved.

A word or two further on the names. The Franks, or Sicambrians, as they were also called, had a harsh guttural sound, which can best be represented by h-Hlodwig (loud or famous war), Hildeberht (Battle maid bright), and the like. The Latin writers represented this by*c*or*ch*. Hence we get Clovis and Childebertus; and French, altering the Latin, gradually made Hlodwig first Ludwig or Ludovicus, and finally Louis; though in these days Clovis has been used as a Christian name. French historians talk of Childebert, Childeric, &c.; but I have thought it best to make them Hildebert, &c.; as nearest to the original, and therefore so used in more modern books.

The Frankish habits are gathered up to the best of my ability-where there is very little authority for them. The Burgundians, be it remembered, had a tolerable code of laws, and were the most civilised of the various tribes.

St. Rend, who baptized Clovis, died in the January of 533, and as Attalus's adventure is dated in 532, and his first shelter was Rheims, I ventured to bring them together.  


