---
title: "NA"
slug: "CORNELL links"
format:
  html:
    toc: true
---


http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fnora%2Fnora0080%2F&tif=00447.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABQ7578-0080-44

*[Miss Yonge's Novel](http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fnora%2Fnora0080%2F&tif=00447.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABQ7578-0080-44)s: pp. 439-459

Title: The North American review. / Volume 80, Issue 167 Publisher: University of Northern Iowa Publication Date: April 1855 City: Cedar Falls, Iowa, etc. Pages: 564 page images in vol.

ART. VII. —**The Heir of Redclyffe**. By the Author of” The Two Guardians,” “Henrietta’s Wish,” “The Kings of England,” etc., etc. Eighth Thousand. New York: P. H.  
Appleton & Co. 1854. 2 vols.  
**Heartsease: or the Brother’s Wife**. By the Author of “The Heir of Redelyffe.” New York: ID. Appleton & Co. 1855.  
2 vols.

*[The Church of England Novel, by Harriet Waters Preston](http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fatla%2Fatla0058%2F&tif=00789.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABK2934-0058-111): pp. 783-791

13 references to yonge in this article

http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fatla%2Fatla0058%2F&tif=00789.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABK2934-0058-111

Title: The Atlantic monthly. / Volume 58, Issue 350 Publisher: Atlantic Monthly Co. Publication Date: December 1886

*[Current Literature, by The Editor](http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fgala%2Fgala0021%2F&tif=00715.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DACB8727-0021-98)pp. 713-721

Title: The Galaxy. / Volume 21, Issue 5  

http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fgala%2Fgala0021%2F&tif=00715.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DACB8727-0021-98

*[Yonge's Life of Marie Antoinette](http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fnora%2Fnora0124%2F&tif=00519.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABQ7578-0124-72): pp. 501-504

Title: The North American review. / Volume 124, Issue 256  
Publisher: University of Northern Iowa Publication Date: May 1877  
City: Cedar Falls, Iowa, etc. Pages: 538 page images in vol.  
This entire journal issue: http://cdl.library.cornell.edu/cgi-bin/moa/moa-cgi?notisid=ABQ7578-0124&byte=98362197  

http://cdl.library.cornell.edu/cgi-bin/moa/pageviewer?frames=1&coll=moa&view=50&root=%2Fmoa%2Fnora%2Fnora0124%2F&tif=00519.TIF&cite=http%3A%2F%2Fcdl.library.cornell.edu%2Fcgi-bin%2Fmoa%2Fmoa-cgi%3Fnotisid%3DABQ7578-0124-72

