---
title: "Countess Kate"
sort_title: "Countess Kate"
year: 1862
gutenberg_url: "https://www.gutenberg.org/ebooks/3259"
slug: "countess_kate"
format:
  html:
    toc: true
---


### Contemporary Review from*The Athenaeum*

*Countess Kate*- by the Author of 'The Heir of Redclyffe'. (Mozley.)

Countess Kate is a little girl who at the opening of the story springs to the style and dignity of the Countess of Caergwent, from the humble position of plain Kate Umfraville, an orphan dependent for protection and education on her charitable uncle, Mr Wardour, who is the clergyman of St. James's, Oldburgh.

On her elevation to the peerage, Kate is taken from the country parsonage, and brought to London, where she is placed under the charge of two excessively decorous old-maid aunts, Ladies Barbara and Jane Umfraville, who live in Bruton Street, and by the aid of carriage, horses, butler, and lady's-maid, protect their delicate constitutions and patrician tastes from close intercourse with the vulgar.

The principal fun of the tale turns on the excruciating torture which these fastidious gentlewomen experience in witnessing and vainly endeavouring to correct the hoydenish manners and rustic style of the niece who, in a scarcely intelligible manner, has become the possessor of the family honours. Goaded into fury by Aunt Barbara's incessant reproofs and lectures, Countess Kate seizes an opportunity for escaping from the genteel captivity of Bruton Street, slips on bonnet and cloak, runs to the nearest cab, drives to a railway station, and makes good speed to her old friends at Oldburgh, where she is received with as much surprise as kindness. What more is told of little Kate's adventures we need not indicate.

The story will amuse children; and here and there it contains a scrap of good writing and pleasant reading, but on the whole it deserves more censure than praise. Readers will complain with reason, who buy 'Countess Kate,' trusting that it has some of the good qualities which won deserved popularity for 'The Heir of Redclyffe'.

