---
title: "The Cunning Woman's Grandson"
sort_title: "Cunning Woman's Grandson"
year: 1889
subtitle: "1889"
slug: "cunning_woman"
format:
  html:
    toc: true
---


### **Summary of**The Cunning Woman's Grandson****

(Kindly supplied by Amy de Gruchy)

**Publication**

1889, National Society. Price, Two Shillings.

Contents

The tale is set in the Cheddar district in the 1790s. At that time the inhabitants were ignorant, savage and superstitious. Inspired by the great William Wilberforce, the authoress Hannah More and her sisters attempted to reform them, teaching them Christianity and morality. C.M.Yonge's tale shows the effect of their efforts, particularly on the lives of two fictitious adolescents, Kitty Cole and Robin Lake. Robin lives in one of the caves with his grandmother, who deals in spells, potions and herbal healing, and also tells fortunes. She is respected and feared by the local community. Under the influence of the Mores Robin and Kitty eschew violence and other forms of bad behaviour and turn away from superstition.

After some years they become servants ill a respectable, pious household, and are instrumental in saving a young girl from a disastrous marriage which had been promoted by Robin's grandmother. The disappointed suitor and his gang attack Robin, but Kitty saves him. An angry crowd duck his grandmother, the cunning woman, as a witch, and though rescued, the shock causes her death, alone in her cave. Robin recovers from his injuries and in due course marries Kitty.

The characterisation is slight but adequate. Robin is intelligent and daring like his grandmother, but vague memories of his pious mother predisposes him to the teaching of the mores. Kitty is forthright and sensible, and so able to counter the superstitious folly and romanticism of Miss Lydia, who is shocked into reform. The cunning woman herself is a wholly unsympathetic figure, a plausible charlatan, proud of her duplicity, and harsh to the child in her care. The Mores, and some of the country folk, are background figures, though they influence events.

Local scenery and local customs are well described. The aim of the tale seems to have been to inform the readers about a little-known piece of religious and social history, and to warn them against the dangers of superstition, in particular the telling of fortunes. In this case the teaching is overt, but in general it is implied or shown through the action.

Further Reading

For contemporary reviews see  

**L. Madden**,*J.B. Shorthouse and C.M. Yonge*,  
Unpublished thesis  
University of London Diploma in Librarianship, 1964.

****

