---
title: "The Danvers Papers"
sort_title: "Danvers Papers"
year: 1867
subtitle: "1867"
slug: "danvers_papers"
format:
  html:
    toc: true
---


*1867*



### Publication details, summary and further reading

#### (Text kindly supplied by Amy de Gruchy)

#### Publication

1867, published by Macmillan

#### Contents

The story is of a seventeenth-century marriage as revealed in letters and other documents in the possession of Sir Bernard Danvers, a contemporary Irish baronet. He is visited by distant relatives from America and together they learn the causes of the separation of the two branches of their family.

These spring from the arranged marriage of Lady Penelope and Sir Thomas Danvers. At home he is a boorish Somerset baronet, in London a roistering Restoration gallant. She is plain, prim and pious. They are further divided by religion and politics. He is a High Churchman, and loyal follower of the Stuarts. She is a Puritan, and opposed to the Stuart kings.

However political events finally reconcile them. Her support for the Monmouth Rising endangers not only herself but her husband's tenantry. To save her and them he pays ruinous bribes and fines, and takes her to her Irish estate, where a few years later he is saved by her Irish tenants after the battle of the Boyne. By this time the couple have come to love and respect each other. He lays aside his wild habits and she, her self-righteousness. They leave their eldest son to inherit the Irish estate and make a new home for themselves in Virginia. It is the descendants of their younger children who visit Sir Bernard.

The seventeenth-century characters are well-drawn, but the contemporary figures are shadowy. The Danvers family history fits well into actual seventeenth-century events, although the fictitious dating for the family goes astray at times. There is a lively picture of life under the late Stuarts, and the imitation of the style of writing of the period is well maintained. The moral teaching is chiefly aimed at Lady Penelope, whose coldness and rigidity drive her husband further into vice.

#### Further Reading

For contemporary reviews see L. Madden,*J.B. Shorthouse and C.M. Yonge*, unpublished thesis, University of London Diploma in Librarianship, 1964.  

### Contemporary Review from*The Athenaeum*

*The Danvers Papers: an Invention*was reviewed in 1867 in*The Athenaeum*by Geraldine Endsor Jewsbury.  
Reference : 2072 (July 13,1867), 44

