---
title: "The Dove in the Eagle's Nest - Charlotte Mary Yonge"
year: 1866
slug: "dove"
format:
  html:
    toc: true
---


### Publication details, summary and further reading

Text kindly supplied by Amy de Gruchy,  
and prepared for the website by Esther McGilvray

Publication

1865 –1866 serialised in Macmillan's Magazine.  
1866 Published by Macmillan in 2 volumes

Contents

The novel is set in Germany towards the end of the 15th century, a period of change throughout Europe. In Germany the feudal system had broken down. The rise of the cities had led to a decline in the economic importance of the countryside. Power resided in the cities and in the hands of the great nobles. Successive emperors, unwilling to be mere figureheads like their predecessors, were attempting to impose their authority on their subjects. A noted figure was the Emperor Maximilian (ruled 1495 - 1516) who tried to unify and pacify the empire, but with limited success, as he wasted his great energy and abilities on too many other objects. However, efforts were being made to combat lawlessness and end the private warfare that had ravaged the countryside. At the same time the influence of the Church was being undermined by a perception of its great power, wealth and corruption.

The novel shoes in microcosm two of the major changes already mentioned, the shift of power from the countryside to the cities and the ending of violence and anarchy by the establishment of the rule of law. Yonge only hints at the approaching religious conflict in the main body of the work, though it is made explicit in the epilogue. She shows the effect the Emperor Maximilian had on his contemporaries by the way he affected the lives of her characters.

The title further illustrates the nature and progress of these changes. The heroine, Christina Sorel is the dove. She is taken from her uncle's peaceful cultured city home in Ulm to Adlerstein, that is, Eagle Rock, the castle of robber barons whose emblem is a white eagle. There the values in which she has been reared are gradually accepted and assimilated and her sons adopt as their emblem a dove brooding over two young eagles. C. M. Yonge had discussed with her publisher an alternative title The Debateable Ford (letter to Macmillan of 25th March 1865), but left the decision to him. In an earlier letter she had described the subject of the novel as "the burgher civilisation of the 15th century brought in contact with the savage robber nobility". (November 21st 1864) The Debateable Ford is claimed by the barons of Adlerstein and the counts of Schlangenwald who live on opposite sides of the river, for with it goes the right to all goods found in the water, which both lords interpret as the right to pillage passing travellers. The blood-feud between the two families, which has lasted for generations, is finally healed by the building of a toll bridge, the Friendly Bridge, by the ford, thus ending the rule of violence and giving the lords a legitimate method of increasing their revenues.

The settings underline the historical facts Yonge wishes to convey. The novel opens in the imperial (i.e. self-governing) city of Ulm, advantageously situated on the river Danube and on a busy trade route which passes through the mountains just south of the city to Switzerland. The city is prosperous and orderly, its inhabitants leading lives of comfort and even luxury. However, the action quickly moves to Adlerstein and its environs, south of the city in the mountains. The harsh climate and poor soil barely support the local population and they and their lords are sunk in poverty and brutal ignorance, but the lords are proud of their noble birth and admit no law but their own. The plot is straightforward, and is more concerned with Christina's sons than with herself. At 16 Christina is taken by her ne-er do-well father to tend the dying daughter of the baron of Adlerstein. She wins the love of the baron's only son and they marry, but secretly for fear of his parents who would never permit a marriage between a noble and a citizen. A few months later the baron, his son and their followers are attacked by the hereditary foe. Only one man returns to Adlerstein to tell the tale. He describes how all the rest were killed and how his young master, before he died, acknowledged his marriage to Christina and urged his mother to be good to her and the coming child. The old baroness spares Christina, for without a direct heir a rival branch of the family will inherit Adlerstein. The following spring the head of this branch, Sir Kasimir, indeed arrives, but is told that his kinsman's young widow has just borne twin sons, the elder of whom is the baron of Adlerstein. Sir Kasimir offers to be god-father to the babies, who are christened Eberhard and Friedmund (always called Ebbo and Friedel). Christina foils an attempt on Sir Kasimir's life by her mother-in-law, and he leaves the castle safely, and uses his influence at court to protect his godsons and their inheritance.

C. M. Yonge passes over the next 16 years in three short chapters. Christina is ill-treated by her mother-in-law, but is able to bring up her sons in her own values, though the grandmother has a little influence with Ebbo. The boys are devoted to their mother and to each other. After the death of the old baroness, Christina's uncle invites her and her sons to Ulm, so that Ebbo can swear allegiance to the Emperor, who is about to visit the city. Ebbo's unwillingness to lose his independence is overcome by his admiration and hero worship of Maximilian, the Emperor's heir, his contempt for burghers is somewhat lessened as he comes to respect his great uncle, but his jealous dislike of his godfather Sir Kasimir is increased when he realises that the latter wishes to marry Christina. Her uncle and aunt favour the match, but Christina is unwilling, partly on account of her sons' opposition but also because she wishes to be true to her long lost husband.

A family breach is just averted, and the trio return to Adlerstein where Christina's dowry (provided by her uncle) is used to make the castle more comfortable and to introduce agricultural improvements, though these are received reluctantly by the peasants.

The count of Schlangenwald now returns to his castle and begins to harass the peasants of Adlerstein, and then attacks a party of Ulm merchants at the ford. Ebbo and Friedel ride to the rescue and drive off the enemy. One of the merchant party, an architect, suggests a bridge could be built, a three way venture involving both nobles and the city of Ulm, the former supplying the land and the building materials while Ulm provided the workmen and technical skills. The count will have none of this and hints that Ebbo's father is still alive. From then on the twins have different aims. Friedel wishes to seek his father, while Ebbo is determined to build the bridge. After the work has started they are warned of an impending attack by the count. Christina counsels a prudent retreat and an appeal to Maximilian, but Ebbo is determined to fight.

Charlotte Yonge gives a stirring account of the battle, in which Ebbo is gravely and Friedel fatally wounded as is the wicked count. Before he dies Friedel makes him confess what he knows of his father's fate that he did not die, as was supposed by his follower, but recovered and was sold as a slave to the Turks. Ebbo slowly recovers from his wounds and is visited by the Emperor Maximilian, incognito, and soon after, by Sir Kasimir. Maximilian arranged a reconciliation between Ebbo and the one survivor of the Schlangenwald family, a military monk. On learning that Christina's husband is probably alive Sir Kasimir withdraws his suit, and Maximilian decides to send him on a distant mission. For fear that his late wife's cruel relations will claim his only child, a little girl of six and marry her to one of themselves for the sake of her fortune, Sir Kasimir asks Ebbo to wed her in the presence of the Emperor, thus ensuring her safety. The reconciliation and marriage ceremonies take place the following day which Maximilian rounds off by scaling a dangerous crag and killing a bear which is threatening the Adlerstein and Schlangenwald communities. He then departs, and unknown to Ebbo and Christina arranges for the finding and ransoming of Christina's husband. Months later the latter returns home and is received with joy by Christina. He is bewildered by the changes that have taken place and realises that Ebbo is better suited to the new duties of his position than he is. Ebbo accepts that he is no longer first in his mother's affection and is consoled by the devotion of his child wife.

The last chapter is an epilogue. It is 1531, the Adlerstein locality is as peaceful and prosperous as Ulm, and Ebbo's seven offspring are carefree and happy. Christina at 75 and Ebbo at 58, both long widowed, have resumed their close relationship and in a long discussion reveal to the reader the main events of the intervening years, Ebbo's views on the late Emperor Maxmilian, and his principled moderation in the current religious strife, which has earned him the hostility of both sides and the approval of his mother.

The theme of the novel is the overcoming of evil with good. Christina overcomes external evil by her own goodness. Ebbo has to overcome the evil within himself, his pride, hatred and jealousy. Minor characters also overcome evil with good. The Debateable Ford is replaced by the Friendly Bridge.

For the first third of the novel Christina is the centre of interest. Thereafter she is replaced by her elder son, to whom she acts as a kind of external conscience, as does her younger son. Christina as a young girl is shown as loving, modest and humble, her resolute principles overcoming her extreme timidity. She is deeply religious, intelligent and quick-witted. She becomes a loving wife and devoted mother, controlling her sons by her example and imbuing them with her own love of learning.

The twins are initially described as being identical in appearance and almost identical in character but Christina's dream of the two sparks one in the air like a star and one running through the grass better describes them. Friedel is spiritual, poetic, gentle and happy, an ideal figure. Ebbo is of the earth, a mixture of bad and good qualities. In their relationship with their mother, both love her deeply, but Ebbo at 16 expects to rule her as well as himself, while Friedel respects her wishes. When the twins are together, Ebbo decides Friedel advises. With social inferiors Ebbo is imperious, Friedel conciliatory. Ebbo is initially hostile to possible authority figures, Friedel accepts them. Ebbo, the chief character, is one of Charlotte Yonge's typical adolescents, and the tale illustrates how he learns to recognise and overcome his faults. In one of Yonge's contemporary novels these faults would have been severely censured but she realises that mediaeval Germany was not Victorian England and so Ebbo's failings are not taken very seriously and he is given credit for his good qualities.

Minor characters are well drawn as are their relationships with the major ones and each other. Maximilian is a convincing figure, and C. M. Yonge's judgment of him is the same as that of most historians.

C. M. Yonge shows a wide knowledge of the period, its political, social and cultural life. Her principle aim seems to have been to share this knowledge with the reader, by a mixture of illustration and direct authorial comment. Moral and religious teaching is unobtrusive, good practice being commended or shown to be effective rather than bad practice receiving strong criticism from the omniscient narrator.

Further Reading

For contemporary reviews see L. Madden,*J B Shorthouse and C. M. Yonge*unpublished thesis, University of London Diploma in Librarianship. 1964.

See also

Coleridge, Christabel.*Charlotte Mary Yonge. Her life and letters*. (London: Macmillan, 1903) pp. 225-226  
Battiscombe, Georgina.*Charlotte Mary Yonge. The story of an uneventful life*(London: Constable, 1943) pp. 130-133  
Romanes, Ethel.*Charlotte Mary Yonge. An appreciation*. (London and Oxford: Mowbray, 1908) pp. 104-108  
de Gruchy, Amy. "C. M. Yonge's Historical Novels - The Influence of Scott", 1837-1901 Journal of the Loughborough Victorian Studies Group No 5 pp. 39-40  
Fairfax Lucy, Alice. "The Other Miss Yonge",*A Chaplet for Charlotte Yonge*. (London: Cresset Press, 1965) pp. 93-94  
Mare, Margaret and Percival, Alicia C.*Victorian best-seller. The world of Charlotte M. Yonge*(London: Harrap, 1947) pp. 207-8  

Back to top of page

###   
  
  
Online text of**The Dove in the Eagle's Nest**

Click here to reach the latest version of**[*The Dove in the Eagle's Nest*](https://www.gutenberg.org/ebooks/3139)**from Gutenberg  
(Many thanks to Sandra Laythorpe her dedicated team)

Back to top of page

### The Dove in the Eagle's Nest

#### Chapter titles

Introduction  
Chapter I: Master Gottfried's Workshop  
Chapter II: The Eyrie  
Chapter III: The Flotsam and Jetsam of the Debateable Ford  
Chapter IV: Snow-Wreaths When 'Tis Thaw  
Chapter V: The Young Freiherr  
Chapter VI: The Blessed Friedmund's Wake  
Chapter VII: The Schneiderlein's Return  
Chapter VIII: Passing the Oubliette  
Chapter IX: The Eaglets  
Chapter X: The Eagle's Prey  
Chapter XI: The Choice in Life  
Chapter XII: Back to the Dovecote  
Chapter XIII: The Eaglets in the City  
Chapter XIV: The Double-Headed Eagle  
Chapter XV: The Rival Eyrie  
Chapter XVI: The Eagle and the Snake  
Chapter XVII: Bridging the Ford  
Chapter XVIII: Friedmund in the Clouds  
Chapter XIX: The Fight at the Ford  
Chapter XX: The Wounded Eagle  
Chapter XXI: Ritter Theurdank  
Chapter XXII: Peace  
Chapter XXIII: The Altar of Peace  
Chapter XXIV: Old Iron and New Steel  
Chapter XXV: The Star and the Spark

