---
title: "Dynevor Terrace - Charlotte Mary Yonge"
sort_title: "Dynevor Terrace - Charlotte Mary Yonge"
year: 1857
gutenberg_url: "https://www.gutenberg.org/ebooks/4235"
slug: "dynevor_terrace"
format:
  html:
    toc: true
---


*1857*


[Read free online at Project Gutenberg](https://www.gutenberg.org/ebooks/4235)

---


### [[Click for online text of volume I]](https://www.gutenberg.org/ebooks/4235)[[Click for online text of volume II]](https://www.gutenberg.org/ebooks/4236)

Click here to reach the latest version of[Dynevor Terrace Volume I](https://www.gutenberg.org/ebooks/4235)from Gutenberg  
(Many thanks to Sandra Laythorpe and others)

#### Dynevor Terrace–Publication details, summary and bibliography

(Kindly supplied by Amy de Gruchy)

Publication details

1857, Macmillan.

Contents

Dynevor Terrace may be described as an extended family chronicle. All the main characters and many of the minor characters are either descendants of the Dynevors, an ancient Welsh family, or closely connected with them. The line had ended with three daughters, who all married in the 1 790s. In 1847, when the novel opens, only the eldest sister is still alive. Catherine has had a chequered life. Born the heiress of Cheveleigh, the family seat, she had married a Mr Frost who speculated in mines. At first his ventures were successful, and he invested some of the proceeds in Dynevor Terrace, built for letting in the small spa town of Northworld, near the seat of the earl of Ormersfield, who had married Catherine's younger sister. The earl involved himself in Mr Frost's speculations, and at his suggestion demolished the village adjoining his park, to improve his view. The villages were compelled to spend move some miles away to Marksedge, a desolate piece of heath land, where they grew unhealthy, impoverished and lawless.

Mr Frost's speculations failed, he died and his widow had to sell her ancestral home. She made her home in Dynevor Terrace and set up a boy's school. Her two sons were of no help to her. Her younger son, Oliver, had vowed as a lad to get back Cheveleigh for her. He settled in Peru and was successful in the mining business, but obsessed with his dream of restoring his mother to her ancestral home, left her to bring up her two grandchildren, James and Clara, the orphans of her elder son, in poverty.

That the Ormersfield family were not similarly ruined was due to the probity and business sense of the heir, but they endured many years of rigid economy. Matters were made worse by the unfortunate marriage of this heir to a frivolous and extravagant society girl, who however died in giving birth to a son, Louis, the hero of the novel.

The third Dynevor sister also married, but died young leaving a daughter Mary, who was brought up at Ormersfield. Mary's marriage to Mr Ponsonby was as unfortunate as her cousin s. Mr Ponsonby was a rough man who neglected and was harsh to his wife. However, when he went to Peru she dutifully accompanied him leaving her daughter, another Mary, to the care of her husband's sister. When her education was complete Mary rejoined her parents in Peru.

In 1847 the Dynevor descendants are reunited at Ormersfield. Mrs Ponsonby's health has failed and she and Mary have returned to England. Catherine's nephew, now the Earl of Ormersfield, invites her and her grandchildren, Mrs and Mary Ponsonby to stay at his home. Catherine accepts gladly, but her grandson James Frost, who won a scholarship to Northwold Grammar School and is now a Fellow of an Oxford College, is unwilling, fearing that a long visit will unfit his younger sister Clara for life as a governess, and irritated by the Earl's admiration for himself and disapproval of his son, Louis. However, he agrees to come, and later Louis, a student at Oxford and Clara join the party.

The first part of the novel is mainly taken up with the escapades of Louis, and his concern for the villagers of Marksedge, and in particular his befriending an intelligent lad from there called Tom Madison. Louis has a serious accident (for which Tom is largely to blame) and this leads to reconciliation with his father, the earl. To please the latter, Louis proposes to Mary who, recognising his motive refuses him. Tom Madison's courtship of Charlotte Arnold, a pretty maidservant of Catherine, proceeds more favourably.

In the next section of the novel beautiful Isobel Conway appears, the step-daughter of Lady Conway, the elder sister of Louis's mother, and is chiefly concerned with the love entanglements of the four principal characters, Isabel herself, Mary, Louis and James. Mrs Ponsonby dies, Mr Ponsonby promptly marries a very young Peruvian girl, and summons Mary home, refusing to permit her engagement to Louis. James and Isobel marry on the strength of his headship of Northwold Grammar school, a post for which he is unsuited. Tom Madison joins the firm in Peru, and Charlotte, his betrothed, has to resist the blandishments of Lady Conway's butler.

Next Oliver returns and buys back Cheveleigh for his mother, and the repercussions of this are widely felt. Catherine soon dies, and Clara takes up responsibility for her uncle. James is estranged from them. In time he and Isobel and their growing family are plunged into poverty, and have the help of Charlotte Arnold. Louis and Mary, though parted remain loyal to each other. The wheel comes full circle, the firm in Peru faces ruin, Oliver has a stroke and has to sell Cheveleigh, and he and Clara find a home in Dynevor Terrace with James and Isobel. Louis comes to Peru and helped by Tom Madison salvages a part of Oliver's wealth, and since Mr Ponsonby has died, Louis and Mary can wed. They and Tom return to England where Tom marries Charlotte in a general celebration.

The theme of the novel is summed up in the sub-title, "The Clue of Life". The clue is to see the present life as a preparation for Heaven, which in practice means improving one's character and doing good to others. Louis has to overcome his volatility and desultoriness, James his pride, Isobel her tendency to live in a dream world, and to neglect her duties to her husband and children.

The characters are well drawn, and their relationships skilfully shown. These relationships develop. At the beginning of the novel Louis is immature, impulsive and careless, the despair of his orderly ambitious father, who hopes that an early marriage to sensible, down to earth Mary will steady him. Mary wisely refuses the guiding, controlling role that the earl has devised for her, but the pair learn from each other. Mary's example spurs Louis on to efforts at self improvement, while he awakens her latent imagination and intellectual powers. When they finally come together their roles are reversed, Louis has become the protector on whom Mary can lean. James and Isobel are taught by their circumstances rather than by each other. James' pride and temper lead to his humiliation, which teaches him humility. Their poverty forces Isobel into action, and an active enjoyment of her maternal role. The same circumstances bring out the latent strengths of Charlotte Arnold's character. Other minor figures are convincingly shown, in particular Clara Frost, "the giraffe".

The characters travel widely. While the main scenes of the action are at Ormersfield and Northwold, Paris during the 1848 revolution, Peru and Panama share their peregrinations and add interest to the narrative.

The moral and religious teaching is mediated through authorial comment, the reflections of the characters, and the action. Though the amount is considerable, it is not overwhelming.

Further Reading

For contemporary reviews see  

**L. Madden**,*J.B. Shorthouse and C.M. Yonge*,  
Unpublished thesis  
University of London Diploma in Librarianship, 1964.

**Christabel Coleridge**  
*Charlotte Mary Yonge. Her life and letters.*  
London: Macmillan, 1903  
pp. 197-8  

**Georgina Battiscombe**  
*Charlotte Mary Yonge*  
Constable, London 1943  
pp 75, 86, 117-118

****M. Mare and A. Perciva******l  
**Victorian Best seller  
G Harrap, London, 1947.  
*See index for numerous references and comments.*

