---
title: "Charlotte Mary Yonge - English Church History (1883)"
sort_title: "Charlotte Mary Yonge - English Church History (1883)"
year: 1883
slug: "english_church_history"
format:
  html:
    toc: true
---


*1883*



Online texts of***English Church History***

### [Click here to reach the online text of*English Church History*  
in various formats, including PDF](http://ia341318.us.archive.org/1/items/englishchurchhi00yonggoog/)

### [Click here to download a PDF file of*English Church History*](http://ia341318.us.archive.org/1/items/englishchurchhi00yonggoog/englishchurchhi00yonggoog.pdf)

#### Charlotte Yonge's own Preface toEnglish Church History

THE brief history here given is an attempt to make the growth of our Church, and of the Prayer Book; comprehensible to young minds. It is hoped that it may be found useful in the senior classes of Sunday and Saturday Schools, as well as to pupil teachers, and that it may help to establish in their minds the essential fact that our own is a branch of the One Catholic and Apostolic Church, built on the One Foundation. The continuity of the Church and the origin of the Prayer Book have therefore been made special subjects; and there has also been an endeavour to show the causes of whatever still comes under the eye of our young people. Some of the greatest difficulties of our time have been caused on the one hand by the loyal assumption that whatever is is right, and on the other by the belief that whatever is old must be better than the new, both parties being alike ignorant of the principle and cause of the customs which they attack or defend, and thus not knowing whether they are, or are not, important.

A knowledge of our own Church history would have some effect in lessening this inconvenience, and with this view these chapters have been drawn up. Some acquaintance with English history has been presumed in the readers, as they will probably be going through some school history which will enable them to understand who are the kings mentioned.

C; M. Yonge

September 23rd, 1882  

#### Chapter titles for English Church History  

I.

The British Church

II.

Conversion of Ireland and Scotland

III.

Our first Archbishop

IV.

The Conversion of Northumbria

V.

Theodore and Wilfred

VI.

Old English Saints

VII.

The Danish Ravages

VIII.

The Changes made by the Normans

IX.

Archbishop Anselm

X

Archbishop Becket

XI

The Interdict

XIII

The Secular and Regular Clergy

XIII.

Colleges

XIV

Wycliffe and the Lollards

XV.

Preparations for Change

XVI

The Separation from Rome

XVII

The Dissolution of the Monasteries

XVIII

King Edward’s First Prayer Book

XIX

King Edward’s Second Prayer Book

XX.

The Marian Persecution

XXI.

Remodelling

XXII

The Puritans

XXIII.

The Hampton Court Conferences

Archbishop Laud

XXV.

Discontents

XXVI

The Rebellion

XXVII.

The Persecution of the Church

XXVIII.

The Restoration

XXIX.

The Savoy Conferences

XXX

The Seven Bishops

XXXI

The Revolution

XXXII.

Silencing of Convocation

XXXIII.

John Wesley

XXXIV.

Evangelical Awakenings in the Church

XXXV.

The Church Awakening

XXXVI.

Revival of Convocation

