---
title: "NA"
slug: "fiamengo_bio"
format:
  html:
    toc: true
---


## Janice Fiamengo  
and  
The Victorian Review

Janice Fiamengo recently published the following article in the The Victorian Review:

*Forms of Suffering in Charlotte Yonge's The Clever Woman of the Family*  
Victorian Review, Volume 25, Number 2 (Winter 2000) pp. 80-105.

**Janice Fiamengo**  
Janice Fiamengo is Assistant Professor at the Department of English, University of Saskatchewan.

Follow these links for more about Professor Fiamengo's**interests in nineteenth-century literature**and**her publications**.

**The Victorian Review**  
The Victorian Review is the Journal of the Victorian Studies Association of Western Canada. It is an interdisciplinary journal promoting the study of all aspects of the nineteenth century. The Victorian Review publishes research articles encompassing a wide variety of topics and approaches and reviews of current books in all fields.

Follow this link for**more on the Victorian Review**

