---
title: "Founded on paper"
year: 1898
slug: "Founded on paper"
format:
  html:
    toc: true
---


### Online text of Founded on Paper

[Click here to access and download*Founded on Paper*from the Intenet Archive (opens in a new tab)](https://archive.org/details/foundedonpapero00yonggoog/page/n9/mode/2up)

***Text for this comment kindly provided by Ellen Jordan***

In Charlotte Yonge's*Founded on Paper*(1898) there is a ne'er-do-well young father, who, enraged because his wife has not only just had twins, but lost her job as well, gets drunk, rushes home, throws all the children down the well shouting "drown the kittens", and then shoots first his wife and then himself.

This was one of the books Yonge wrote with the specific audience of the "weary hardworked women" who belonged to Mothers' Unions in mind. In the 1880s she wrote, in an annotated list of books called*What Books to Lend and What to Give*, that "this class of woman must have incident, pathos and sentiment to attract them", and the books she wrote for this audience have plenty of fires, floods, and mad bulls, though the "incident" here is more horrific than most.

