---
title: "The Book of Golden Deeds"
sort_title: "Book of Golden Deeds"
year: 1864
subtitle: "1864"
gutenberg_url: "http://onlinebooks.library.upenn.edu/webbin/gutbook/lookup?num=6489"
slug: "golden_deeds"
format:
  html:
    toc: true
---


*1864*


[Read free online at Project Gutenberg](http://onlinebooks.library.upenn.edu/webbin/gutbook/lookup?num=6489)

---


**Online illustrated and plain texts**Chapter titles**Yonge's own Preface**  
**Yonge's historical sources**1865 reviewReal Men read Charlotte Yonge

Click here to reach an**[illustrated online version of*A Book of Golden Deeds*](http://digital.library.upenn.edu/women/yonge/deeds/deeds.html)**from the Celebration of Women Writers

This book has been put on-line as part of the**[BUILD-A-BOOK](http://digital.library.upenn.edu/women/instructions-2.html)**Initiative at the**[Celebration of Women Writers](http://digital.library.upenn.edu/women/writers.html)**through the combined work of: Alison Rogers and LaGloria Scott, Ann and Neil Piche, Brooks Taylor, Chris Alhambra, Jan Lawson, Jessie Hudgins, Joan Chovan, Judith Fetterolf, Judith Welch, Lori Summers, Patricia Heil, Sally Drake, Sue Farley, Sumi Lee, Velvet Van Bueren, and Mary Mark Ockerbloom.

For a plain text or simple-HTML version*of A Book of Golden Deeds*in a single file, with no pictures,[use the Gutenberg version](http://onlinebooks.library.upenn.edu/webbin/gutbook/lookup?num=6489).

**Cha****pter titles for*A Book of Golden Deeds***

### Charlotte Yonge's own Preface to*A Book of Golden Deeds*

As the most striking lines of poetry are the most hackneyed, because they have grown to be the common inheritance of all the world, so many of the most noble deeds that earth can show have become the best known, and enjoyed their full meed of fame. Therefore it may be feared that many of the events here detailed, or alluded to, may seem trite to those in search of novelty; but it is not for such that the collection has been made. It is rather intended as a treasury for young people, where they may find minuter particulars than their abridged histories usually afford of the soul-stirring deeds that give life and glory to the record of events; and where also other like actions, out of their ordinary course of reading, may be placed before them, in the trust that example may inspire the spirit of heroism and self-devotion. For surely it must be a wholesome contemplation to look on actions, the very essence of which is such entire absorption in others that self is forgotten; the object of which is not to win promotion, wealth, or success, but simple duty, mercy, and loving kindness. These are the actions wrought, "hoping for nothing again", but which most surely have their reward.

The authorities have not been given, as for the most part the narratives lie on the surface of history. For the description of the Colisæum, I have, however, been indebted to the Abbé Gerbet's*Rome Chrétienne*; for the Housewives of Löwenburg, and St. Stephen's Crown, to Freytag's*Sketches of German Life*; and for the story of George the Triller, to Mr. Mayhew's Germany. The Escape of Attalus is narrated (from Gregory of Tours) in Thierry's*Lettres sur l'Histoire de France*; the Russian officer's adventures, and those of Prascovia Lopouloff, the true Elisabeth of Siberia, are from M. le Maistre; the shipwrecks chiefly from Gilly's*Shipwrecks of the British Navy*; the*Jersey Powder Magazine*from the*Annual Register*, and that at Ciudad Rodrigo, from the traditions of the 52nd Regiment.

There is a cloud of doubt resting on a few of the tales, which it may be honest to mention, though they were far too beautiful not to tell. These are the details of the Gallic occupation of Rome, the Legend of St. Geneviève, the Letter of Gertrude von der Wart, the stories of the Keys of Calais, of the Dragon of Rhodes, and we fear we must add, both Nelson's plan of the Battle of the Nile, and likewise the exact form of the heroism of young Casabianca, of which no two accounts agree. But it was not possible to give up such stories as these, and the thread of truth there must be in them has developed into such a beautiful tissue, that even if unsubstantial when tested, it is surely delightful to contemplate.

Some stories have been passed over as too devoid of foundation, in especial that of young Henri, Duke of Nemours, who, at ten years old, was said to have been hung up with his little brother of eight in one of Louis XI's cages at Loches, with orders that two of the children's teeth should daily be pulled out and brought to the king. The elder child was said to have insisted on giving the whole supply of teeth, so as to save his brother; but though they were certainly imprisoned after their father's execution, they were released after Louis's death in a condition which disproves this atrocity.

The Indian mutiny might likewise have supplied glorious instances of Christian self-devotion, but want of materials has compelled us to stop short of recording those noble deeds by which delicate women and light-hearted young soldiers showed, that in the hour of need there was not wanting to them the highest and deepest "spirit of self-sacrifice."

At some risk of prolixity, enough of the surrounding events has in general been given to make the situation comprehensible, even without knowledge of the general history. This has been done in the hope that these extracts may serve as a mother's storehouse for reading aloud to her boys, or that they may be found useful forshort readings to the intelligent, though uneducated classes.

NOVEMBER 17, 1864.

### Charlotte Yonge's bibliography for*A Book of Golden Deeds*

*"The authorities have not been given, as for the most part the narratives lie on the surface of history"*

**Where did Yonge get the historical information for her novels?  
Here some details of the authors and works that Yonge alludes to in her Preface to*A Book of Golden Deeds***

**  
Olympe-Philippe Gerbet**(1798-1864) : French bishop and writer  
"*... for the description of the Colisæum**I have ...been indebted to the Abbé Gerbet's Rome Chrétienne ..."*

"Esquisse de Rome Chrétienne" various editions eg Paris 1843, 4me édition Paris, 1863.

Bookseller's description: Tome 2 seul : de la papauté considérée dans ses attributs et ses emblèmes, tradition de vérités : monuments primitifs de la foi, continuation du même sujet, monuments et usages particulièrement relatifs à la vie pieuse, monuments et institutions de charité, transformation de Rome paienne en Rome chrétienne, le Panthéon, temple de Jupiter Capitolin, Eglise d'Ara-Coeli, Palais des Césars, le Colysée; dissertation supplémentaire sur les Catacombes.

For an overview of Gerbet's life and works, see**[Gerbet's biography](http://www.newadvent.org/cathen/06470b.htm)**in the New Advent Catholic Encyclopedia.  
  

**Gustav Freytag**(1816 – 1895)  
*"*... Freytag's*Sketches of German Life*for the Housewives of Löwenburg, and St. Stephen's Crown ...*"*

Yonge is probably referring to Freytag's series*Bilder aus der deutschen Vergangenheit*, which seemed to have appeared in several volumes and editions over a period of years:

*1859 erscheinen seine kulturhistorischen Schriften: "Bilder aus der deutschen Vergangenheit" (2 Teile - 16. u. 17. Jh.)*  
*1862 erscheinen seine kulturhistorischen Schriften: "Neue Bilder aus dem Leben des deutschen Volkes" (18. u. 19. Jh.)*  
*1867 Die Neuauflage: "Bilder aus der deutschen Vergangenheit" in 5 Bänden erschienen.*

Those determined to learn more about Freytag's life, times and works should visit the extensive**[Gustav Freytag website](http://www.phil-fak.uni-duesseldorf.de/germ/germ4/freytag/gf.htm)**(in German).  

Weinsberg (Kreis Heilbronn, in Baden-Württemberg), where this golden deed took place, still describes itself today on its**[extensive municipal website](http://www.weinsberg.de/home/index.cfm)**as "Die Stadt der Trueun Weiber". For lots more on the background to Yonge's tale, search the internet for "Die Weiber von Weinsberg".

**Augustin****Thierry**(1795-1856)  
" ...Thierry's*Lettres sur l'Histoire de France*(1827) for the escape of Attalus (from Gregory of Tours) ... "  

The magnificent Gallica site has a**[facsimile edition of Thierry's*Lettres*](http://gallica.bnf.fr/scripts/ConsultationTout.exe?E=0&O=N029439)***  
*The story of the escape of Attalus (*Attale*) is in letter VIII on pp 136, 7, 8*  
*(use the*Pagination*feature to get to the page).

For more on Thierry himself, read this**[short biography of Augustin Thierry](http://www.bautz.de/bbkl/t/thierry_j_n_a.shtml)**(in German).  

And for a 14-page paper on**Thierry**'s work, try the*[**Historiographie du XIXe siècle**](http://bcs.fltr.ucl.ac.be/ENC4/12.html)**[: Augustin Thierry](http://bcs.fltr.ucl.ac.be/ENC4/12.html)***section of the Encyclopedie de l'histoire

**William O.S. Gilly  
**" ... the shipwrecks [come] chiefly from Gilly's*Shipwrecks of the British Navy ... "*

(The correct title seems to be*Narratives of shipwrecks of the Royal Navy: between 1793 and 1857*)*  
*by Gilly, W. O. S., 1864 Longmans, London, 332 pp.

alternatively:

*Narratives of shipwrecks of the Royal Navy [microform] : between 1793 and 1849*  
Compiled principally from official documents in the Admiralty by William O.S. Gilly ;  
with a preface by William Stephen Gilly.  
London : J.W. Parker, 1851.

**  
Annual Register**  
*" ... the Jersey Powder Magazine [is] from the Annual Register ... "  
*  
The Annual Register is a survey of the past year (traditionally focusing on history, politics, and literature) published annually in the UK since 1758. It has had various publishers; the latest is Longmans. On the title page of the first issue it describes itself as "**[The Annual Register, or a View of the History, Politicks and Literature of the Year 1758](http://www.bodley.ox.ac.uk/cgi-bin/ilej/image1.pl?item=page&seq=1&size=1&id=ar.1758.x.x.1.x.x.u1)**"

The Bodleian Library at Oxford has**[volumes 1-21 on-line as page images](http://www.bodley.ox.ac.uk/cgi-bin/ilej/pbrowse.pl?item=jnl)**(1758-1778): .

**  
****52nd (or Oxfordshire) Regiment of Foot  
***"... [the events at] at Ciudad Rodrigo from the traditions of the 52nd Regiment ..."  
*

Yonge is referring to**[The Siege of Ciudad Rodrigo: January 8-19, 1812](http://www.napoleonseries.org/articles/wars/ciudad.cfm)**, part of the Peninsular Campaign against Napoleon 1808-14.  
Her hero, Captain William Jones, was later killed at the storming of Badajoz on 6th April 1812.

For anyone researching this topic:

On a lighter note, academics, teachers, medics etc amongst us may be cheered to read**Wellington's letter of August 1812 to the Foreign Office**

**Joseph de Maistre**(1753-1821)  
*"... the Russian officer's adventures, and those of Prascovia Lopouloff, the true Elisabeth of Siberia, are from M. le Maistre ..."*

Count Joseph de Maistre was a major theorist of the Counter-Enlightenment whose writings stimulated such thinkers as Saint-Simon, Auguste Comte, and Charles Maurras, and inspired generations of French royalists and ultramontane Catholics. For more, visit Richard LeBrun's**[Maistre homepage](http://www.umanitoba.ca/faculties/arts/history/maistre.html)**.

Count Joseph de Maistre : St. Petersburg Dialogues. Translated by Richard A. Lebrun. Montreal: McGill-Queen's University Press 1993.

**Henry Mayhew**(1812-1887)  
*"... for the story of George the Triller, to Mr. Mayhew's Germany ..."*

**[Henry Mayhew](http://www.spartacus.schoolnet.co.uk/Jmayhew.htm)**was a writer, playwright, journalist and co-founder of Punch, perhaps best remembered for his classic work*[**London Labour and the London Poor**](http://etext.lib.virginia.edu/toc/modeng/public/MayLond.html)*(1851).

Yonge is here referring to Mayhew's 1864 publication:*German life and manners as seen in Saxony at the present day : with an account of village life--town life--fashionable life--married life--school and university life, &c., of Germany at the present time. Illustrated with Songs and Pictures of the Student Customs at the University of Jena.*

Georg(e) the Triller's golden deed is**[now commemorated by an obelisk](http://www.zugast.de/hotel-koehlerhuette/index.shtml)**inscribed "Hier wurde Prinz Albrecht, Ahnherr des kgl. Sächs. Fürstenhauses am 8. Juli 1455 durch den Köhler Schmidt, hernach Triller genannt, aus Kunzens von Kauffunge".

There is even a heroic depiction ofGeorg in action freeing Prince Albrecht

#### A BOOK OF GOLDEN DEEDS of all Times and all Lands

#### Gathered and Narrated  
by the Author of the "Heir of Redcliffe."

#### Literary Notices  
in  
The Ladies' Repository: a monthly periodical, devoted to literature, arts, and religion.  
Volume 25, Issue 6, June 1865, pp. 379-380

#### (Making of America Journal Articles)

This is a charming book, got up in excellent style, closely printed on tinted paper, and constituting a treasury of some of the noblest deeds of the world. "It is intended," says the author, "as a treasury for young people, where they may find minuter particulars than their abridged histories usually afford of the soul-stirring deeds that give life and glory to the record of events; and where also other like actions, out of their ordinary course of reading, may be placed before them, in the trust that example may inspire the spirit of heroism and self-devotion." This book is worthy of a place in every family, immeasurably preferable to much of the trash that finds its way into our households.

Real Men read Charlotte Yonge

#### Men at War: The Best War Stories of All Time  
Edited and with an Introduction by Ernest Hemingway

#### 1942

#### Charles Oman; Richard Hillary; Eric Jens Petersen; Jean De Joinville; Lloyd Lewis; Livy; R. Aldington;Charlotte Yonge; Marquis James; T E Lawrence; Alden Brooks; Nordhoff & Hall; Victor Hugo; William Faulkner; Winston Churchill; Etc N.Y.: Avon Double Size Books # G 1006, 1942

Hemingway's introduction states: "This book has been edited in order that...boys, as they grow to the age where they can appreciate it and use it and will need it, can have [a] book that will contain truth about war as near as we can come by it." As a result of careful selection and organization, this collection of war stories accomplishes what Hemingway set out to do. As a teacher, I've found these stories useful in class -- from Caesar's notes on his invasion of Britain and**Charlotte Yonge's "Pass to Thermopylae"**to Aldington's heartbreaking WWI story, "At All Costs." This collection contains the works of fine writers (Faulkner, Kipling, Forester, Crane, Kipling) and historical figures (Churchill,T. Roosevelt). As a parent, I am encouraging my adolescent son to read this book so that he will understand what others have done and what he may one day be called upon to do for his country. This book will one day be rediscovered and reprinted for a modern America once again engaged in a discussion of war and courage. In the meantime, join me in being grateful for these used copies which are available at (usually) reasonable prices.

