---
title: "Grisly Grisell - Charlotte Mary Yonge"
sort_title: "Grisly Grisell - Charlotte Mary Yonge"
year: 1893
slug: "grisly_grisell"
format:
  html:
    toc: true
---


*1893*



###   
**Online text of*******Grisly Grisell*****

### [[Click to see online copy of this book]](http://www2.cddc.vt.edu/gutenberg/etext05/grgr10.txt)

Click here to reach the latest version of**[Grisly Grisell](http://www2.cddc.vt.edu/gutenberg/etext05/grgr10.txt)**from Gutenberg  
(Many thanks to David Price)

***Grisly Grisell***– Publication details, summary and bibliography

(Kindly supplied by Amy de Gruchy)

Publication details

1893, Macmillan.

Contents

Grisly Grisell is an historical tale, set in the period of the Wars of the Roses. It ingeniously combines the plots of two mediaeval tales, Sir Gawaine and the Loathly Lady, and Patient Griselda.

As a child of ten the heroine Grisell Dacre is badly injured in an accident caused by her prospective husband, Leonard Copeland, a boy of thirteen. His family repudiate the contract, and the scarred child is cared for and trained by the nuns of Wilton. However, they are unable to keep her without a dowry, and she is returned to her parents whose home is a primitive castle on the Durham coast. There her appearance causes horror, but her goodness and care for others gradually wins trust.

At the outbreak of the war Grisell's father, a supporter of the Yorkist party, captures Leonard, whose family support the Lancaster side, and forces him to marry Grisell. He agrees on condition that he can go free and rejoin his king's army. In a later battle Grisell's father and brother are killed, and Leonard takes over the castle in right of his wife, sending in a troop of mercenaries. These decide that Grisell is a witch, but she escapes from them to the home of a Flemish apothecary in Sunderland. The tide of war turns again, Leonard is badly wounded, and the Fleming decides to return to his homeland, taking Grisell with him, and at her plea, for she loves her husband, Leonard also. Leonard recovers but does not realise that his kind nurse is his wife, for he has never seen her face since the accident, and has been told that she is dead. He takes service as a soldier in the Netherlands, but is largely supported by Grisell's lace making and medical skills. When her childhood friend Margaret of York becomes Duchess of Burgundy, Grisell sues for Leonard's pardon, and also for an end to their enforced marriage, so that he can wed another lady. Leonard, however, has already come to love Grisell, even before this example of her magnanimity, so they are happily reunited.

Characterisation is subordinated to the plot. Griselda as the loathly lady and rejected wife is consistently worthy, pious and loving. Leonard is the Sir Gawaine figure, loyalty to his king compelling him to a marriage he abhors. He is brave and chivalrous, quite unlike Griselda's cruel husband. The minor characters are one dimensional, though they perform adequately. Many are historical personages and their relationships and the political scene are set out at length. There are contrasting locations, the tranquil scenery of Wilton, the wild Durham countryside, the prosperous city of Bruges.

There is hardly any overt moralising. The authorial voice is chiefly used to convey information about the social conditions and the events of the period.

Further Reading

For contemporary reviews see  

**L. Madden**,*  
J.B. Shorthouse and C.M. Yonge*,  
Unpublished thesis  
University of London Diploma in Librarianship, 1964.

**Romanes, Ethel**  
*Charlotte Mary Yonge. An appreciation*  
(London and Oxford: Mowbray, 1908)  
page 182.

**Briggs, Katherine Mary**  
*Folklore in the Works of Charlotte Yonge*,  
(Occasional Papers of the K.B.Club, No. 1. Cambridge: Just Your Type, 1990)  
pages 11-12.

### **Review of***Grisly Grisell*****

Click here to read[a review of***Grisly Grisell***by Elizabeth Yank](http://www.love2learn.net/history/15centhf.htm#grislygrisell)  

### ****Grisly Grisell******on paper**

*Grisly Grisell*has been reprinted as an illustrated hardback by the Lepanto Press.  
It is part of their*[Knights and Ladies](http://www.olvs.org/whats_new.html)*series, which also includes editions of[*The Lances of Lynwood*](lances.qmd)and[*The Little Duke*](little_duke.qmd).

