---
title: "Hannah More by Charlotte Mary Yonge"
year: 1888
slug: "hannah_more"
format:
  html:
    toc: true
---


[Click here to download online versions of*Hannah More,*including PDFs](http://ia311205.us.archive.org/2/items/hannahmore00yonggoog/)  
**(digitized by Google from the library of Harvard University)**

Text and picture link from Wikipedia, the free encyclopedia.

Hannah More (February 2, 1745 - September 7, 1833) was an English religious writer and philanthropist.

[http://upload.wikimedia.org/wikipedia/commons/thumb/archive/8/8f/20081004023403%21Hannah_More.jpg/101px-Hannah_More.jpg](http://upload.wikimedia.org/wikipedia/commons/thumb/archive/8/8f/20081004023403%21Hannah_More.jpg/101px-Hannah_More.jpg)

Hannah More engraving after the painting by H.W. Pickersgill, A.R.A.  
in the National Portrait Gallery of Illustrious and Eminent Personages of the Nineteenth Century Vol 3 of 4,  
London: Fisher, Son, & Jackson, 1832

Hannah More was born at Stapleton, near Bristol, on the 2nd of February 1745. She may be said to have made three reputations in the course of her long life: first, as a clever verse-writer and witty talker in the circle of Johnson, Reynolds and Garrick; next, as a writer on moral and religious subjects on the Puritanic side; and lastly, as a practical philanthropist.

She was the youngest but one of the five daughters of Jacob More, who, though a member of a Presbyterian family in Norfolk, had become a member of the English Church and a strong Tory.

He taught a school at Stapleton in Gloucestershire. The elder sisters established a boarding-school at Bristol, and Hannah became one of their pupils when she was twelve years old. Her first literary efforts were pastoral plays, suitable for young ladies to act, the first being written in 1762 under the title of A Search after Happiness (2nd ed., 1773). Metastasio was one of her literary models; on his opera of Attilio Regulo she based a drama, The Inflexible Captive.

She gave up her share in the school in view of an engagement of marriage she had contracted with a Mr Turner. The wedding never took place, and, after much reluctance, Hannah More was induced to accept from Mr Turner an annuity which had been settled on her without her knowledge. This set her free for literary pursuits, and in 1772 or 1773 she went to London.

Some verses on Garrick's Lear led to an acquaintance with the actor-playwright; Miss More was taken up by Elizabeth Montague; and her unaffected enthusiasm,simplicity, vivacity, and wit won the hearts of the whole Johnson set, the lexicographer himself included, although he is said to have told her that she should consider what her flattery was worth before she choked him with it Garrick wrote the prologue and epilogue for her tragedy Percy, which was acted with great success at Covent Garden in December 1777.

Another drama, The Fatal Falsehood, produced in 1779 after Garrick's death, was less successful. The Garricks had induced her to live with them; and after Garrick's death she remained with his wife, first at Hampton Court, and then in the Adelphi. In 1781 she made the acquaintance of Horace Walpole, and corresponded with him from that time. At Bristol she discovered a poetess in Mrs Anne Yearsley (1756 - 1806), a milkwoman, and raised a considerable sum of money for her benefit. Lactilia, as Mrs Yearsley was called, wished to receive the capital, and made insinuations against Miss More, who desired to hold it in trust. The trust was handed over to a Bristol merchant and eventually to the poetess.

Hannah More published Sacred Dramas in 1782 and it rapidly ran through nineteen editions. These and the poems Bas-Bleu and Florio (1786) mark her gradual transition to mere serious views of life, which were fully expressed in prose, in her Thoughts on the Importance of the Manners of the Great to General Society (1788), and An Estimate of the Religion of the Fashionable World (1790). She was intimate with Wilberforce and Zachary_Macaulay, with whose evangelical views she was in entire sympathy. She published a poem on Slavery in 1788, and was for many years a friend of Beilby Porteus, Bishop of London and leading abolitionist.

In 1785 she bought a house, at Cowslip Green, near Wrington, near Bristol, where she settled down to country life with her sister Martha, and wrote many ethical books and tracts: Strictures on Female Education (1799), Hints towards forming the Character of a Young Princess (1805), Coeiebs in Search of a Wife (only nominally a story, 1809), Practical Piety (1811), Christian Morals (1813), Character of St Paul (1815), Moral Sketches (1819). The tone is uniformly animated; the writing fresh and vivacious; her favourite subjects the minor self-indulgences and infirmities. She was a rapid writer, and her work is consequently discursive and formless; but there was an originality and force in her way of putting commonplace sober sense and piety that fully accounts for, her extraordinary popularity.

The most famous of her books was Coelebs in Search of a Wife, which had an enormous circulation among pious people. Sydney Smith attacked it with violence in the Edinburgh Review for its general priggishness. It is interesting to note that the model Stanley children have been said to, be drawn from T. B. Macaulay and his sister. She also wrote many spirited rhymes and prose tales, the earliest of which was Village Politics, by Will Chip (1792), to counteract the doctrines of Tom Paine and the influence of the French Revolution.

The success of Village Politics induced her to begin the series of Cheap Repository Tracts, which were for three years produced by Hannah and her sisters at the rate of three a month. Perhaps the most famous of these is The Shepherd of Salisbury Alain, describing a family of phenomenal frugality and contentment. This was translated into several languages. Two million copies of these rapid and telling sketches were circulated, in one year, teaching the poor in rhetoric of most ingenious homeliness to rely upon the virtues of content, sobriety, humility, industry, reverence for the British Constitution, hatred of the French, trust in God and in the kindness of the gentry.

Perhaps the best proof of Hannah More's sterling worth was her indefatigable philanthropic work, her long-continued exertions to improve the condition of the children in the mining districts of the Mendip Hills near her home at Cowslip Green and Barley Wood.

The More sisters met with a good deal of opposition in their good works. The farmers thought that education, even to the limited extent of learning to read, would be fatal to agriculture, and the clergy, whose neglect she was making good, accused her of Methodist tendencies. In her old age, philanthropists from all parts made pilgrimages to see the bright and amiable old lady, and she retained all her faculties till within two years of her death, dying at Clifton, where the last five years of her life were spent, on the September 7, 1833.

Text and picture link from Wikipedia, the free encyclopedia

