---
title: "History of Christian Names"
sort_title: "History of Christian Names"
year: 1863, 1884
subtitle: "1863, 1884"
slug: "history_of_christian_names"
format:
  html:
    toc: true
---


*1863, 1884*



### Review**of*History of Christian Names***  
by Margaret Anderson

*Charlotte Yonge 1823-1901: nominal indexer*

The index to Charlotte Yonge's History of Christian Names (1863, revised 1884) is remarkable in several respects:

For the purposes of some readers, this index may obviate any need to turn to the text. But the text is worth reading. Although Miss Yonge's etymology has been shown by later philologists to be sometimes at fault, her book is still, 'the standard work on the subject in English' (E. G. Withycombe in the introduction to*The Oxford Dictionary of English Christian Names*).

*Her very wide knowledge of history is displayed in her discussion of the origins of names and of the rise and fall in their use in different places and periods, and also of the effects of the names of famous people on subsequent choice of names. She adduces the popularity at the time she was writing of the name Florence, in honour of Florence Nightingale.*

An example of the wealth of interest in the book is the surprising account of the prevalence of the name Hannibal among country people in Cornwall, shown in the parish registers beginning in the late 1500s. This name is thought to have been derived from contact with Phoenician traders who came to Cornwall long ago to buy tin. The index reference is: Hannibal, m. Eng. Phoen. grace of Baal, 40.

Another remarkable thing about Miss Yonge's long and learned book, and its index, undoubtedly compiled by herself, is that during the period when she must have been working on it, she produced several other, shorter books. That it was her custom to write at least two books at the same time is shown by the remark she is recorded to have made once at lunch: 'I have had a dreadful morning; I have killed the bishop and Felix.' The bishop was the missionary Coleridge Patterson, whose biography she was writing, and Felix was the leading character in one of her long, delightful novels of Victorian family life.

The remarkable index was the work of a remarkable author.

*Margaret Anderson, The Indexer, vol. 17, April 1991, page. 160.*  
  

#### Acknowledgements

CMYF also thanks Hazel Bell (Editor of The Indexer, 1978-1995) for pointing out this article and kindly providing a copy of the text.

*Hazel Bell has recently written an annotated anthology of extracts from and comments on indexes, published by the British Library jointly with the University of Toronto Press. It is called[Indexers and Indexes in Fact and Fiction Indexes: The Facts and the Fiction](http://www.utppublishing.com/detail.asp?TitleID=2420), (ISBN 080208494X).*

#### Chapter list forHistory of Christian Names

A modern bookseller writes:

*Yonge's comprehensive book is a positive feast of densely-packed information about Hebrew, Greek, Roman, Celtic, Slavic and German culture. There is much about Arthurian legend, Teutonic gods, Greek and Roman myth and viking heroes, and fascinating stories of names originating from animals, religious rituals, jewels, royality and much else.*

### Microfiche of***History of Christian Names***

Yonge's*History of Christian Names*is available on microfiche from**The Nineteenth Century**(this site gives you free access to an online catalogue of over 25,000 nineteenth-century works available on microfiche)

### Cuthbert Bede's contemporary critique  
of Yonge's*History of Christian Names*

The appearance of Charlotte Yonge's*History of Christian Names*stimulated a number of reviews or critiques pointing out omissions in her coverage. One of the most amusing of these is[*Christian Names*](http://www.bodley.ox.ac.uk/cgi-bin/ilej/image1.pl?item=page&seq=1&size=1&id=nq.1863.11.7.4.97.x.369)by Cuthbert Bede, which appeared in*Notes and Queries*in 1863.

Bede – whose real name was Edward Bradley– was the author of various comic novels and sketches, including*The Adventures of Mr. Verdant Green, An Oxford Freshman*and*Photographic Pleasures*. Among the names he attests are Sabrina, Christmas and Mareli; the last of these, used in a story of his own (see*The Curate of Cranston*), had in real life been given to a girl whose godmothers were Mary and Elizabeth. Yonge might well have compared her own Marilda (Mary Alda) Underwood, in**[*The Pillars of the House*](pillars_of_the_house.qmd)**.

Reference and online facsimile :  
[*Christian Names*](http://www.bodley.ox.ac.uk/cgi-bin/ilej/image1.pl?item=page&seq=1&size=1&id=nq.1863.11.7.4.97.x.369), by Cuthbert Bede  
Notes and Queries Vol. 4 3rd S. (97) Nov 7 1863 Page 369

### A more contemporary comment

"Yonge is no longer considered a trustworthy source. Her main strength is the breadth of languages she covered; for many of those languages (including French) she has been superceded by far more reliable works." (LoAR Sep 92, p. 6)

(LoAR**–**Letters of Acceptances and Returns. The Laurel letters are historical records of the SCA College of Arms.)

**1863 Review of History of Christian Names.**

**in*****English Woman's Journal*****Vol 12 Number 68**

**1 October 1863 pp 134-139**

.  
XXIII-NOTICES OF BOOKS  
.  
History of Christian Names. By the Author of " The Heir of Redclyffe."

2 vols., £1 10s. Parker and Son.

The title, "History of Christian Names" might lead to the supposition that the writer limited her work to modern times, and especially confined her attention to nations professing Christianity. So far from this being the case, if the title of the opening- chapter, " The Spirit of Nomenclature," had been given to the whole work, the design of the author would have been better expressed ; for this is an account of the original and proper names of men and women from the earliest times. We have books in plenty upon surnames. It is the peculiar province of every Dr. Dryasdust (and what county is without some of the fraternity), to hunt up the pedigree of local notorieties and thus discover a mine of materials upon which the College of Heralds may draw at pleasure, whenever a new-made millionaire desires a handle to his name. Far different is it^ when we pass from, mere local patronymics, to consider nomenclature in its spirit and universality. The subject has been hitherto so little considered, that the author can point to no work, wherein it has been treated with anything like completeness. A few lists, a few local derivations have appeared from time to time, but complete information could only be obtained by patient and industrious research. Yet comparative nomenclature is the student's best assistant in historical investigation, indeed, an all but infallible guide through the labyrinth of myth, legend, and tradition. And thus proper names, considered in their widest signification , become illustrations of language, religion, character, and fashion, and mementoes of the circumstances which have assisted their transmission from remote to modern times. In the preface, the author refers to the difficulties she encountered, and to the special objects she had in view.

" The changes through which the word passes is one of great interest, and for this I have been collecting for years, from dictionaries, books of travels, histories, and popular tales, whenever people were so good as to give the genuine word, instead of translating it into English. The history of names, however, seemed to have been but little examined, nor why one should be popular and another forgotten-why one should flourish throughout Europe, another in one country alone, another around some petty district. Some of these questions were answered by history, some by genealogy, many more by the tracing of patron saints, and their relics and legends. In each case I have tried to find out whence the name came, whether it had a patron, and whether the patron took it from the myths or heroes of his own country, or from the meaning of the words. I have then tried to classify the names, having found that to treat them merely alphabetically, utterly destroyed all their interest and connection. It has been a loose classification , first by language, then by meaning or spirit, but always with the endeavour to make them appear in their connection , and to bring out their interest." The author greatly assists her readers by the admirable manner in which she has arranged her subject. She classifies it under seven distinct heads : the Hebrew, Ancient Persian, Greek, Latin, Keltic, Teutonic, and Slavonic. These again are subdivided according" to national appropriation and association. No less than 125 pages axe taken up with a glossary of proper names, arranged alphabetically, with their meaning and derivation ; and reference is made to the page at which each several name is explained and illustrated. In the first volume, various classes of names are treated of, such as Patriarchal, Israelite, Persian, mythological ; names from animals, Greek and Latin Christian names. The second volume deals in names from the Keltic, Gaelic, Cymric, Teutonic, and Slavonic. Followed by descriptive names, closing with a curious chapter upon modern names.

As might be expected from Miss Yonge's known predilection for all that relates to romance, chivalry, and legend, the chapters on which she expends the greatest care, and illustrates with the happiest effect, are those relating to Keltic and Teutonic nomenclature. It must be "borne in mind that the Keltic splits into two great branches, the Cymric and the Gadhaelic. The former embraces the Ancient British, the Welsh, and their dependencies ; the latter, the Irish and the Scottish. Tennyson has so " raised the Table Bound again," and called the mythic Arthur back into substantial day, that all which relates to him and to his knightly companions, is deservedly popular. The chapter upon the Round Table contains much curious information, especially the account of how the legends connected with it were preserved. How the Norman trouvere listened to the wild chants of the Triads, and carried them to France and Brittany. There they lingered long, and were reproduced by Marie of Bretagne, and by our Geoffrey of Monmouth, though it remained for Mallory, who wrote in the fifteenth century, to preserve the main line of the allegory, which still remains the veritable prose epic of the Round Table. But the most convincing* argument for the real existence of this golden age of chivalry is found in the derivation of proper names ; for as Miss Yonge observes :- " Among the Bound Table names, there is not one that is Teutonic, except perhaps Lancelot, an error of translation and imitation ; all the rest are either genuine Cymric, or else such modifications of Latin nomina as citizenship was sure to leave to the Britons."

A few extracts respecting some of Tennyson 's heroines may not be uninteresting, particularly as showing that even to the derivation of a name he has been scrupulous in preserving unity in design. Enid is equivalent to Psyche, and it is singular that, except in Greece and Wales, the soul has nowhere been accepted in nomenclature. Enid, in the old romances, is never separated from Geraint, one of the three naval champions of Britain, and supposed to be her husband. " These are two of the characters whom Tennyson has recently rescued from unmerited oblivion, and raised to their true dignity among the chivalry of the Round Table. Their story was indeed to be found in the Mabinogion (a curious collection , of Welsh, legends, edited by lady Charlotte Guest), and Christian de Troyes had put them into French verse by the names of Erec and Enide ; but they had not been admitted into the general cycle of the romances, though a Triad mentioned Enide as one of the three celebrated ladies of Arthur's court. She is as beautiful a picture of wifely patience as Grisell herself, and does not go to such doubtful lengths of endurance. Her name is the Keltic form of animus, the soul ; and if Geraint ever meant, as David explains it, a ship or vessel, it would be tempting to see in the story an allegory of the scenes through which the soul is dragged by its mate, the ship that bears it." Still more curious is the derivation of Elayne, the mother of Sir Galahad, known to readers of the "' Idylls " as identical with the Lady of Shallotte Her name is traced back to classic times, to Helios (light), or the sun-god. It were impossible in our limited space to follow the author through all the variations of the name : suffice it to say that, after having been the designation of the fatal Trojan dame, it was borne by the mother of Cons tan tine, the St. Helena who found the true cross, and who was thenceforth revered throughout Christendom. "Eglwys Tlan, the Church of Helen, still exists in. Wales, and the Insular Kelts have always made great use of her name. And thus with light reflected from the saintly empress, Helena comes forth as the Lady Elayne of the Round Table."

It will surprise many to learn that the name of the wicked Vivian (lively) really comes from vita (life) , and was used by the early Christians to express their hopes of immortality. " Vivianus and Viviana were names of later Roman days, often , in the West, pronounced with a JB, and we find a Christian maiden, named Bibiana, put to death by a Roman governor, under Julian the Apostate, under pretence of her having destroyed one of his eyes by magic, a common excuse for persecution in the days of pretended toleration. A church was built over her remains as early as 465, and considering the accusation against her, it is curious to find Vyoyan or Viviana the enchantress of king Arthur's court. Some old romances made Vivian invite Merlin to a forest-dwelling, with sixty windows, and covered with hawthorn flowers ; but fancy soon turned this into the famous scene in which Vivian learns the lesson of magic from Merlin himself, and binds him for ever to the hawthorn in the forest of Broceliande, in Brittany." Guenever, or the White Lady, is identified with the ancient British goddess Gwen , or the moon.

Hardly less curious are the derivations of names which belong to the great Teutonic family, embracing, the larger part of modern Europe, and to which, as Anglo-Saxons and Normans, we are closely allied. Coming originally from the north , the Gothic races gradually dispossessed Rome of her conquests,. and were only stayed by the waters of the Mediterranean. Fierce as well as generous, hardy yet romantic, the Goths were not without their myths, and their scallds, and their singular religion affected their nomenclature. " The words whence names were compounded were usually the names of deities and those of animals, together with epithets or terms of offices generally conveying good auguries. They were usually connected with some great hero belonging to the various cycles of myth, in which the Teuton imagination revelled, and which, for the most part, under Christian influence, descended from the divine to the heroic, and then to fairy tale. "These Teutonic centres of legend may be considered as threefold. There is the great Scandinavian mythological system, as elaborate and poetical as that of the Greeks, and which belonged in part, at least, to the G-oths, Franks, and Saxons, though their early conversion gave it five hundred years less of development, and Louis le Debonnaire unfortunately destroyed the poetry that would have shown us what it had been among them.

"Next, there is the cycle of romance, represented in Scandinavia by the latter part of the elder Edda and by the Volsunga Saga, in Denmark by the Vilkina Saga, and in the centre of Europe by the Nibelungenlied, where old myths have become heroic tales that have hung themselves round the names of Attila the Hun, and Theodoric of Verone, who in Germany is the centre of a great number of ancient legends, once doubtless of deified ancestors.

  
" Thirdly, we have the grand poetical world, In which Charlemagne has been adopted as the sovereign, and Roland is the hero-the world of French Romance, Spanish ballad, and Italian poetry, which is to continental chivalry what the Round Table is to our own."  
Thus the whole family of Francis and Fanny is traced to Frey, the second deity in the Teutonic triad. The word Frey signifies joyous freedom. Thus-

Franja , or free, was the lord and master, so his wife was likewise frea , both the beloved and the free woman ; the northern freue , German frau, and Dutch vrowe, as donna had done in Italy, becoming the generic term for ¦woman."

As the gods grew human, Odin took to wife Frigga ; she gave her name to the moon, to the sixth day of the week, and, as Venus to the south? she became the goddess of love to the north. It is presumed she gave the name to Franklin, a freeman of small property, and so through a variety of imitations down to the present day.

The two ravens who sat on Odin's shoulders, and revealed to him all that passed in the world, were Huginn and Munninn, thought and memory. The first of these mythological creatures gives the name of Hugh, and Hugo. Hu Gadarn made it popular in Wales, and it is very frequently met with in Domesday Book. It is supposed to have named our Howards. It is pleasant to learn that Albert is a veritable national name ; it is a Teutonic word signifying nobly bright, and as Aethelbyrht was a favourite name among the Anglo Saxons. In like manner, Alexandra, though of Greek origin, and signifying helper of men^ "was popular throughout Europe at a very early period. Adopted in Scotland, it chiefly settled in Germany and Russia, and Is now likely to be much used in England Edward, literally, rich guard, is an heroic name of the Nibelung and from the earliest Saxon times popular in England. Victoria, on the contrary, is from the Latin, vinco, to conquer. " The original Victoria was a Roman virgin, martyred in the Decian persecution, whence the Italian Vittoria, borne by the admirable daughter of the Colonne, from whom France and Germany seem to have learnt it, since after her time, Victoria and Victorine became very common in France ; and it was from Germany that we learnt the Victoria that will, probably, sound hereafter like one of our most national names ; while many a city called Victoria in distant lands, will testify to the wide sweep of the rule of England in the ' Victorian age.'"

At the end of her work, Miss Yonge devotes several pages to modern nomenclature. The chapter having reference to Great Britain is full of interest. We learn that the appearance, disuse, or recurrence of certain proper names, gives data to our history, and marks conquest, alliance, or accidental circumstance. Taking up the subject at the Reformation, we fin d that the custom of using surnames as Christian names was then introduced. The Utopian school drew upon the heathen mythology, while the more pious, no longer permitted their patron saints, were fain to be content with the virtues, and Prudence, Temperance, &c, still linger in old Nonconformist families. Old Testament names were revived with the Puritans. Phyllis and Chloe, and other dwellers in Arcadian bowers, came in with the Restoration. The Augustan age approved an ornamental taste, witness the names found in the " Spectator. '9 The chivalrous school of Scott, and the simplicity upheld hj Wordsworth , were opposed to this stilted style, and it gradually died out , and beyond a few Almas, Navarinos, and such like, no particular fashion marks our present nomenclature. It may not be amiss to add, that Alma, or all good is a real old Erse name, and that probably the Crimean river was so named from these Keltic words. As specimens of odd names, the following will lose nothing by comparison :-

"Nonconformity leaves its mark in its virtue names and in its Scripture names, the latter sometimes of the wildest kind. Talithacumi was the daughter of a Baptist. A clergyman had been desired to christen a boy 4 Alas,' the parents supposing that 'Alas ! my brother,' was a call on the name of the disobedient prophet. There is a floating tradition of l Acts ' being chosen for a fifth son, whose elder brothers had been called after the four Evangelists. Among other proposed names may be mentioned 'Elibris,' which some people persisted belonged to their family, for "it was in their grandfather's books ; and so it was, being elibris (from the books) the old Latin manner of commencing an inscription , in a book. ' Valuable and serviceable ' is also said to have been intended for a child on the authority of an engraving in an old watch ; and an unfortunate pair of twins were presented for the imposition of Jupiter and Orion, because their parents thought them pretty names, and c had heard on them.' "  


