---
title: "Charlotte M Yonge Fellowship website - a focus for scholarly information on the life and works of the Victorian novelist and writer Charlotte Mary Yonge (1823–1901)"
slug: "home"
format:
  html:
    toc: true
---


###   
This website is a one-stop shop for information  
about Victorian best-selling author Charlotte Mary Yonge (1823–1901)

About this website

This website is a one-stop shop for information  
about Victorian best-selling author Charlotte Mary Yonge (1823–1901).

It includes material about:  
  
• her life, context, and correspondence  
• her books (over 250 titles, fiction and non-fiction) and journalism  
• the writers whom she influenced

Use the links in the left hand column of this website to access resources on Charlotte M. Yonge and her works. Whether you are a reader, a student or academic, or simply interested in the Victorian world, there will be something for you.

You will find publication details and plot summaries of Yonge’s many books. There are links to texts in all formats, as well as general and scholarly material, and contemporary and modern reviews. Over a hundred of her works are available free online from Project Gutenberg, Internet Archive, Google Books, and other libraries and agencies. You can read or download these directly from the list on our works page.

[This site is maintained by the Charlotte M. Yonge Fellowship.](http://www.charlottemyonge.org.uk/)

[Charlotte M Yonge Fellowship](http://www.charlottemyonge.org.uk/)

The Charlotte M. Yonge Fellowship welcomes everyone with an interest in the life and work of popular Victorian novelist Charlotte Yonge (1823-1901).

Charlotte M. Yonge's bicentenary in 2023 will be celebrated with events, activities and publications.

The CMYF holds regular meetings in the UK. It publishes a twice-yearly*Review*and the more scholarly*Journal*(both free to members); the*Journal*is also accessible on JSTOR. Its archive of Yonge and Yonge-related works is held at St Hugh’s College in Oxford University.

For fuller information about the Charlotte M. Yonge Fellowship's activities, and how to join, go to our sister website by clicking the link below:

**[charlottemyonge.org.uk](http://www.charlottemyonge.org.uk/)(opens in a new tab)**

About Charlotte Yonge

‘... the ideas that she promulgated through her books, through her personal influence and through her letters were actually major ideas for a key generation of Victorian women – the women born in the second half of the 1840's who went on to become the first generation of women head teachers, who founded the Girls’ High Schools, and who became the Principals of the new women’s colleges at various universities.’ (Julia Courtney, Open University)  
‘... Yonge addressed herself energetically for over half a century to precisely the issues with which convinced feminists were concerned ...’ (Charlotte Mitchell, co-editor of Yonge’s Letters)  
‘... one could say that this [Yonge’s Monthly Packet] was one of the first teenage magazines that was ever written ...’ (Amy de Gruchy, UCL)  
‘... she’s not a feminist, but she doesn’t say that being a woman lets you out of anything at all ...’ (Julia Courtney, Open University)  

Copyright (c) 2000-2022 The Charlotte Mary Yonge Fellowship  

Top of page[CMYF home page](index.qmd)

