---
title: "Hopes and Fears, or, Scenes from the Life of a Spinster"
sort_title: "Hopes and Fears, or, Scenes from the Life of a Spinster"
year: 1860
subtitle: "1860"
slug: "hopes_fears"
format:
  html:
    toc: true
---


*1860*



[Online text of : Hopes and fears; or, Scenes from the life of a spinster (Volume 1)](http://books.google.com/books?vid=05yKlHx0ByJXA-Uj&id=hLIBAAAAQAAJ&pg=PP7&dq=%22charlotte%2Bmary%2Byonge%22&as_brr=1)

[Online text of : Hopes and fears; or, Scenes from the life of a spinster (Volume 2)](http://books.google.com/books?vid=05EVQ0lhlvioD4Hn&id=n7IBAAAAQAAJ&pg=PP7&lpg=PA1&dq=%22charlotte%2Bmary%2Byonge%22&as_brr=1)

Google scans of the 1860 Parker and Son edition  
PDF file of both volumes available for download from the Google webpages.

#### Review ofHopes and Fearsin The Athenaeum, 1860  

*November 3, 1860, page 590-91*

#### The Hopes and Fears of a Spinster's Life  
By the Author of 'The Heir of Redclyffe.' (Parker and Sons.)

A new work by the Author of '***[The Heir of Redclyffe](heir_of_redclyffe.qmd)***,' is tolerably sure of a hearty welcome from a certain class of readers. It only remains for us to hope that Miss Yonge's admirers may not be disappointed with the volume now before us.

Without the help of genealogical tree, we are completely at a loss to understand the plot of the story, for we are carried through no less than four generations of one family, and are favoured with the history of all their relations, connexions and friends. Moreover, as in 'The Daisy Chain,' 'Dynevor Terrace,' &c., nearly every person mentioned in the book is known by a very unfair number of nicknames, which only makes confusion worse confounded. Miss Charlecote (the spinster who hopes and fears) is talked of indifferently as "Honora," "Honor," "Nora," "Honey," "Sweet Honey" and "Honey-pot"; while her adopted daughter figures sometimes as "Lucilla" and at others as "Lucy," "Cilla," "Cilly," &c., so that it really requires a clear head and a good memory to know precisely whom we are talking of.

Honora Charlecote appears to be an excellent but much-injured individual, who devotes herself to the care of the orphan children of her false lover, Owen Sandbrook, Though sparing neither trouble nor expense in their education, Miss Charlecote's kindness is requited with neglect, coldness, and even contempt. The pleasantest characters in the book are those of Phoebe Fulmert and her brother Robert -*alias*"Robin,"*alias*"The Redbreast." Though brought up in an irreligious and even vicious family, the children of the rich distiller become Honora Charlecote's greatest blessings - carefully picking up, and turning to the best account, the meagre crumbs of advice which are thrown aside, as worthless, by the conceited young Sandbrooks.

The moral of the story seems to prove (whether intentionally or not we cannot say) that if children are duly instructed in religious principles, and receive a careful education they will probably turn out good-for-nothing, worthless characters; but if sufficiently neglected, or even intrusted to the tender mercies of an Unitarian governess, with the addition of a studious example at home, there is every hope that they may ultimately become praiseworthy and valuable members of society, even, perhaps, zealous, hard-working High-Church clergymen.

This book is apparently written for the edification of very young ladies; but upon what principle they are to be initiated into the art of talking slang we cannot imagine. To be repeatedly told that Cilly Sandbrook "in her wildest moments, is always thoroughly lady-like" might lead some unsophisticated young woman to suppose that all real ladies are in the habit of making use of such expressions as the following: - "I can't resist the charm of*hooking*a Marshal or a Prince or two." "Rashe's sprain was*a great sell*, but we had capital fun notwithstanding." When expecting a visit from a young curate, this ultra-refined young person wonders if she "shall have time to change this spoony simplicity, and come out in something spicey, with a dash of the Bloomer." She thinks she is a little "like the Christian religion, for which people are always making apologies which it does not want;" and she considers that "four and twenty is quite old enough to bite off one's wings and found an ant-hill." Now if Lucy Sandbrook were represented as a frightfully vulgar, detestable woman, whose example could not be too much avoided, it might be very well to repeat all the coarse and unseemly expressions of which she is so lavish; but when Cilly is given to us not only as a specimen of all that is fascinating, engaging and irresistible, but even as a type of a class, we think we have a right to remonstrate

### Review of*Hopes and Fears*in The North American review, 1861  
Available online from Cornell University

*Hopes and Fears*: pp. 560-561

Title: The North American review. / Volume 92, Issue 191  
Publisher: University of Northern Iowa Publication Date: April 1861

