---
title: "Charlotte Mary Yonge - The Instructive Picture Book"
year: 1857
slug: "instructive_picture_book"
format:
  html:
    toc: true
---


THE INSTRUCTIVE PICTURE BOOK  
or Lessons from the Vegetable World

***not to be confused with the similar title by Adam White which was also published by Edmonston and Douglas***

By the Author of 'The Heir of Redclyffe' Etc.

Edinburgh: Edmoston and Douglas

Size 8.5 x 13 ins. 22 pages .

31 hand coloured double page plates

**Plates:**

Tabular view of vegetable kingdom (1)  
Spring / summer / autumn / winter flowers (4)  
Kitchen vegetables and roots (3)  
Plants useful in domestic economy, the arts etc (3)  
Forage or field plants (1)  
Grains (2)  
Poisonous plants (11)  
British Fungi (1)  
Fruits (5)

See the prints

The plates from this book are currently (2005) offered for sale by Fine Rare Prints.

See them here::

[http://www.finerareprints.com/vol_botanical_ipb_1.html](http://www.finerareprints.com/vol_botanical_ipb_1.html)

(Click on any image to see enlarged view**)**

THE INSTRUCTIVE PICTURE BOOK. OR LESSONS FROM THE VEGETABLE WORLD.  
BY THE AUTHOR OF "THE HEIR OF REDCLYFFE"

Edmonston & Douglas, Edinburgh, 1857.

Large octavo, 22 pages + plates, original blue papered boards with hand-coloured engraving at centre front, adverts at each pastedown and yellow free endpapers, 31 engraved double-page plates with hand-colouring, arranged by Robert M.(=Mackenzie) Stark 1815-1873.

Robert M. Stark was a fellow of the Botanical and Royal Physical Societies.

