---
title: "Kenneth; or, The Rear Guard of the Grand Army(1850) by Charlotte Mary Yonge"
sort_title: "Kenneth; or, The Rear Guard of the Grand Army(1850) by Charlotte Mary Yonge"
year: 1850
slug: "kenneth"
format:
  html:
    toc: true
---


*1850*



###   
[Click here for an online text of :*Kenneth, Or, The Rear-guard of the Grand Army*from the Internet Archive](https://archive.org/details/kennethorreargu00yonggoog/page/n10/mode/2up)

A scan of a copy of*Kenneth*published as Volume 1 in the Tauchnitz "Series for the Young" Leipzig 1860.  

Bookplate "Francis Weld Peabody His Book" and a Harvard College Library label. Later, under a Harvard stamp of June 2 1937, the following handwritten "From the library of Francis W Peabody"

#### The Stones of Plouhinec

#### From of[The Lilac Fairy Book](https://archive.org/details/lilacfairybook00lang/page/236/mode/2up)by Andrew Lang

Perhaps some of you may have read a book called 'Kenneth; or the Rear-Guard of the Grand Army' of Napoleon. If so, you will remember how the two Scotch children found in Russia were taken care of by the French soldiers and prevented as far as possible from suffering from the horrors of the terrible Retreat. One of the soldiers, a Breton, often tried to make them forget how cold and hungry they were by telling them tales of his native country, Brittany, which is full of wonderful things. The best and warmest place round the camp fire was always given to the children, but even so the bitter frost would cause them to shiver. It was then that the Breton would begin: 'Plouhinec is a small town near Hennebonne by the sea,' and would continue until Kenneth or Effie would interrupt him with an eager question. Then he forgot how his mother had told him the tale, and was obliged to begin all over again, so the story lasted a long while, and by the time it was ended the children were ready to be rolled up in what ever coverings could be found, and go to sleep. It is this story that I am going to tell to you ...

**For the rest of*****The Stones of Plouhinec*****, follow the link above to*****The Lilac Fairy Book***

