---
title: "Landmarks of History, Part III: Modern History"
sort_title: "Landmarks of History, Part III: Modern History"
year: 1857
subtitle: "1857"
slug: "landmarks_of_history_modern"
format:
  html:
    toc: true
---


*1857*



A Google scan of an 1857 edition at Bodley is currently (August 2007) available on Google. A PDF version is also available for download from the Google webpage.

[Click here to see the text](http://books.google.com/books?id=OoUBAAAAQAAJ&printsec=titlepage&dq=%22Charlotte%2Bmary%2Byonge%22&as_brr=1)

#### Charlotte Yonge's own Preface toLandmarks of HistoryIII, Modern History

THE Landmarks of History have now been brought down as nearly to our own times as could be accomplished without entering too much on contemporary history. Napoleon's death appears the fit close for the last act of the great drama of the Revolution; and the scenes which fall within our own memory and observation, have not yet developed their import, so as to enable us to judge of their true meaning and tendency. In closing the task, perhaps too rashly undertaken, we have only to repeat, what has been before said, that this little book aims at no originality of views, nor at revelations of new facts. It is a mere compilation of the more memorable events recorded in standard histories; and all that it attempts is, so to class them together as to elucidate the spirit of each period, and bring into relief the characters of the chief actors, in the hope of letting history fulfil its true purpose, namely, of being a great lesson in principle, rather than a mere record of dates, names, and events.

October 14th, 1857

CHAPTER I.  
PERIOD OF THE REFORMATION.

i. The Papacy  
ii. The Modifications of the Feudal System  
iii. Sovereigns of Europe  
iv. The Sclavonian Nations  
v. Mexico and Peru  
vi. Martin Luther  
vii. Imperial Conquest of Italy  
viii. The Confession of Augsburg  
ix. Wars with the Turks  
x. Treaties with France  
xi. The Jesuits  
xii. The League of Schmalkalde  
xiii. Abdication of Charles V  

CHAPTER II.  
PERIOD OF WARS OF RELIGION.

i. The Peace of Cateau Cambresis  
ii. The Council of Trent  
iii. Malta and Lepanto  
iv. François de Guise  
v. Tyranny in the Netherlands  
vi. Annexation of Portugal  
vii. The Seven United Provinces  
viii. Massacre of St. Bartholomew  
ix. The League  
x. The Spanish Armada.  
xi. Pacification  

CHAPTER III.  
PERIOD OF THE THIRTY YEARS WAR

i. The Counter Reformation  
ii. Europe in Sixteen Hundred  
iii. The Fraternal Contest  
iv. The Cardinal de Richelleu  
v. The Winter King  
vi. Wallenstein  
vii. Gustavus Adolphus  
viii. French Intervention  
ix. The Revolution of Portugal  
x. Decay of Spanish Power  
xi. Peace of Westphalia  

CHAPTER IV.  
REIGN OF LOUIS XIV.

i. La Fronde  
ii. The Jansenists  
iii. Christina of Sweden  
iv. Peace of the Pyrennees  
v. Court of Louis XIV  
vi. Invasion of Holland  
vii.The Treaty of Nimeguen  
viii. The Siege of Vienna  
ix. Revocation of the Edict of Nantes  
x. Decline of the Turks  
xi. The War of the Palatinate  
xii. Quietism  
xiii. War of the Spanish Succession  
xiv. Eugene and Marlborough  
xv. The Peace of Utrecht  
xvi. Peter and Charles  
xvii. Charles  
xviii. Swedish Invasion of Russia  
xix. Charles XII. in Turkey  

CHAPTER V.  
THE AGE OF PHILOSOPHY.

i. Decay of Europe  
ii. Latter Years of Peter the Great  
iii. The Quadruple Alliance  
iv. Austrian and Spanish Intrigues  
v. War of the Austrian Succession  
vi. The Rebuke of Kings  
vii. The Seven Years War  
viii. Suppression of the Jesuits  
ix. Partitlon of Poland  
x. Philosophy on the Throne

CHAPTER VI  
THE ERA OF REVOLUTION.  


