---
title: "Langley Little Ones"
sort_title: "Langley Little Ones"
year: 1882
slug: "langley_little_ones - 6 stories"
format:
  html:
    toc: true
---


*1882*



#### [Click here for online text ofLangley Little Onesin the Internet Archive](https://archive.org/details/langleylittleon00yonggoog/page/n6/mode/2up)

**Preface and contents list for*Langley Little One***

It is sometimes said that stories of this description are of far more use to the teachers than to the taught.

It may be so. Long ago the well-known "Langley School" taught hundreds of young ladies to care for village school-children, and what sort of training to give them. If this little attempt can show to any, at a time when change and difficulty make many feel great discouragement, how the same happy relations and the same mutual affection can exist amidst the much more elaborate conditions of a modern town-school, it will, through them, at any rate, benefit their scholars.

**CONTENTS**  
  
1. QUACK, QUACK.  
2. BULLY BRINDLE.  
3. SNOWDROP'S EGGS.  
4. FANNY'S DOLL.  
5. A MILLER, A MOLLAR,  
A TEN-O'CLOCK SCHOLAR.  
6. THE THIRD STANDARD.

