---
title: "The Little Duke - Charlotte Mary Yonge"
year: 1854
slug: "little_duke"
format:
  html:
    toc: true
---


"On a bright autumn day, as long ago as the year 943, there was a great bustle in the Castle of Bayeux in Normandy ... "

*Little Duke***online*****Little Duke*republished**

Summary and publication detailsMark Twain and The Little Duke

### **Online text of*The Little Duke***

[Click here to reach the latest version of*The Little Duke*from Gutenberg](http://digital.library.upenn.edu/webbin/gutbook/lookup?num=3048)  
(Many thanks to Sandra Laythorpe and others)

### ***The Little Duke***on paper

[Jane Nissen Books](http://www.janenissenbooks.co.uk/)republished*The Little Duke*in paperback (2001). The book, in good clear print and with copies of the original illustrations, has a brief introduction by****Beverley Naidoo

Back to top of page

### **Publication details, summary and further reading for*The Little Duke***

(Text kindly supplied by Amy de Gruchy)

#### Publication

#### Contents

The Little Duke, the first of C.M. Yonge's historical tales for children, appeared as a serial in her magazine**[The Monthly Packet](monthly_packet.qmd)**in 1851. In 1854 a longer version on good paper, attractively illustrated and priced five shillings was brought out by Parker and Sons who had published Yonge's first best-seller,[The Heir of Redclyffe](heir_of_redclyffe.qmd), the previous year.

The main character is Richard Duke of Normandy, the great grandfather of William the Conqueror. At the beginning of the tale he is a boy of eight, who succeeds to the dukedom when his father is murdered in 943 A.D. His overlord King Louis carries the boy off to the French court. There his life seems to be in danger, and he is rescued by his faithful squire and returns to Normandy. There the serial ends, but the book continues with an account of the subsequent struggle between the Normans and French. It concludes with a summary of Richard's life, stressing his magnanimity.

The child Richard is an extremely well-drawn character, a recognisable small boy albeit one shaped by his particular heredity and environment. The author never allows him to be wiser and more perceptive than is natural for his age, and in matters beyond his comprehension intervenes as the omniscient narrator. The minor characters are seen through his eyes in general, and with the exception og King Louis, have only one or two traits apiece, but are consistent , all that would be required by child readers.

C.M. Yonge's aim seems to have been to convey moral as well as historical instruction. The first part concentrates on Richard's failings, their punishment and his reform, the second part on his virtues. She also wished to acquaint readers with the characters and events of a little known period of history. Her historical detail is meticulous, but her account of events is biased in favour of the Normans.

The book went through many editions before 1900 and was to be found in school libraries until the middle of the twentieth century. It is nowonce again in print.

#### Further Reading

******For contemporary reviews:******

L. Madden,*J.B. Shorthouse and C.M. Yonge*, unpublished thesis, University of London Diploma in Librarianship, 1964.

***For Charlotte Yonge's historical fiction:***

Alice Fairfax Lucy, 'The other Miss Yonge', in*A Chaplet for Charlotte Yonge*.  
Edited for The Charlotte Yonge Society by Georgina Battiscombe and Marghanita Laski. The Cresset Press, London 1965

L.A. de Gruchy, 'C.M. Yonge's historical novels - the influence of Scott', 1837-1901:  
*Journal of the Loughborough Victorian Studies Group*, no. 5, October 1980, pp. 30-49.

L.A. de Gruchy,*The Monthly Packet*, unpublished thesis, University of London, 1986, p. 153 et seq.  

*Back to top of page*

#### Mark Twain and The Little Duke

The following is extracted from Volume VI of Mark Twain's Letters 1907-1910  
(Samuel Clemens)

To Rev. F. Y. Christ, in New York:

REDDING, CONN., Aug., '08.

....

Yesterday a guest said, "How did you come to think of writing 'The Prince and the Pauper?' I didn't. The thought came to me from the outside — suggested by that pleasant and picturesque little history-book, Charlotte M. Yonge's "Little Duke," I doubt if Mrs. Burnett knows whence came to her the suggestion to write "Little Lord Fauntleroy," but I know; it came to her from reading "The Prince and the Pauper." In all my life I have never originated an idea, and neither has she, nor anybody else.

....

Your friend and well-wisher  
S. L. CLEMENS.

[This volume of Mark Twain's Letters is available on line from Gutenberg](http://www.ibiblio.org/gutenberg/etext02/mt6lt10.txt)

