---
title: "Magnum Bonum, or, Mother Carey's Brood"
sort_title: "Magnum Bonum, or, Mother Carey's Brood"
year: 1879
gutenberg_url: "https://www.gutenberg.org/ebooks/5080"
slug: "magnum_bonum"
format:
  html:
    toc: true
---


*1879*


[Read free online at Project Gutenberg](https://www.gutenberg.org/ebooks/5080)

---


[Click here for the latest version of*Magnum Bonum*online from Gutenberg](https://www.gutenberg.org/ebooks/5080)  

[Click here for the latest version of*Magnum Bonum*online from the Internet Archive](https://archive.org/details/magnumbonumormo00yonggoog/page/n5/mode/2up)  

#### Talia Schaffer: “The MysteriousMagnum Bonum: Fighting to Read Charlotte Yonge”

This paper appeared in Nineteenth-Century Literature Volume 55 ·Issue 2 · September 2000

#### Abstract

(The full text is available in the on-line jounal, but only to subscribers)

This essay argues that Charlotte Yonge has presented a particular challenge to critics because she depicts rebellious youths only to subsume them within an overriding (and unpalatable) ideological nexus. She encourages readers to identify with these dissident characters in order to share their inevitable conversions to a Yongian worldview. A close examination of Magnum Bonum; or, Mother Carey’s Brood (1879) reveals the mechanisms by which Yonge manipulates her readers. This novel centers on a mysterious legacy, a medical discovery named the “Magnum Bonum,” left by a dying father to his most deserving son. Magnum Bonum exerts a normalizing force on the younger generation, suppressing daughter Janet ’s lesbian desires and feminist activism, and disciplining son Jock’s iconoclastic and anticapitalist performances. The only person empowered by the Magnum Bonum is Mother Carey, who becomes its guardian, exalts it into a near-religious icon, and finally acquires a voice of her own through being ventriloquized by her dead husband ’s wishes. Through the Magnum Bonum, the patriarch’s disembodied, omnipotent authority transforms his unruly offspring into docile (if suicidal)replicas of himself. Magnum Bonum reveals that the mixture of realist observation and pious oppression in Yonge’s novels is a sophisticated literary strategy and suggests that monitoring this technique might be the most useful way into Yonge’s fiction.

Talia Schaffer, Assistant Professor of English at Queens College, City University of New York, is the author of*The Forgotten Female Aesthetes: Literary Culture in Late-Victorian England*(2000) and coeditor, with Kathy Alexis Psomiades,of*Women and British Aestheticism*(1999). She is now at work on a book-length study that analyzes domestic handicrafts as a paradigm for the novel, with chapters on Yonge, Gaskell, Oliphant, and George Eliot, tentatively titled “*The Craft, the Commodity, and the Collectible: Domestic Art and the Victorian Popular Novel*.”

