---
title: "Charlotte Mary Yonge - Major Library Holdings"
slug: "major_holdings"
format:
  html:
    toc: true
---


This page contains links to libraries with well-described holdings of Yonge books which may interest Yonge readers.

We cannot provide a general means of searching library catalogues here: you can usually do this from academic and other major libraries.

#### Parrish Collection, Princeton

#### Charlotte Yonge material held in[  
The Morris L. Parrish Collection of Victorian Novelists](home.html#)

The Morris L. Parrish Collection of Victorian Novelists consists of the library of books, manuscripts, photographs, artwork and ephemera collected by Morris Longstreth Parrish. This collection came to Princeton University in 1944 as a bequest.

Mr. Parrish formed the beginnings of a collection of the voluminous Charlotte M. Yonge – nineteen of her**books**, including her two most famous works,*The Heir of Redclyffe*and*The Dove in the Eagle’s Nest*. The library has since added more, and the book collection now stands at twenty-eight.

The collection also contains 178**letters**in Charlotte's own hand and a small number of letters addressed to her. It includes the**manuscripts**of five of her stories,*The Carbonels*(1895),*The Constable’s Tower*(1891),*The Cock and the Captive*(1894),*The Cross Roads*(1892), and*The Wardship of Steepcoombe*(1896), as well as parts of the manuscripts of six other books.

An excellent[online finding aid to the entire Parrish collection of manuscripts](home.html#)is available online.

