---
title: "The Making of a Missionary, or, Daydreams in Earnest"
sort_title: "Making of a Missionary, or, Daydreams in Earnest"
year: 1890
subtitle: "1890"
slug: "making of a missionary"
format:
  html:
    toc: true
---


*1890*



[Click here to reach the latest version of Life of John Coleridge Patteson from Prkect Canterbury](http://anglicanhistory.org/asia/china/yonge1900/)

### [1st Biennial TransTasman Conference on Australians and New Zealanders  
in Christian Missions, at Home and Abroad](http://rspas.anu.edu.au/pah/TransTasman)[.](http://rspas.anu.edu.au/pah/TransTasman)

### Canberra 8-10 October, 2004

Presentations on any aspect of New Zealand and Australian contributions to Christian missions are invited.  
A wide variety of presentations is expected, with a focus expected on the contribution of women to the missionary cause.

Semple, Rhonda Anne, (2003)  
Missionary Women: Gender, Professionalism, and the Victorian Idea of Christian Missions  
Rochester, NY, Boydell Press.

### Charlotte Yonge's own Preface to***The Making of a Missionary***

THIS tale was begun, and indeed nearly completed, before China had become the scene of more than the sudden raids of fanatics, such as those Vegetarians who fell on the Stewart family and their helpers at Kucheng. Of the cruel persecution by the so-called Boxers, nothing then was known, and the war had only just begun when the last chapters were written. In fact, only the first attacks had then been made, and the terrible atrocities that followed were yet unperpetrated. The end is not yet come, but by the time this tale actually appears there will probably have been much more to lament, and thus far we can only feel that

and join in the thanksgiving of the Church for Brooks, Robinson, and Norman, and the countless Chinese Christians whose names we shall never know, but who have won their crowns in Paradise. For be it remembered that all agree that when a Chinese is converted, he is so from his heart, and in reality.

I have not attempted many Chinese scenes, for want of sufficient information as to the habits of the converts, and I have avoided names of persons, as it is dangerous to invent or to copy names from a language not understood; and besides, the chief details to be had were from Southern China, where, though the written language is the same to the eye, a totally different dialect is spoken.

In fact, my object has rather been to trace the growth of the purpose of self-devotion, and what it may lead to when once the seed, however small, has been planted.

C. M. YONGE.  
June 12, 1900.  


