---
title: "Charlotte Mary Yonge - Marie Thérèse de Lamourous"
year: 1858
slug: "marie_therese_de_lamourous"
format:
  html:
    toc: true
---


[Online text of : Marie Thérèse de Lamourous](http://books.google.com/books?vid=06TU8YjmS6L2p8lZ&id=9JYBAAAAQAAJ&printsec=titlepage&dq=%22charlotte%2Bmary%2Byonge%22&as_brr=1)

Google scan  
PDF file available for download from the Google webpage.

Contemporary review of this any other Yonge works available online in Dublin Review

[Dublin Review vol XLV September and December 1858](http://books.google.fr/books?vid=0n5hTRWzGJI46fFvCu&id=tdrEz2Y0qegC&pg=PP8&dq=miss%2Byonge&as_brr=1#PRA1-PA324,M1)  
Google scan, starts bottom of page 324 ff****

**Marie Thérèse de Lamourous : foundress of the House of La Misericorde, at Bordeaux : a biography /**

Lamourous, Marie Thérèse de, 1754-1836

Pouget, Firmin, 1800-1870.

POUGET

#### L'ange de Bordeaux.  
Vie de Mlle Thérèse de Lamourous.

Paris, Saint-Paul/Grammont (Belgique), Ôuvre de Saint-Charles, 1905

#### Marie Thérèse de Lamourous,  
Firm of Hand, Loving of Heart

by Joseph Stefanelli, SM

During the French Revolution, Marie Thérèse was a part of the underground in Bordeaux, bringing comfort to the sick, teaching catechism, visiting the prisons, and carrying messages among the clergy. She met Father Chaminade and began a forty-year association with him. Later during the Revolution she went to Pian, where she sustained the faith life of the people in the absence of priest, leading prayer and holding catechism classes. After the Revolution, her work with repentant prostitutes at the Miséricorde ("House of Mercy") and with the Sodality in Bordeaux occupied the remainder of her life.

Stefanelli's new 30-page biography looks at the many works of Marie Thérèse and how this "Saint of Bordeaux" played in integral role in the early days of the Marianists.

His book examines how Marie Thérèse balanced the supervision of the 230 acre family property at Pian, a few miles northwest of Bordeaux; her ministry at the Miséricorde; the support of her extended family; and her work with Father William Joseph Chaminade in establishing the Bordeaux Sodality and participating in the foundation of the Daughters of Mary and the Society of Mary. Her administrative and organizational skills were put to use in all these endeavors.

Father Stefanelli is also the author of Mlle de Lamourous, a 517-page resource on the life of Marie Thérèse de Lamourous (1998).

Marie Thérèse de Lamourous, Firm of Hand, Loving of Heart concludes Father Stefanelli's popular trilogy on the Marianist Founders. It is a companion piece to Adèle, Aristocrat for the Poor and Chaminade, Pragmatist with a Vision.

