---
title: "Memoirs of Colonel Bugeaud - translated and edited by Charlotte Mary Yonge (1884)"
sort_title: "Memoirs of Colonel Bugeaud - translated and edited by Charlotte Mary Yonge (1884)"
year: 1884
slug: "memoires_of_colonel_bugeaud"
format:
  html:
    toc: true
---


*1884*



Memoirs of Colonel Bugeaud from his private correspondence and original documents 1784-1815 – by the Count H. d'Ideville

++++++

Le maréchal Bugeaud : d'après sa correspondance intime et des documents inédits, 1784-1840 / H. d'IdevilIe

Ideville, Henry-Amédée Lelorgne, comte d', 1830-1887

++++++

Bugeaud, Thomas Robert, duc d'Isly, 1784-1849

Thomas-Robert Bugeaud de la Piconnerie joined French Army in 1805, and served as a grenadier of the Velites of the Imperial guard Austerlitz-Pultusk. Commissioned in 1806, he served at Austerlitz and Pultusk, and did notable service in the Peninsular War, participating in the sieges of Saragossa and Lerida, and various combats against the SpanishSaragossa. He was promoted Chef de Battlion 1811 and then served with L'Armee D'Aragon and in 1815 L'Armee des Alpes.

Bugeaud, Marshal Thomas Robert  
MEMOIRS OF COLONEL BUGEAUD  

Worley 1998 Reprint of 1884 ed. 184pp  
Worley Publications with Brigade Library, Tyne and Wear 1998

Worley Publications (publishers of Napoleonic books and memoirs)  
10 Rectory Road East, Felling, Tyne and Wear, NE10 9DN, UK

Telephone (00 44) 0191 469 2414

Life and achievements of Bugeaud

Solid biographical overview of the life and achievements of Bugeaud:  
[http://www.ohiou.edu/~Chastain/ac/bugeaud.htm](http://www.ohiou.edu/%7EChastain/ac/bugeaud.htm)

