---
title: "Charlotte Mary Yonge - The Miz Maze or The Winkworth Puzzle: A story in letters -- by nine authors: Charlotte Mary Yonge, Frances Awdry, Mary Bramston, Christabel Rose Coleridge, A.E. Mary Anderson Morshead, Frances Mary Peard, Mary Susanna Lee, Eleanor C. Price, and Florence Wilford"
year: 1883
slug: "miz_maze"
format:
  html:
    toc: true
---


#### Online text ofThe Miz Maze

[*Click here to view and download online versions of*The Miz Maze**](http://ia350613.us.archive.org/0/items/mizmazeorwinkwo00awdrgoog/)

#### The Miz Maze- An experimental epistolary novel

#### From the Preface:

"It had sometimes occurred to two of the writers of the ensuing correspondence that novels in letters generally were unsatisfactory because the various characters could only be the same person under different masks. They therefore resolved to try the experiment of putting the representation of each correspondent into different hands ... so that there may be the difference that real life might produce in style and way of thinking."

Frances Awdry

Mary Bramston

Christabel Rose Coleridge

Mary Susanna Lee

A.E. Mary Anderson Morshead

Frances Mary Peard

Eleanor C. Price

Florence Wilford

Charlotte Mary Yonge

*Who wrote what is not identified*

