---
title: "Mothers in Council"
sort_title: "Mothers in Council"
slug: "mother_in_council"
format:
  html:
    toc: true
---




A Real Childhood

by  
Miss Yonge

Mothers in Council - Vol II, No 5 January 1892, pp 15-19

I SHOULD like to give a few pictures of real childhood. Perhaps, if I begin with my own recollections, others may follow, and I will try to be perfectly truthful.

Perhaps there were unusual circumstances to lead to the complete oneness between my mother and myself, for we lived with my grandmother, who for nearly twenty years took the household cares. Moreover, I was an only daughter, an only child for six years, and the object of much more attention and solicitude than I ever was allowed to know.

It was an old-fashioned up-bringing-with much that would shock sanitarians now-only one nursery-also the maids' work room and the nurse's sleeping-room (in a press-bed). However, I was generally outside the nursery, though it was a home, and all my meals were taken downstairs, except supper-milk and dry bread ; 'nice crustesses,' as the maid used to say, in a tone of congratulation. I have been glad ever, since of having been thus taught to enjoy dry bread. The rule was that those who could not eat dry bread were not really hungry-a very good rule. Butter, as a rule, I never had. I remember my indignation when a naughty, good-natured housemaid, in misplaced pity, brought slices with the buttered side turned down to escape the nurse's eye. I don't know that the absence of such nutritious food is an example, but I am sure the prevention of dainty habits was an advantage. However, dining at luncheon time, the fat trouble never was surmounted, and certain joints recall it to me still. But greediness was treated as despicable. We were rebuked for casting sidelong glances to see what pudding was coming, taught never to meddle with fruit not given to us, and that gathering strawberries was pleasure enough without eating them till the proper time. Sweets we never bought, and, if given, were administered one at a time at bedtime. The denial was never felt as a hardship, and it has certainly been of no small benefit in health and discipline.

As to the maids sitting with the nurse, I am decidedly of opinion that it was unadvisable. One woman, though really very good-natured, used to put me in a passion for the pleasure of seeing me roll on the floor. The sure way was to incite the nurse to repeat that tragic poem of Jane Taylor's on the melancholy adventures of 'Poor Puss,' which tore my heart. I remember matters unsuitable to 'little pitchers'' ears being discussed; and a cousin of mine heard Pamela being read aloud after she was in her crib.

The above anecdote shows that I was not too good a child, though naughtiness was never tolerated for a moment. I think it was chiefly noisiness, disobedience, slovenly carelessness, and quick temper, with a certain provoking levity, since I have heard a story (though beyond recollection) of having been put in the corner, and there beginning to sing, in a high squeak,

'Be gone, dull care!'

The only flat falsehood of those early days was so seriously treated that it is a pain to me to remember it now. One other, some years later, hung on my conscience so heavily, that I voluntarily, with many tears, confessed it, 'after what now seems a long time. Equivocating was shown to be equally heinous, the occasion of my being so taught being that my father detected me making a sort of accompaniment to the responses in church, instead of following the words. His displeasure at my thus acting a falsehood was not to be forgotten. Perfect truth and honour seem to me to have been the strongest of all my early impressions.

My father, a Peninsular and Waterloo soldier, was the hero of heroes to both my mother and me. His approbation was throughout life, my bliss, his anger, my misery for the time, though my elastic, frivolous spirits so soon recovered that I was thought not to care. No liberty was ever taken with either parent; the half-saucy, half-petting terms of children to their parents were never dreamt of. My father could be very stern, but also very gentle, and he took great pains with me. The stories he told me, and those first books he read to me are still glorified. One needs no glory of association, being Joseph's history; but 'Bel and the Dragon' will always be linked with the scene in the long journey which he beguiled with it. Then the Pilgrim's Progress he began when I had the measles, and 'Aladdin's Lamp' and the 'Perambulations of a Mouse' always recall the delight of hearing them from him. Such kindnesses from an intensely respected father dwell with one for ever.

He taught me to write, after an idea of his own, in large letters in chalk, done without resting the hand, thinking this would conduce to freedom of hand in drawing. He was not always patient at the time with childish carelessness, but he was most persevering, and most warmly fostered all real attempts to do one's best.

Daily, before breakfast, he read the Bible with us, from Mant's edition. Nor can I remember a time when I did not say prayers, repeat the catechism every Sunday, and go to church, being taken early that no one might be kept at home. There was teaching of the meaning of these things, and of Scripture history, but the manuals of those days were not many, nor very helpful. However, a great Dutch Scripture history, with an immense number of prints, impressed Scripture events; and from seven years old, my mother took me to the Sunday school, first to learn, and then to teach, when, however, I was much too young to be put in authority. I was more a conscientious than a religious child. Except a vehement pleasure in the Sunday school-which was not so much for religion's sake as for the love of teaching-I felt these observances a weariness, though I should have been ashamed to say so, and felt that it was my own fault.

It was a strict Sunday-two services, two Sunday schools, books always of a religious cast, and not too many of them, hymns and catechism in the evening; but I grew gradually up from the sense of lengthiness to actual enjoyment, at first through the Sunday school. Lax Sundays would never have had the same effect.

Intellectually the religious teaching interested me, but my parents were of the old reticent school, reverent and practical, so as to dread the drawing out of feeling and expression, for fear of unreality, and I do not know of much awakening in me to religious warmth, unless it may be impulses of thankfulness for a beautiful day, and an extreme terror of the Last Judgement. Fancying it would only come when nobody was awake, I remember trying to keep off sleep by pulling out the hairs in my mattress. This, however, was only like other terrors that haunted my bedtime, such as wolves in the dark hall, gunpowder plots, and the fate of the princes in the Tower. These are, I believe, the lot of all imaginative children. My parents were my practical religion and conscience.

My mother had read and imbibed the Edgeworth books. She was perfectly regular in her teaching, and never gave holidays unless there was a needful occupation, but there were no lessons after one o'clock. She had the old London school education, and was very thorough, hut she had the art of making her teaching pleasant, with playful observations. At four years old I could read. The discovery that I was capable of reading to myself was too delightful to be forgotten. It was made over a quarto illustrated Robinson Crusoe, beside a print of him contending with the breakers. French in children's stories was easy to me at seven or eight years old; also the order of Kings of England, and their histories in Bishop Davys's little book; nor do I think there was the slightest damage to health or brains from what people now call over-forcing.

It was a happy, healthy, childhood, with much joy in play, running about boisterously in upper rooms, and out of doors, delighting in dolls and in live creatures, and in all quiet games, having the best of playfellows in my mother, though her health would not permit her to walk out far with me. She was much afraid of my being vain. Once, on venturing to ask if I was pretty, I was answered that all young animals, young pigs and all, were pretty. It would probably have been wiser to tell me her true opinion, for the question of my beauty was a problem to me all my earlier life. My hair, in those days, was of a rich chestnut colour, in wavy curls; but it delighted her that I answered a lady who admired it (out of Miss Edgeworth), 'You flatter me!'

There was hardly any companionship with other children, except in an annual visit to a large family of cousins, whose company was perfect felicity, but who were brought up on the same lines, perhaps even more plainly and strictly. These recollections reach to about seven or eight years old.

The special point experience would lead me to remember is that justice and strong displeasure at wrong-doing, severe criticism on carelessness, and no weak indulgence promoted the most fervent love and honour to my father, and that my mother's perfect loyalty to all his opinions and measures, and her unfailing tenderness, sympathy, and playfulness made a life of happy affection and lasting reverence.

C. M. YONGE.

Stepmothers

By C. M. YONGE

Mothers in Council - Vol VI, No 23 July 1896, pp 130-135

THIS is not written from personal experience, but from the amount of observations that no one can fail to have made in the course of a lifetime, and in the hope of bringing out further and more useful observations upon one of the most difficult positions upon which a person can voluntarily embark.

It has been said, and probably with truth, that the cruel stepmother of fiction is really an inheritance from the pagan times when myths began, and there was a rivalry of living mothers, whose whole status as queen or slave depended on the heirship of the favoured son. The tendency of the modern stepmother is indulgence, and in fiction she is always represented as coming in like a sunbeam on the child terrified by the nurse's prognostications. Yet, with the best intentions, there are difficulties in the way often unforeseen.

With boys these are generally slight difficulties. The poor fellows are so glad to have the house no longer dreary, and so relieved to have motherly sympathy, that a fairly kind and conscientious woman can generally 'get on' well with them, and often so warm an affection grows up that it is not easy to believe them not actually mother and sons, especially when no other children come to claim her affections.

Indeed, one perplexity that sometimes arises is that the father is apt to be more indulgent to the children of his comparative old age than to the elder family, whom perhaps he regarded with the experimental sharpness of youth and inexperience. This does not tell so much on sons, who are less dependent on home, as on daughters, who recollect the way in which offences were visited on their own brothers, and may think the later vein entirely due to the favour of the stepmother, even if she be the more punctilious parent and the most anxious for strict justice. If, however, she can make home a pleasant resort to the growing lads, show sympathy and win their confidence, her task with them is comparatively easy.

With the girls, probably, the welcome is not the trouble. Good young people, fairly right-minded, will have made up their minds not to vex their father or make a bad begin-fling; and, if they are younger, unless their minds have been prejudiced, novelty and change from a trying interregnum renders them willing to accept a change.

The troubles come later, when the new mistress ceases to be 'company,' and the family has to work in together. In point of fact, women always find it harder to amalgamate than opposite sexes do, for there are endless little idiosyncracies that may clash, such as the opening of doors or windows, tolerance of noises, precautions as to health, and a thousand little matters which prey on temper and nerve, and even may be connected with principle. They may often prove the 'little rift,' unless there is tact and forbearance. We are considering very different possibilities. There is the man who is driven to seek a wife by the daughters who need a chaperon, and who have shown themselves incapable of ministering to his comfort,. managing the household, or taking care of the little ones; there is the man who had never found his match before, and is beginning life again more congenially; there is the man who has felt his house too dreary to be borne, and is much molested by advice; and there is he who has loved faithfully once, and is ready once more for hearty love.

What is to be said in each case? It really amounts to considering the difficulties rather than advising on them,. but perhaps this statement from an outsider may bring out advice from the experienced.

One thing is clear, the stepmother must mount her step, and make it clear that she is the mistress of the house. Where there are grown-up daughters, their father has very likely told them that he is only bringing them a companion, whom they will call by her Christian name. This is not quite wise, and it would be better perhaps to have a serious conversation with them before there has been time for a collision or misunderstanding, and make it clear that, as lady of the house, it is fitting that engagements and invitations should never be made without reference to her. Nice girls will assent, but probably occasions may arise when the loss of liberty may be felt~ and great gentleness, as well as quiet resolution, will be needed to keep up authority while there is indulgence or tolerance as far as is practicable. If there be real difficulty, an appeal to the father should be the very last resort, and the daughters should be made to perceive that it should be the desire of the women folk not to vex and worry him, yet that he is the dernier ressort. Inevitable changes there must be, but the new-coiner will gain much by sacrificing her own taste-not her principle-to the young people, above all when there are connexions of association and loyalty to the past. Remember, in Wives and Daughters, bow Mrs. Gibson overturned Mollie's beloved bedroom that it might not seem inferior to her Cynthia's.

When the stepmother comes in upon a reign of misrule and comparative anarchy, such as may have grown up under incompetent aunts, or with governesses more intent on winning the father than managing the children, her task is simpler in theory. Authority must be established and enforced, and, where the wills are strong, it can hardly be done with rose water. If the schoolroom has been a trouble and perplexity, probably there will be sufficient support at the ultimate tribunal to enable reforms to be carried out. The difficulty is to unite needful severity with attraction enough to win confidence and affection. Surely this should be done by great willingness to meet repentance half-way, by sharing and promoting. little pleasures when in any way merited, by holding out the prospect of earning the father's commendation. There should be those religious readings and talks that no parent should neglect, and, if possible, promotion of pleasant occupations or pursuits, so as to make the children feel that they have come to a happier, brighter world than when they ran wild. No one really hates having a strong hand over all: it is actually a comfort to know what may and what may not be done; it is uncertainty that is the trial. Firmness is far better than indulgence, but firmness coupled with sympathy is loved.

The difficulty here is that hereditary tastes and customs clash, when in close contact in such matters as an open window, eating fruit or sweets at irregular times, or tidy habits, and the very greatest care is needed to be firm without infringing on real loyalty to the past. When the children use the plea, 'Mother always let us,' or 'Auntie always let us,' they may think themselves speaking the truth, but they do not always do so; and 'You are older now' is often a safe answer to what may be objectionable. Management or non-management of health should not be hastily reversed, whether the children have been used to what seem too hardy, too tender, or too dainty customs. Tempers and constitutions both need study. Children. used to all sorts of weather will resent precautions as nonsense and tyranny, and these need to be gradually and kindly brought in, even when needful. Those who seem to be coddled may require care of a kind to be only learnt by' experience, and even with over-dainty tastes a rough break may be at the cost of alienation. Have we not sympathised with the children in East Lynne, whose aunt deprived them' of their egg for breakfast? These are only hints to check impetuous changes, such as may leave impressions dangerous' to later confidence and affection.

Whatever the children may have previously called their own mother should be left sacred to her. For my own part,. I love the tender 'mamma' as a title, leaving the more' dignified, almost holy, 'mother' out of the wear and tear of daily use, and avoiding the silly contractions that are on the borders of 'familiarity breeding contempt.' I know 'paw and maw' have vulgarised the terms, but I cannot help preferring them. However, all I meant is that it is best to leave the real mother her own proper title, and always to treat her memory reverently, even if all she has done may not seem desirable.

Often girls will show a vehement preference for their aunts, especially maternal ones, and they may really have affinities with them that are wanting in the stepmother. It is a very hard task not to provoke jealousy or prejudice, especially when the aunts may not be very wise or satisfactory, and the effect of intercourse with them may not be conducive to harmony at home.

Let me here entreat of the aunts to avoid comparison; and to do all in their power to support the stepmother, as the only way to family peace. Whatever they may think, however much they may pity their sister's children, or dislike the successor, it must be a very strong case indeed in which sympathy shown on the niece's side against her government does not do harm.

Even children orphaned too young to remember their own parent, as they grow older, whenever they feel aggrieved, are prone to raise to themselves a shadowy mother, compounded of their favourite aunt and of impossible perfection, and to believe in moments of 'grizzling' that nothing would have gone wrong if their own parent had been alive. With such yearnings, generally in silence and unknown, the stepmother has to contend almost inevitably.

Moreover, another difficulty may sometimes grow up. She may wish to be scrupulously impartial to her own children, but if her rule is easier and more demonstratively affectionate than what the elder children recollect, it may be viewed as maternal partiality, and awaken jealousy. Perhaps it makes it needful that her vigilance and justice should be very careful, and that she should show special kindness to the elder ones, and bring their more favourable aspects before their father, avoiding complaint when not absolutely needful. It is well, too, to make each a special guardian to a little brother or sister.

Yet there is another extreme. Some become almost slaves to their stepchildren in the fear of being supposed to be tyrants. This is a mischief to be deplored. Nothing can go right in a family without just authority and firmness, and to abdicate it is ruinous to all peace and good conduct. The long and short of what I fear is a very unsatisfactory discussion seems to be that, with the fear of God and love of justice and kindness before her eyes, a stepmother is often deeply loved and respected, becoming indeed a true mother; but that she will probably have much to undergo, which can only be endured and conquered through love, hope, and patience.

The Church of England Union for Mothers was founded by Mary Sumner in about 1875.

Charlotte Yonge, though, though never a mother herself, was a contributor to and editor of its Journal –*Mothers in Council*– at quite an elderly age, and carried out this work in the 1880s –1890s.

The Mothers' Union, now with over 3 million members worldwide, recently celebrated its 125th anniversary. See the impressive[Mother's Union website and online shop](http://www.themothersunion.org/)for more on the organisation today

