---
title: "My Young Alcides (1875) by Charlotte Mary Yonge - translated and edited by Charlotte Mary Yonge (1884)"
slug: "my_young_alcides"
format:
  html:
    toc: true
---


**Charlotte Yonge's Preface to*My Young Alcides***

"Ideas have a tyrannous power of insisting on being worked out, even when one fears they may be leading in a track already worthily pre-occupied.

But the Hercules myth did not seem to me to be like one of the fairy tales that we have seen so gracefully and quaintly modernised; and at the risk of seeming to travestie the Farnese statue in a shooting-coat and wide-awake, I could not help going on, as the notion grew deeper and more engrossing.

For, whether the origin of the myth be, or be not, founded on solar phenomena, the yearning Greek mind formed on it an unconscious allegory of the course of the Victor, of whom the Sun, rejoicing as a giant to run his course, is another type, like Samson of old, since the facts of nature and of history are Divine parables.

And as each one’s conquest is, in the track of his Leader, the only true Conqueror, so Hercules, in spite of all the grotesque adjuncts that the lower inventions of the heathen hung round him, is a far closer likeness of manhood-as, indeed, the proverbial use of some of his tasks testifies-and of repentant man conquering himself. The great crime, after which his life was a bondage of expiation; the choice between Virtue and Vice; the slain passion; the hundred-headed sin for ever cropping up again; the winning of the sacred emblem of purity; then the subduing of greed; the cleansing of long-neglected uncleanness; the silencing of foul tongues; the remarkable contest with the creature which had become a foe, because, after being devoted for sacrifice, it was spared; the obtaining the girdle of strength; the recovery of the spoil from the three-fold enemy; the gaining of the fruit of life; immediately followed by the victory over the hell-hound of death; and lastly, the attainment of immortality — all seem no fortuitous imagination, but one of those when “thoughts beyond their thoughts to those old bards were given.”

I have not followed all these meanings, for this is not an allegory, but a mere distant following rather of the spirit than the letter of the old Greek tale of the Twelve Tasks. Neither have I adhered to every incident of Hercules’ life; and the most touching and beautiful of all— the rescue of Alcestis, would hardly bear to come in merely as an episode; in this weak and presumptuous endeavour to show that the half-divine, patient conqueror is not merely a classic invention, but that he and his labours belong in some form or other to all times and all surroundings."

*C.M. YONGE, Nov. 8, 1875.*

Back to top of page

### ***My Young Alcides***– Plot summary

### I The Arghouse Inheritance

Lucy Alison (23 years old) learns that by a first marriage, her late father had twin sons Ambrose and Eustace. Led away by the revolutionary spirit of Count Prometesky, a Polish exile, they became ‘democrats’ and married two sisters, farmer’s daughters, Alice and Dorothy Lewthwayte. At the time of the 1832 Reform Bill, aged 21, they took part in rioting for which they were tried and transported to Australia; the wives and their two small babies went with them. They subsequently prospered as farmers on an estate called Boola-Boola. Ambrose died and his wife Alice married a clergyman called Smith. Now, twenty-six years later, with Lucy’s father and mother both dead, the Arghouse estate is to “go in the male line to the son of one of [her] disinherited convict brothers”. Two sons arrive: Harold, Ambrose’s son, and Eustace, son of Eustace; also Eustace’s eight year old sister Dora, who calls herself Harold’s ‘wife’. To Lucy and her friend Viola Tracy, the first impression of Harold is one of size, strength, and kindness.

It seems at first that Harold will inherit, but it turns out that the will specifies the eldest grandson to be born at home: Ambrose and Alice’s first baby had died on the voyage out, so Eustace is in fact the heir. Harold is to stay until Eustace gets settled in. Lucy accepts the offer to make her home with them; as their half-aunt, she can do so with propriety; however, the local county society has got hold of a number of discreditable stories about the Australian newcomers, and the whole family is shunned socially. Harold is determined to get a pardon for Prometesky, but lacks an influential sponsor. It starts to become apparent that Harold is the stronger, more able, better character in every way; Eustace is weak, vain, and snobbish.

*Back to start of summary*

### II The Lion of Neme Heath

At the Neme Heath horse fair, a lion escapes from a travelling menagerie and attacks a child. Harold manages to overpower it until Dermot Tracy, son of Lady Diana Tracy and nephew of Lord Erymanth, arrives with a rifle and shoots it. Harold’s badly injured hand is treated by young Dr George Yolland. Dora jealously throws away a ring which Harold has constantly worn. It was his wedding ring, and Lucy learns the following story. As a youth, Harold married Meg Cree, a storekeeper’s daughter. She made his home intensely miserable; his uncle and cousin Eustace were wretched, and Harold became reckless and alienated. Harold and Meg already had one child when she went back to her father for the birth of her second child. There her demeanour towards another man aroused Harold’s jealousy, and he insisted on taking her away once the baby was born. Drunk and angry, he drove so recklessly that he killed Meg and both children. He then met the man whom he thought Meg had favoured, and killed him in a fight. ‘Brain fever’ and delirium followed, and there was a long period of recovery. What brought him fully back to life was the need to search for Dora (then aged six) who was lost in the bush. The elder Eustace, worn out, subsequently died, committing both his children to Harold’s care; at his death-bed, Harold had spontaneously taken a solemn oath that he would never again touch alcohol.

Dermot Tracy and his sister Viola are childhood friends of Lucy; an incipient attachment between Dermot and Lucy was checked by Lucy’s late mother, who disapproved of Dermot’s wildness. Dermot hero-worships Harold, and introduces the Alison men into county sporting society. Harold continues to support his mother and her second husband Smith (a dishonest and hypocritical clergyman), but means to prevent them coming back to England to prey upon Eustace as heir.

*Back to start of summary*

### III The "Dragon’s Head"

The chief industry in the little local town of Mycening is the unsuccessful Hydriot Clay Works, producing tiles and pipes. Eighteen years of industrialisation (opposed by the local gentry) has made Mycening a rural slum, where such scanty wages as the men earn go on drink. Dr George Yolland, though an unbeliever, tends the unfortunate population devotedly, and opens Harold’s eyes to its misery. Actuated by humanitarian rather than religious principles, Harold buys up the "Dragon’s Head" public house, and announces that he intends to run it as a temperance reading room. Numerous beer-shops spring up instead.

Harold determines to become the major shareholder in the Hydriot works in order to run it more efficiently; he is encouraged by George Yolland, who is experimenting with a more economical form of fuel, and by a letter from Count Prometesky, recalling the excellent quality of the local clay, suitable for fine wares. George Yolland is seriously injured in an explosion caused by the carelessness of his assistant. His brother Ben, a curate, comes to nurse him; and eventually becomes curate at Mycening.

*Back to start of summary*

### IV The Wrath of Diana

George Yolland’s senior partner dismisses him, and he becomes manager of the Hydriot works. He is to live with his brother on the premises of the new reading and community rooms. Ben Yolland starts a Sunday children’s service, to which Dora goes. Harold takes her there, and begins to stay and listen. A child’s funeral is the first time the idea of eternal life makes any impact upon him; as he comes to realise that this is enjoyed his own dead children, the terrible guilt he feels for their deaths is somewhat lessened. Lucy tries to tell him about “what had cancelled all”, but feels that her own religious understanding is not deep enough; Harold refuses to talk to a clergyman, mistrusting them all because he so disliked his stepfather Smith.

Several months pass and society still ignores Lucy and her nephews. One day she is delighted to have a visit from Viola Tracy, ‘captured’ while out riding by Harold, Eustace, and her brother Dermot. Viola knows her mother, Lady Diana, will disapprove, as indeed she does. Harold and Eustace both find Viola charming; Dora is jealous: since her rescue by Harold, she has always called herself his wife.

*Back to start of summary*

### V The Capture in the Snow

The new products of the Hydriot works start to have some success but the social isolation continues. During a terrible snowstorm, Harold comes upon a stranded train and rescues an elderly passenger. He struggles through to Arghouse, where the old man proves to be Lord Erymanth, Lady Diana Tracy’s brother. When Dermot arrives the next morning, frantic with worry about his uncle, he is enormously relieved to find him safe, and prosing on in his usual pompous, repetitive fashion. Lord Erymanth recognises that prejudice and malice have traduced the characters of Eustace and Harold; he will see to it that they are accepted by society.

*Back to start of summary*

### VI Ogden’s Buildings

Lord Erymanth congratulates the Alisons on the improvement of the general tone in Mycening, where several beer-shops are closing; he recommends improving the dwellings on the Arghouse property and replacing the Arghouse agent, Bullock, as dishonest and unfit for his job; Eustace takes credit for all improvement and avers his intention of being a model landlord. Lord Erymanth sternly refuses to help Prometesky to a pardon, holding him responsible for all the rioting. He departs, having invited the Alisons to Viola’s coming-out ball: Eustace is overjoyed at this. When Harold says that Eustace needs “a good agent and a good wife” before he can safely be left, Lucy points out how much Harold is doing for him.

Ogden’s farm in the Alfy valley is an undrained, unhealthy disaster; Harold cannot persuade the obstinate farmer to undertake drainage work, but the latter agrees when Harold promises to carry it out with his own hands, aided only by the farmer’s son Phil. Two days of hard work see the task done and Ogden convinced — but Eustace is disgusted and considers that Harold will not be fit to be seen at Viola’s coming-out ball.

*Back to start of summary*

### VII The Birds of Ill-Omen

At the ball, Viola is delighted by Lucy’s present (a Hydriot works flower-pot, chosen by Harold and planted by Lucy) and contemptuous of Eustace’s scent spray of porcelain violets, bought in London. Eustace is delighted at being introduced into society by Lord Erymanth, where he is welcomed as the Arghouse heir; little attention is paid to Harold. Whispered rumours still abound about the works (‘“the glaze on the pottery is dead men’s bones”’), and about Harold’s past in Australia. They come chiefly from members of the Stympson family. The next day, Lady Diana feels it her duty to pass all these on to Lucy, and urges her to get a lady chaperon to live with them at Arghouse; she does not yet urge Lucy to give up her nephews. That follows, however, when a letter from one of the Stympson ladies details a number of accusations of gambling, cattle-stealing and fighting. Lucy regards these as incredible and there is a breach with Lady Diana.

Harold comes back from a long walk, soaked through because he has jumped into the river to rescue a dog. It proves to belong to the Misses Stympson, who call to thank him for an action of great bravery and strength, The Stympsons aver that they will never again believe any of these wicked rumours (which they are unconscious of transmitting). When Lucy afterwards tells Harold that these ladies were themselves the rumour-mongers, and congratulates him for an act of heroic forgiveness, he rejects the notion, deeming Christian forgiveness as weakness. Eustace later tells Lucy that Harold has had a horror of dogs since the night of Meg’s death when they had followed the buggy; in his delirious illness Harold had believed he was being pursued by a pack of black hounds. Lucy notes a change towards irritability in Harold, though he tries hard to control it; she regrets that his moral strength, unaided, cannot prove equal to the demands made upon it.

*Back to start of summary*

### VIII Bullock’s Chastisement

The agent, Bullock, is caught menacing an old woman tenant; Harold throws him out. Eustace backs Harold up but is aghast when Bullock brings a charge of assault. Lucy bears witness in court to Bullock’s disgraceful behaviour, and Harold is given a token fine. This episode makes him very popular with the workmen of Mycening. Harold in effect takes on the role of agent to the estate.

After a day with the Foling Hunt, Eustace tells Lucy that Harold has got drunk at the hunt dinner. Some of the hunt members, Ernest (Nessy) Horsman prominent among them, had tried for a bet to lure Harold from his pledge of teetotalism; they had first tricked him by giving him a liqueur of unfamiliar name, then had encouraged him to drink more and show off feats of strength. Lucy finds Harold at George Yolland’s, determined to leave for Australia: he is disgusted and desperate because he has broken his vow. Lucy feels that for him to leave is to invite self-destruction; he has been cheated and tricked, and must seek divine help rather than trusting to his own unaided self-control. Harold agrees to try. Lucy is determined that he must walk home with her rather than getting a cab for her at the public-house; as they walk, Nessy Horsman and others invite Harold to join them, and jeer when he refuses. The weather is so bad that Lucy has to take shelter in church, and she insists that Harold come in with her. There he hears, for the first time, the Confession, and is overcome. The next day, he asks Lucy for help and guidance. She encourages him to pray and to feel that with time, temptation can be overcome. From now on, he attends church, but, as yet, no more. He falls asleep in the sermons, and refuses to talk to the clergyman Ben Yolland. Ben tells Lucy it is best for the time being to go on as she is doing.

*Back to start of summary*

### IX The Champion’s Belt

The widow of a distant cousin comes to live with the Alisons; she is very elderly, almost penniless, and rather confused. Her only other living relative is her ne’er-do-well son Henry, gone to Australia and long lost sight of. She acts as chaperon and ‘grandmother’ to the family.

Eustace blames Harold for spending out too much on improvements to the estate because it prevents him from cutting a fine figure in the London season. However, the family make a brief visit to London, where Lady Diana does her best to throw Eustace in Viola’s way. At an exhibition of antique jewellery they see a family heirloom which has become the prize at their local Archery Club. The only way to get it back seems to be to win it, and then get the club to agree to accept a replica. Both ladies and gentlemen can compete, after which there is a shoot-out between the respective winners; for some years the overall champion has been Miss Hippolyta Horsman. When the match comes, Harold wins the belt, and Miss Hippo takes defeat very well in her great admiration of him. She later insists on photographing him with lion skin and bow. Harold is not won over by her attempts to interest and attract him.

*Back to start of summary*

### X Dermot’s Mare

Dermot Tracy, who is the absentee landlord of an estate in Ireland, invites Eustace and Harold to stay with him there. Dermot is seriously injured when approaching an ill-tempered mare; only Harold’s strength stops the mare from trampling him to death. Lady Diana and Viola go to nurse Dermot who makes a gradual recovery. When Harold gets back, he tells Lord Erymanth that Dermot should live on his estate and look after his tenants, who are in an appalling state of want. Lord Erymanth agrees, and hints that he and his sister look forward to Viola marrying Eustace. Lucy is indignant that Harold’s modesty and dislike of show allow Eustace to claim the credit for the improvements at Arghouse and Mycening. Harold admits to her that he has left Ireland because he cannot bear to see Eustace gain Viola. He intends, however, to go out to Australia, taking Dermot with him for a spell: this is to break Dermot’s habits of gambling and speculating in horses. When Eustace returns, Viola has refused his proposal, but her mother encourages him to try again later. Viola tells Lucy how entirely she sees through Eustace’s vanity and pretensions, and recognises what is due to Harold. Lucy knows that Viola will never accept Eustace and tells Harold so. He, however, feels that it would be profanation to offer himself and his past to the pure and innocent Viola: his repentance is not enough; the new world that was revealed to him when he first saw Lucy and Viola together is not for him. He helps Dermot to clear his debts by selling off his English property and the horses which have been ruining him, and for whose sake he has been draining exorbitant sums from his wretched tenants.

*Back to start of summary*

### XI The Red Valley Cattle Stealers

Some prominent visitors, one a leading politician, come to visit the Hydriot works; Eustace shows off, but Harold’s knowledge is appreciated by the discerning. Harold seizes the opportunity to put forward the request for Prometesky’s pardon, and is given some encouragement. Viola shows evident pleasure at this, which overjoys Harold, and for which he gives thanks. He later admits to Lucy that he has just begun to pray for Prometesky. He plans go to Australia to complete the Prometesky business and sell up Boola-Boola; he intends to settle in England, and then to ask for Viola’s hand. Old Mrs Alison asks him to look for her son Henry while he is out there, and also makes him promise to go and see his own mother, now in New Zealand. He is reluctant because, detesting her husband Smith as he does, he cannot trust himself to meet the man without harbouring murderous feelings. Lucy urges him that, with God’s help, he can do his duty; she also longs to see him helped by taking the sacrament, but he will not hurry that on before his conscience allows him.

Harold and Dermot find Prometesky living like a scholar-hermit. The area is menaced by a gang of bushrangers based in the Red Valley. Harold joins a party to hunt them out, and overcomes the leader. He is unwilling to shoot him, as he suspects he is the missing Henry Alison (as indeed proves to be the case): instead, he wrestles him down, giving him three falls before gaining the victory.

Back to start of summary

### XII The Golden Fruit

At home, Eustace behaves with increasing petulance and extravagance. He becomes engaged to Miss Hippolyta Horsman; Viola is delighted, as this frees her from his attentions. Harold, who is nursing the badly injured Henry Alison back to health, sends for Mrs Alison to go out to her son. Much of Henry’s wild and dissolute behaviour has been attributed, through rumour and confusion, to Harold; this accounts for some of the earlier scandalous reports. Harold and Dermot meanwhile travel to New Zealand, where they find Alice living in a gold-digging area. She is desperately ill, and bullied by husband and stepson. She has managed to find and hide three golden nuggets, like apples, and wants them given to Eustace in repayment for money of which Smith had defrauded the elder Eustace. This is arranged, and Harold looks after Alice until she dies; he reads Bible and Prayer-Book to her, though she refuses to see a clergyman. He prepares to return, intending for the time being to live with Lucy at a house (Mount Eaton) she is preparing for herself, since she will have to leave Arghouse on Eustace’s marriage. She is not allowed to keep Dora, who is dispatched to live*en famille*with a Horsman cousin in London.

Back to start of summary

### XIII The Bloodhound

Harold and Prometesky arrive back the day before the wedding. With age and reflection, Prometesky has given up his radical views and returned to his Roman Catholic faith; he plans to become a monk at La Trappe. He praises Lucy for transforming Harold from “a noble savage to that far higher being — the Christian hero”.

As the bridal party leaves the church the next day, Hippolyta’s bloodhound Kirby, which is suspected of having hydrophobia, breaks loose and menaces the bride. Mastering his repugnance to dogs, Harold chokes him and manages to carry him away to be shot. The incident shatters everyone’s nerves, and the wedding party is uneasily facetious. Lucy and Harold regard this is inappropriate: grave thankfulness is the right reaction to such a narrow escape from death. Eustace grumbles at the size of the nugget-apples (his present to Hippolyta), at the price which Boola-Boola fetched, and at Prometesky’s presence in his house. Dora is delighted to see Harold and Lucy again: she hates school-room life in London with dull little girls, and her only fun is in visits from Nessy Horsman. Harold encourages her to do her duty there, and to say her prayers.

*Back to start of summary*

### XIV Sunset Gold and Purple

Lucy and Harold settle in at Mount Eaton, and Prometesky stays with them. His political views have been greatly modified by his rediscovered faith; Harold is affected by this change in his mentor. Harold, outgrowing Lucy’s guidance, has come to feel the need to consult Ben Yolland. Harold and Lucy visit Lady Diana, Viola and Dermot; in the course of a walk, Harold and Viola evidently avow their love for each other: Lucy and Dermot see them in a transfiguring glory of sunset light, the culmination of earthly love. Harold can feel Viola’s love as a token of divine love; his reaction is of awe-struck joy. However, Lady Diana now intends Viola to marry her distant cousin, Pigou St Glear, son of Lord Erymanth’s heir. She gives an unqualified refusal to Harold’s overtures, advancing a number of more or less fallacious objections; one is that Harold’s breakdown after Meg’s death is a sign of constitutional insanity. Viola and Harold are prepared for a probationary period of any length, but Lady Diana’s opposition is so adamant that Harold comes to feel it is his duty to give Viola up entirely, and to persuade her to do the same, with no mental reservation of a mutual understanding or of waiting for the future. He accepts the need for this with calmness and humility. They part for ever, and she gives him back a crystal cross he has brought her from New Zealand. Lucy has fears as to how Harold will bear it all, but Prometesky assures her he is a changed character. Harold takes Prometesky to La Trappe. When he returns, he visits Ben Yolland. The following Sunday, he takes Holy Communion for the first time.

Lucy and Harold discuss an uncertain future; he will leave the district to reduce Viola’s difficulties. He tells Lucy that he has learnt from Dermot that the latter always cared for her, but was offended by the apparent indifference she showed in obedience to her mother. Lucy knows that Dermot has reformed, thanks to Harold’s help, and can envisage her own future with him, though this will leave Harold totally alone. He expects to find a call to God’s service.

*Back to start of summary*

### XV The Fatal Token

Harold receives a letter from Dora (“your wife”), enclosing a lock of her hair, and saying she feels very ill. They learn from the Horsmans that Nessy Horsman has taken her to a shop where someone proved to have smallpox; he has also been teasing her about Harold’s attachment to Viola. The rest of the family has fled to safety, leaving Dora in London in the care of a maid. Lucy (immune because she has had a slight attack) goes to nurse Dora, urging Harold to get himself vaccinated. Unfortunately George Yolland is away. As Lucy last glimpses Harold at the station, carrying a tired child for a poor woman, he reminds her of St Christopher. Lucy travels to London with Ben Yolland, and is glad to learn that Harold’s example of self-conquest is having an effect on the irreligious George. Dora is seriously, though not dangerously, ill, and Lucy is occupied with her for several days before recovery sets in.

One evening Dermot Tracy appears. Lucy thinks he has come to tell her Harold is ill, but it is worse — he is dead. He suffered the disease in an acute and severe form; while at times suffering terrible delusions of pursuit by black hounds, he retained a literal and metaphorical hold upon the Cross, and was strengthened by words from the Litany. He has died peacefully, having overcome at last. He has already been buried, for fear of infection. Dora is dreadfully affected by the news, and takes a long time to recover. Dermot meanwhile catches the disease too. George Yolland brings Lucy Harold’s pocket book: everything has to be burnt except Viola’s crystal cross and a silver pencil-case of Alice’s. Harold has left all his property between Lucy and Dora. George tells her of the grief at Mycening, and the workmen’s wish to dedicate a window in memory of Harold. This is eventually carried out (only temperate men are allowed to subscribe); the subject is Samson “set in juxtaposition with the great Antitype”, and flanked by St George and St Christopher. Over the years, Mycening becomes a changed place, with Ben Yolland as Vicar of a new church, and George, who, chiefly through Harold’s example, has gained faith, as manager of the Works.

*Back to start of summary*

### XVI Conclusion

Lucy takes Dora to the seaside to convalesce. She has no news except that Eustace and Hippo are back from their honeymoon tour. One day Dermot appears; he has been extremely ill, and is now convalescing too. He is worried that Viola may be on the point of agreeing to marry her cousin Pigou; he is also despondent about his own future without Harold to keep him up to things; he doubts whether he will ever make himself worthy of Lucy. She admits she has always cared for him. They decide to marry very quietly as soon as possible, before Dora is sent off to school at Baden-Baden, as decreed by Hippo. Lord Erymanth comes down to give Lucy away. Lucy and Dermot are to live in Ireland; Lady Diana begs them to visit London, where they find Viola in a such a state of resolute resistance to grief that she is on the verge of a physical and mental breakdown. She only seems happy near Lucy and Dermot, so comes down to stay while Lucy packs up at Mount Eaton. They find her one day after her first visit to Harold’s grave, her self-control gone, and finally able to give way to her feelings. She realises how wrong it was “to try to bear it proudly, all by [her]self”. This is the start of her recovery, and of her reconciliation with her mother, who has come to realise her own mishandling of Viola. Viola’s future is as lady of Mycening, involved with the workmen and their families. Five years pass, and Dora returns from Baden, seriously ill from the strict and uncongenial regime. She recovers slowly with care from Lucy and Dermot, and marries George Yolland.

Lucy’s narrative is followed by brief comments from Dermot, Viola, Dora and George.

Back to start of summary  
Back to top of page

### Lucy’s ending and the comments of other participants (*My Young Alcides*, ch. XVI, pp. 374-6)

There! my work is done, though I fear it is a weaker likeness of my young Alcides than even the faded photograph by my side, but I could not brook that you, my children, should grow up unknowing of the great character to whom your father and I owe one another, and all besides that is best in our lives. There are things that must surprise you about your dear father. Remember that he insisted on my putting them in, and would not have them softened, because, he said, you ought to have the portrait in full, and that, save at his own expense, you could not know the full gratitude he feels to the man who made a new era in our lives. He says he is not afraid either of the example for you, or that you will respect him less, and I know you will not, for you will only see his truth and generosity.

L.P. T. [Lucy]

All that your mother has written is true — blessings on her! — every word of it, except that she never could, and I hope none of you ever will, understand the depth and blackness of the slough Harold Alison drew me out of by just being the man he was; nor will she show you — for indeed she is blind to it herself — that it was no other than she, with her quiet, upright sweetness and resolution, that was the making of him and of both of us. Very odd it is that a woman should set it all down in black and white, and never perceive it was all her own doing. But if you see it, young people, what you have to do is to be thankful for the mother you have got and try to be worthy of her, and if the drop of Alison blood in you should make one of you even the tenth part of what Harold was, then you’ll be your father’s pride, and much more than he deserves.

D.E. ST. G. T. [Dermot]

Thank you, dear brother, for having let me see this, though I know Lucy did not intend it for my eyes, or she would not have been so hard on poor mamma. It shows me how naughty I must have been to let her get such a notion of our relations with one another, but an outsider can never judge of such things. For the rest, dear Lucy has done her best, and in many ways she did know him better than anybody else did, and he looked up to her more than to anyone. But even she cannot reach to the inmost depth of the sweetness out of the strong, nor fully know the wonderful power of tender strength that seemed to wrap one’s mind round and bear one on with him, and that has lasted me ever since, and well it may, for he was the very glory of my life.

V.T. [Viola]

I am glad to have read it, because it explains a great deal that I was too much of a child to understand; but I don’t like it. I don’t mean for putting in the fatal thing I did in my ignorant folly. I knew that, and she has softened my wilfulness. But there’s too much flummery, and he was a hundred times more than all that. I had rather recollect him for myself than have such a ladylike, drawing-room picture; but Lucy means it well, and it is just as he smoothed and combed himself down for her. Nobody should have done it but George. He would have made a man of him.

D.Y [Dora]

As if George could have done it! A lady must always see a man somewhat as a carpet knight, and ill would betide both if it were not so. But, allowing for this, and the want of “more power to her elbow,” I am thankful to Mrs. Tracy for this vivid recall of the man to whom I and all here owe an unspeakable debt. For my own part, I can only say that from the day when I marvelled at his fortitude under the terrible pain of the lion’s bites, to that when I saw the almost unexampled triumph of his will over the promptings of a disordered brain, he stood before me the grandest specimen of manhood I ever met ever a victor, and, above all, over himself.

G.Y. [George]

Back to top of page

#### Online text ofMy Young Alcides

[Click here to reach the latest version of*My Young Alcides*online from Gutenberg](http://digital.library.upenn.edu/webbin/gutbook/lookup?num=4347)  
(Many thanks to Sandra Laythorpe and others)

