---
title: "NA"
sort_title: "NA"
slug: "old_journal_of_the_Lady_Beatrix_Graham"
format:
  html:
    toc: true
---




  
**Journal of the Lady Beatrix Graham : sister of the Marquis of Montrose.**

JOURNAL OF THE LADY BEATRIX GRAHAM -- J. M. F. Smith (= Mrs. Fowler Smith, afterwards Smith-Dampier).  
Period of Montrose and the Covenant  
Geo. Bell & Sons

**Preface by  
Yonge, Charlotte Mary, 1823-1901.  
**

**Person(s) as subject Montrose, James Graham,. Marquis of,. 1612-1650. Fiction.  
Maderty, Beatrice Graham Drummond,. Baroness,. 1615-1691. Fiction.  
**

Corporation(s) Chiswick Press  
Publication London: Bell and Daldy,  
Publication year 1871.  
Description xii, 258 p. : 19 cm.  

Athenaeum Title Record

Title : Journal of the Lady Beatrix Graham, Sister of the Marquis of Montrose  
Anonymous authors : ANON  
Contributor: DORAN, Dr. John  
Mark : DORAN  
Reference : 2264 (March 18,1871), 335 - 336

  
location library code  
CT YALE UNIV LIBR YUS  
DC LIBRARY OF CONGRESS LNN  
TX AMARILLO PUB LIBR TAP  
VT UNIV OF VERMONT, BAILEY LIBR VTU

http://www.millenicom.com/~mattc/research%20site/03-historic/peerage.htm

Peerage of Carmichael  
This ancient surname is local, and was assumed by the propiertors of the lands and barony of Carmichael, in the shire of Lanark, which has been long in the possession, and still is one of the chief seats of this noble family.

