---
title: "Old Times at Otterbourne"
sort_title: "Old Times at Otterbourne"
year: 1891
subtitle: "1891"
slug: "old_times_at_otterbourne"
format:
  html:
    toc: true
---


*1891*



NOT many of us remember Otterbourne before the Railroad, the Church, or the Penny Post. It may be pleasant to some of us to try to catch a few-recollections before all those who can tell us anything about those times are quite gone.

To begin with the first that is known about it, or rather that is guessed. A part of a Roman road has been traced in Otterbourne Park, and near it was found a piece of a quern, one of the old stones of a hand mill, such as was used in ancient times for grinding corn so that the place must have been inhabited at least seventeen hundred years ago. In the last century a medallion bearing the head of a Roman Emperor was found here, sixteen feet beneath the surface. It seems to be one of the medallions that were placed below the Eagle on the Roman Standards, and it is still in the possession of the family of Fitt, of Westley.

After the Roman and British times were over, this part of the country belonged to Wessex, the kingdom of the West Saxons, of which Winchester was the capital. Lying so near the chief town, which was the Bishop's throne, this place was likely soon to be made into a parish, when Archbishop Theodore divided England in dioceses and parishes, just twelve hundred years ago, for he died 690. The name no doubt means the village of the Otters, and even now these creatures are sometimes seen in the Itchen, so that no doubt there were once many more of them. The shapes and sizes of most of our parishes were fixed by those of the estates of the Lords who first built the Church for themselves and their households, with the churls and serfs on their manor. The first Lord of Otterbourne must have had a very long narrow property, to judge by the form of the parish, which is at least three miles long, and nowhere a mile in breadth. Most likely he wanted to secure as much of the river and meadow land as he could, with some high open heathy ground on the hill as common land where the cattle could graze, and some wood to supply timber and fuel. Probably all the slopes of the hills on each side of the valley of the Otter were covered with wood. The top of the gravelly hill to the southward was all heather and furze, as indeed it is still, and this reached all the way to Southampton and the Forest. The whole district was called Itene or Itchen, like the river. The name meant in the old English language, the Giant's Forest and the Giant's Wood.

The hill to the north was, as it still remains, chalk down. The village lay near the river and the stream that runs into it, upon the bed of clay between the chalk and the gravel. Most likely the Moathouse was then in existence, though a very different building from what it is at present, and its moat very deep and full of water, serving as a real defence. There is nothing left but broad hedge rows of the woods to the north-east, but one of these is called Dane Lane, and is said to be the road by which the Danes made their way to Winchester, being then a woodland path. It is said that whenever the yellow cow wheat grows freely the land has never been cultivated.

There was a hamlet at Boyatt, for both it and Otterbourne are mentioned in Domesday Book. This is the great census that William the Conqueror caused to be taken 1083 of all his kingdom. From it we learn that Otterbourne had a Church which belonged to Roger de Montgomery, a great Norman baron, whose father had been a friend of William I.

Well for the parish that it lay at a distance from the Giant's Wood, where the King turned out all the inhabitants for the sake of his "high deer," making it the New Forest. He and his sons could ride through down and heath all the way to their hunting. We all know how William Rufus was brought back from his last hunt, lying dead in the charcoal burner Purkis's cart, in which he was carried to his grave in Winchester Cathedral. Part of the road between Hursley and Otterbourne, near Silkstede, is called King's Lane, because it is said to have been the way by which this strange hearse travelled.

Silkstede is a farm now-it was most likely a grange, or outlying house belonging to some monastery-and there is a remnant of the gardens and some fine trees, and a hollow called China Dell, where snowdrops and double daffodils grow. But this is in Hursley parish, as is also Merdon Castle.

The green mounds and deep trenches, and the fragments of ruinous wall, have a story reaching far back into the ages.

There is little doubt, from their outline, that once there was an entrenched camp of the Romans on this ground, but nothing is known thereof. Meranturle, as our Saxon ancestors called it, first is heard of when in 755 Cynewolf, King of Wessex, was murdered there by his kinsman Cyneheard, who was in his turn killed by the Thanes of the victim. With this savage story it first appears, but no more is known of its fate except that it became the property of the Bishops of Winchester, some say by the grant of Cynegyls, the first Christian King of Wessex, others by a later gift. It was then a manor, to which Hurstleigh, the woodland, was only an appendage; and the curious old manorial rights and customs plainly go back to these ancient pre-Norman times. To go through all the thirty customs would be impossible, but it is worth noting that the tenure of the lands descended by right to the youngest son in a family instead of the eldest. Such "cradle fiefs" exist in other parts of England, and in Switzerland, on the principle that the elder ones go out into the world while their father is vigorous, but the youngest is the stay of his old age. The rents were at first paid in kind or in labour, with a heriot, namely, the most valuable animal in stock on a death, but these became latterly commuted for quit rent and fines. The trees were carefully guarded. Only one good timber tree on each holding in the life-time of a tenant might be cut by the Lord of the Manor, and the tenants themselves might only cut old rotten trees But this is as much as you will wish to hear of these old customs, which prove that the Norman feudal system was kept out of this Episcopal manor. It was not even mentioned in Domesday Book, near as it was to Winchester. There it lay, peacefully on its island of chalk down, shut in by the well-preserved trees, till Stephen's brother, Bishop Henry de Blois, of Winchester, bethought him -of turning the old Roman Camp into a fortified castle. The three Norman kings had wisely hindered the building of castles, but these sprung up like mushrooms under the feeble rule of Stephen.

The tenants must have toiled hard, judging by the massiveness of the small remnant, all built of the only material at hand, chalk to make mortar, in which flints are imbedded.

This fragment still standing used to be considered as part of the keep, but of late years better knowledge of the architecture 'of castles has led to the belief that it was part of the northern gateway tower. I borrow the description of the building from one written immediately after the comments of a gentleman who had studied the subject.

Henry de Blois, King Stephen's brother, Bishop of Winchester, probably wished for a stronghold near at hand, during his brother's wars with the Empress Maud. He would have begun by having the nearly circular embankment thrown up with a parapet along the top, and in the ditch thus formed a stockade of sharp pointed stakes. Within the court, the well, 300 feet deep, was dug, and round it would have been the buildings needed by the Bishop, his household and guards, much crowded together.. The entrance would have been a drawbridge, across the great ditch, which on this side was not less than 6o feet wide and perhaps 25 deep, and through a great gateway between two high square towers which must have stood where now there is a slope leading down from the inner court, into the southern one. This slope is probably formed by the ruins of the gateway and tower being pitched into the ditch.

The Castle was then very small, and did not command the country except towards the south. The next work therefore would be to throw out an embankment to the south, with a ditch outside. The great gap whence Hursley House is seen, did not then exist, but there was an unbroken semicircle of rampart and ditch, which would protect a large number of men. In case of an enemy forcing this place, the defenders would retreat into the Castle by the drawbridge.

The entrance was on the eastern side, and in order to protect this and the back (or northern side) of the Castle, an embankment was thrown up outside the fist moat, and with an outer moat of its own. Then, as, in case of this being carried by the enemy the defenders would be cut off from the main southern gateway, a square tower was built on this outer embankment exactly opposite to the ruin which yet remains, and only divided from it by the great ditch. On either side of the tower, cutting the embankment across therefore at right angles, was a little ditch spanned by a drawbridge, which, if the defenders found it necessary to retire to the tower, could at any time be raised. The foundations of the tower and the position of the ditch can still be distinctly traced.

Supposing farther that it became impossible to hold the tower, the besieged could retreat into the main body of the Castle by another drawbridge across the great ditch. This could lead them through the arch which can still be seen in the ruin, though it is partially blocked up. The room on the east side of this passage was probably a guard room.

These are all the remains. The embankments to the south and west command a great extent of country, and on the north and northwest, we trace the precautions by the great depth of the ditch, and steepness of the earthworks, though now overgrown with trees. All this must have been done between the years 1138 and 1154, and great part of the defences were thrown down in the lifetime of the founder.

