---
title: "A Pictorial History of the World's Great Nations"
sort_title: "Pictorial History of the World's Great Nations"
year: 1882
slug: "pictorial history of the worlds great nations"
format:
  html:
    toc: true
---


*1882*



Online and downloadable versions of[A Pictorial History of the World's Great Nations](https://archive.org/details/pictorialhistory01yonguoft/page/n13/mode/2up)are available here.

This book is not listed in the*Chaplet of Pearls*bibliography (1965)

### It is listed in Bonnie Schuster's biobibliograhy (1967) as published by Selmer Hess in New York in 1882, 1894 and 1899.

### Very possibly an American combined edition of the Aunt Charlotte's stories of  
Greek / Roman / German / French / English history, all published in the 1870's  
(and with a new section written by Doyle on US history)

### Numerous copies are available second-hand and in US libraries.  
Collating the various seller and catalogue descriptions we find:

### Vol. I: Greek, Roman and German History.  
Vol. II: German History continued (from Lothar II to Wilhelm I), French and English History (up to and including Elizabeth I).  
Vol. III: English History continued; American History (History of America by John A. Doyle)

### **Note that The United States history is by John A. Doyle, edited by E.A. Freeman.**

