---
title: "A Reputed Changeling, or, Three Seventh Years Two Centuries Ago"
sort_title: "Reputed Changeling, or, Three Seventh Years Two Centuries Ago"
year: 1889
slug: "reputed_changeling"
format:
  html:
    toc: true
---


*1889*



[Click here to reach the latest version of*A Reputed Changeling*from Gutenberg](http://www.gutenberg.org/dirs/1/2/4/4/12449/12449.txt)  
(Many thanks to David Price and others)

*(Text kindly supplied by Amy de Gruchy)*

#### Publication

#### Contents

According to superstition elves can substitute one of their own kind for an unbaptised baby, but the changeling can be exchanged for the human child at seven year intervals. Peregrine Oakshott was born the year after his mother suffered the trauma of the Great Fire of London (1666). His strange appearance caused her, the servants and other members of the family to consider him a changeling. His subsequent outrageous behaviour causes his father and tutor, stern Calvinists, to believe him predestined to damnation and possessed of an evil spirit. At the age of fourteen the despairing boy makes two attempts to return to fairyland, one involving King Charles II. He has a serious accident, and is nursed by Mrs Woodford, a gentle and pious widow from whom he receives kindness and understanding.

She and her brother-in-law, a clergyman, arrange for his transfer to the care of his uncle, a cultured and kindly diplomat, who can control him. However, as he approaches the age of twenty-one his father recalls him and at home his rebellious nature reappears. His love for Mrs Woodford is transferred to her daughter Anne, but she refuses to marry him. Just after a celebration of the acquittal of the seven bishops in 1688, his pursuit of her involves him in a duel, in which he is believed to have been killed, and his body hidden. However, he is rescued by smuggling friends, taken abroad and recovers to help in the escape from England of Mary of Modena, the queen of James II.

Peregrine becomes a Roman Catholic, but his religious practices do not help him to overcome his lower nature, as he had hoped. He spends some years plotting for the return of King James, and when he is twenty-eight kidnaps Anne Woodford, but his better nature prevails, and he frees her, though at the cost of his own life. He clears Anne's lover, his assailant in the duel, of his attempted murder, and dies reconciled to his father and Heaven, leaving Anne free to marry her lover.

Anne Woodford is a typical Yonge heroine, a basically good girl, but with a flaw in her character that requires correction. Most of her actions are well-meaning and well-judged. Her childhood love for Charles Archfield has to be overcome, for at eighteen he is married off to a spoilt childish heiress. She realises that a marriage to Peregrine would be disastrous for both of them. Charles intervenes to save her from Peregrine, and she sees the apparently fatal result of the duel, but keeps the secret, until she has to reveal all at his trial. Before that her pride and ambition had caused her to reject a safe home with the religious Lady Russell in favour of a post at the court of King James. There she becomes an upper servant, and though loyally accompanying the royal family in their exile, she is neglected and rejected on account of her religion. Charles, now a widower, declares his love for her and before departing to join the Imperial army, enables her to return to England. She has learnt her lesson, and overcome her pride, finding happiness in the care of Charles' motherless child.

There is a large cast of characters. Richard Cromwell, the son of the Protector, appears briefly, as does Charlotte Yonge's own ancestor, Dr James Yonge. In France she brings back characters from Stray Pearls, set forty years earlier, and introduces their descendants. The leading characters in A Reputed Changeling are skilfully drawn, and the minor characters are adequately shown.

The plot is ingenious, linking public events with the seven year cycles of the changeling, though with some stretching of dates. Historical happenings are accurately described, and there is a convincing picture of Hampshire life in the late seventeenth century. Most of the action is set in an area well-known to C.M. Yonge, and her detailed knowledge gives added realism to her descriptions. Religious discussion and thought are prominent, but the moral teaching is enforced through the action, and the recognition of their failings by those concerned.  

#### Further Reading

For contemporary reviews see L. Madden,*J.B. Shorthouse and C.M. Yonge*, unpublished thesis, University of London Diploma in Librarianship, 1964.

Katherine M. Briggs,*Folklore in the works of Charlotte Yonge*, Occasional papers of the KB Club, no. 1, 1990.

