---
title: "The Story of the Christians and the Moors in Spain"
sort_title: "Story of the Christians and the Moors in Spain"
year: 1878
subtitle: "1878"
slug: "story_of_christians"
format:
  html:
    toc: true
---


*1878*



[Click here for](http://www.archive.org/details/TheStoryOfTheChristiansAndMoorsOfSpain)[*The Story of the Christians and Moors of Spain*](http://www.archive.org/details/TheStoryOfTheChristiansAndMoorsOfSpain)[available to read online or to download  
(from the Internet Archive -- scanned by the State Central Library, Hyderabad)](http://www.archive.org/details/TheStoryOfTheChristiansAndMoorsOfSpain)

**Click here for a brief introduction to the*The Story of the Christians and the Moors*  
Charlotte Yonge's own preface to*The Story of the Christians and the Moors***

### **The Story of the Christians and Moors of Spain  
**London: Macmillan, 1878  
Title vignette by W. Holman Hunt

In her Preface to this History, Charlotte Yonge states that while there has been an interest in Spanish chivalry, the "eight hundred years' struggle between the Moslem and the Christian was little recollected at the present day." She continues by noting that "no one has tried to combine in a general view Spanish and Moorish history, together with tradition, romance, and song."

Her work begins with a table of the Moorish, Castilian, and Aragonese sovereigns, followed by an introduction to the geography of the country whch contrasts the rugged mountainous northern section with the open Southern areas.

She then describes the history from ancient times up to 1611.

### **Charlotte Yonge's own Preface to***The Story of the Christians and the Moors*********

IN the earlier times of the awakening of romance in modern days, Spanish chivalry was the fashion. Scott and Southey both did their parts in making it known; and the fantastic honour and dauntless bravery of the Castilian knight were favourite subjects; so that Washington Irving in America, and Herder in Germany, were alike inspired with the same enthusiasm. Modem criticism on the one hand, and modem persiflage on the other, have done their part to discredit these legends. Research has shown the small foundation on which stood some of the favourite stories, and then they have been parodied and laughed at. Perhaps Babieca is more familiar as the horse of Don Fernando Gomezales than of the Cid; and even Don Quixote has been so far forgotten that there has been little inclination to seek out either the facts or the fictions that formed his character.

Thus it has seemed to me that the eight hundred years' struggle between the Moslem and the Christian was little recollected at the present day; nor, indeed, could I find its history, romance, and poetry anywhere brought into combination. Viardot has admirably written the Moorish history, and Dozy has brought microscopic research to bear upon it; but they take history alone, and from the Moorish side. Dunham's is a very good English complete history of Spain, full of matter, but many-volumed and almost forgotten; and Lady Callcott's stands nearly alone as a short popular history of great excellence.

Washington Irving has dealt with the romance of the Arab conquest, Southey with the Cid, Lockhart with the ballad lore, Perez de Hyta with the civil wars of Granada; but, as far as I have seen, no one has tried to combine in a general view Spanish and Moorish history, together with tradition, romance, and song. It is a presumptuous effort, only properly to be carried out by one with as much access to original documents and private knowledge as Mr. Ford, to whose handbook I am much indebted; but he is out of sympathy with the spirit of the Spaniards, and more inclined to dwell on their evil qualities than · their good ones. This, then, is only a compilation to give a surface idea of that strange warfare, and which may, perhaps, give a hint of unexplored fields of wondrous interest.

Where it has been possible, I have availed myself of existing translations of Spanish poetry.

Having no knowledge of Arabic, I am afraid the names of the Moorish princes may not be always correctly spelt, as authors vary a good deal in their mode of expressing them.

C. M. YONGE.

May 31st, 1878.  


