---
title: "The History of the Life and Death of the Good Knight Sir Tom Thumb"
sort_title: "History of the Life and Death of the Good Knight Sir Tom Thumb"
slug: "thomas_thumb"
format:
  html:
    toc: true
---




[Online text of: The History of Sir Thomas Thumb](http://books.google.com/books?vid=OCLC01212279&id=3ErmsfmqA0QC&printsec=copyright&dq=%22charlotte%2Bmary%2Byonge%22)

A (rather spotty!) Google scan of an 1855 edition stamped "Harvard College Library from the bequest of Evert Jansen Wendell 1918". Bookplate Harvard College Library ... bought from the fund bequesthed by Evert Jansen Wendell class of 1882 of New York.

PDF version available for download from the Google webpage.

#### Tom Thumb in the Arthurian Tradition

#### A project by Susan Bauer of the University of Rochester

#### Susan's impressive work on the Tom Thumb story includes the following:

An[essay](http://www.lib.rochester.edu/camelot/TTEssay.htm)on the various versions of Tom Thumb:

In Charlotte Mary Yonge's 1856 adaptation, Tom's elfin size causes his aunt to suspect him of demonic possession. Throughout the narrative he must resist his mischievous nature and numerous temptations by the impish elf Puck, who offers to help Tom out of his various mishaps if Tom would only admit to his elfin nature. Tom steadfastly refuses to do so. While recovering in Fairyland, he renounces his ties with the fairies, declares that he is a "Christian man", and demands to be returned to Earth in order to help Arthur fight Mordred's rebellion. Upon Tom's return, the rebellion is over, Mordred is dead and Arthur dying. Tom returns to Caerleon and agrees to escort Guinevere to a nunnery as his last duty as a knight of the Round Table. When he sees a spider's web around Arthur's chair at the Round Table, he tries to remove it but the devious spider weaves a web around Tom, binding him hand and foot. Puck, once again, offers to help Tom if he will admit to his own impish nature and return to fairyland. Tom refuses, preferring to die as an honorable Christian.

Detailed[primary and secondary bibliographies](http://www.lib.rochester.edu/camelot/TTBib.htm)of the Tom Thumb story including this on Yonge's novel:

A moralistic slant is given to this adaptation in which Tom must resist his own mischievous nature in order to perform his duty. He is tempted and mocked by the impish Puck who offers to help him out of his various mishaps if Tom will admit to his elfin nature, which Tom steadfastly refuses to do. It also combines Arthurian tales with the story of Tom Thumb. Tom leaves his parents to go to Caerleon and seek his fortune. There, he becomes a favorite of the court. His loyalty and courage are rewarded when King Arthur knights him. He assists King Arthur in solving Dame Ragnelle's riddle, but when Tom learns of Mordred's planned rebellion, he is seriously wounded by Mordred and taken to Fairyland to recover. Puck again tries to convince Tom to stay in Fairyland rather than returning to Earth. Tom refuses, insisting that he is a good Chrisitan man and will do his duty. However, upon his return, Tom finds Arthur mortally wounded. After Arthur's death, he agrees to escort Guinevere to a nunnery as his last duty as a knight of the Round Table. On the night before they were to leave, Tom is incensed at the sight of a spider web on King Arthur's chair. While he tries to remove the web, the spider weaves another around him. Bound hand and foot in the spider's web, Tom is tempted one last time by Puck, who offers to free him if he will acknowledge his own impish nature. Tom refuses, preferring to die an honorable Christian death.

[Illustrations](http://www.lib.rochester.edu/camelot/TTImages.htm)**from many versions including those by Jemima Blackburn's (1823-1909) for Yonge's 1855 edition.**

### Contemporary Reviews

### Putnam's Monthly 1857

#### VOL. IX JANUARY 1857 No. XLIX page 94

Among the fascinating holiday juveniles, we must not forget the handsome illustrated quarto*Tom Thumb*, by the author of the*Heir of Redclyffe*. (Dix, Edwards & Co.) The exhaustless charm of the old story Is increased rather than diminished in this new form. It deals with the purest romance; takes us back to the cheerful round-table and the bright days when good King Arthur ruled the land; and gives the child a hundred happy fancies which last as long as life.

While so many able minds are employed upon new and good books for children, we are glad to see the charming talent of Miss YONGE devoted to this old and good story. We have no fear that children will learn too much; so that we are in no degree jealous of the sciences made easy, which are so constantly offered them. We are very sure that nobody knows what the young people want so well as the young people themselves; and they are not to be put off with any dullness; therefore, they will always love Tom Thumb, and everybody who tells his story well.

### *Notes and Queries*1856

[*Notes and Queries*1856](http://www.bodley.ox.ac.uk/cgi-bin/ilej/image1.pl?item=page&seq=1&size=1&id=nq.1856.1.5.1.1.x.19)Vol. 1, 2nd Series, January 5 1856, page 19.

The fair authoress of the Heir of Redclyffe has given us, what was greatly to be desired, a most genuine, veracious, and agreeable*History of the Life and Death of the Good Knight Sir Thomas Thumb with divers other Matters concerning the Court of Good King Arthur of Britain*. The book has been illustrated by that cunning artist J.B., whose*Photographic Illustrations of Scripture*, last year, excited no much attention and admiration in the world of Art. It seems doubtful whether the book was written to the pictures or the pictures made to fit the book; but they do fit most admirably, and Miss Yonge bids fair to be the Macaulay of Fairy Land.

This lady must, however, look to her laurels. There is another Richmond in that field, which she has almost made her own.*Claude de Vesci a Tale, in two volumes*, is a now and interesting story of the*Heir of Redclyffe*school written with very considerable talent; although some lady readers may. perhaps, find it deficient in that peculiar interest which depends upon the prominence given to a heroine.

