---
title: "Two Penniless Princesses - Charlotte Mary Yonge"
year: 1891
slug: "two_penniless_princesses"
format:
  html:
    toc: true
---


#### Online text of Two Penniless Princesses

[Click here to reach the latest version of*Two Penniless Princesses*from Gutenberg](http://digital.library.upenn.edu/webbin/gutbook/lookup?num=2942)  
(Many thanks to Sandra Laythorpe and others)

### Publication details, summary and further reading for*Two Penniless Princesses*

(Kindly supplied by Amy de Gruchy)

#### Publication

January - December 1890, serialized in[*The Monthly Packet*](monthly_packet.qmd), editor C.M. Yonge, publishers Walter Smith and Innes.  
1891, published by Macmillan

####   
**Contents**

The tale is a sequel to C.M. Yonge's earlier historical novel, The Caged Lion. It commences in the year 1446, nine years after the murder of James I of Scotland, the caged lion, and the two penniless princesses, his younger daughters Jean and Eleanor, are now sixteen and seventeen. Various warring nobles seek to marry them, to strengthen their own positions. Their brother King James, and his council decide to send them to their elder sister, the wife of the Dauphin of France. They are escorted by Sir Patrick and Lady Lilias Drummond, fictitious characters from The Caged Lion, and accompanied by George, the son of Earl Douglas, disguised as a man at arms, who loves the beautiful wayward princess Jean.

The group travel first to England, encountering much pomp, pageantry and luxury, in contrast to the bleakness of life in Scotland. They also meet many leading historical figures. In France it is the same, but the girls are made aware of the unhappiness of their sister whose love for her husband, the Dauphin, is returned by scorn and dislike. Soon, by the connivance of their sinister brother-in-law, the princesses are kidnapped by a robber baron and taken to his almost impregnable castle. They are rescued by their two suitors, Jean's faithful Scot and Eleanor's Austrian Archduke, both experienced cragsmen, who scale the walls of the castle and bring them back safely to France. There, their joy is turned to grief, for their sister has died. However Jean marries George Douglas, and Eleanor her Archduke, so the tale ends on a happy note.

Until the princesses are kidnapped the plot is slow-moving and interest is mainly maintained by the interaction between the characters. This is well shown in the relationship between the arrogant beautiful Jean and the gentle talented Eleanor whose gift for second sight is socially embarrassing for her, but informative for the reader. The historical characters are well drawn. Of the fictitious ones, Lady Lilias Drummond strongly resembles another Lilias, Lady Merrifield of*The Two Sides of the Shield*(1884-1885) and other tales of contemporary life. Her husband Sir Patrick has developed from an impetuous youth to a statesmanlike figure, but other characters from The Caged Lion remain unchanged.

The historical information is generally accurate, and in places shows little known aspects of mediaeval life. The aim of the tale seems to have been to inform. There is no overt moral teaching.

####   
**Further reading**

For contemporary reviews see L. Madden,*J.B. Shorthouse and C.M. Yonge*, unpublished thesis, University of London Diploma in Librarianship, 1964.

