---
title: "The Two Sides of the Shield - Charlotte Mary Yonge"
year: 1885
slug: "two_sides_of_the_shield"
format:
  html:
    toc: true
---


### Online text of**The Two Sides of the Shield**

It is sometimes treated as an impertinence to revive the personages of one story in another, even though it is after the example of Shakespeare, who revived Falstaff, after his death, at the behest of Queen Elizabeth. This precedent is, however, a true impertinence in calling on the very great to justify the very small!

Yet many a letter in youthful handwriting has begged for further information on the fate of the beings that had become favourites of the school-room; and this has induced me to believe that the following out of my own notions as to the careers of former heroes and heroines might not be unwelcome; while I have tried to make the story stand independently for new readers, unacquainted with the tale in which Lady Merrifield and her brothers and sisters first appeared.

'Scenes and Characters' was, however, published so long ago, that the young readers of this generation certainly will only know it if it has had the good fortune to have been preserved by their mothers. It was only my second book, and in looking back at it so as to preserve consistency, I have been astonished at its crudeness.

It will explain a few illusions to state that it is the story of the motherless family of Mohuns of Beechcroft, with a kindly deaf father at the head, Mr. Mohun, whose pet name was the Baron of Beechcroft, owing to a romantic notion of his daughters made fun of by his sons. The eldest sister, a stiff, sensible, dry woman, had just married and gone to India, leaving her post to the next in age, Emily, who was much too indolent for the charge. Lilies, the third in age, with her head full of the kind of high romance and sentiment more prevalent thirty or forty years ago than now, imagined that whereas the household had formerly been ruled by duty, it now might be so by love. Of course, confusion dire was the consequence, chiefly with the younger boys, the scientific, cross-grained Maurice, and the high-spirited, turbulent Reginald, all the mischief being fomented by Jane's pertness and curiosity, and only mitigated by the honest simplicity and dutifulness of eight years old Phyllis. The remedy was found at last in the marriage of the eldest son William with Alethea Weston, already Lilias's favourite friend and model.

That in a youthful composition there should be a cavalier ancestry, a family much given to dying of consumption, and a young marquess cousin is, perhaps, inevitable. Lord Rotherwood was Mr. Mohun's ward, and having a dull home of his own, found his chief happiness as well as all the best influences of his life, in the merry, highly-principled, though easy-going life at his uncle's, whom he revered like a father, while his eager, somewhat shatter-brained nature often made him a butt to his cousins. All this may account for the tone of camaraderie with which the scattered members of the family meet again, especially around Lilias, who had, with her cleverness and enthusiasm, always been the leading member of the group.

It should, perhaps, also be mentioned that Lord Rotherwood's greatest friend was also Lilias's favourite brother, Claude, who had become a clergyman and died early. Aunt Adeline had been the spoilt child and beauty of the family, the youngest of all.

C. M. YONGE.

March 8th, 1885.  


