---
title: "The Two Guardians, or, Home in this World - Charlotte Mary Yonge (1852)"
sort_title: "Two Guardians, or, Home in this World - Charlotte Mary Yonge (1852)"
year: 1852
slug: "two_guardians"
format:
  html:
    toc: true
---


*1852*



### **  
Online text of**The Two Guardians****

[Click here to reach*The Two Guardians*fromthe Internet Archive (opens in a new tab)](https://archive.org/details/twoguardiansorho00yong/page/n3/mode/2up)  

[Click here to reach*The Two Guardians*from Making of America books](http://www.hti.umich.edu/cgi/t/text/text-idx?type=simple&c=moa&sid=972085c35c7a4713eda22d43683789ee&q1=yonge&rgn=full%20text&firstpubl1=1800&firstpubl2=1925&view=header&cc=moa&idno=ABK2822.0001.001)  

#### Charlotte Yonge's own Preface toThe Two Guardians, or Home in this World

IN putting forth another work, the Author is anxious to say a few words on the design of these stories; not with a view to obviate criticism, but in hopes of pointing to the moral, which has been thought not sufficiently evident, perhaps because it has been desired to convey, rather than directly inculcate it.

Throughout these tales the plan has been to present a picture of ordinary life, with its small daily events, its pleasures, and its trials, so as to draw out its capabilities of being turned to the best account. Great events, such as befall only a few, are thus excluded, and in the hope of helping to present a clue, by example, to the perplexities of daily life, the incidents, which render a story exciting, have been sacrificed, andi the attempt has been to make the interest of the books depend on character painting.

Each has been written with the wish to illustrate some principle which may be called the key note. "Abbeychurch" is intended to show the need of self-control and the evil of conceit in different manifestations, according to the various characters. "Scenes and Characters" was meant to exemplify the effects of being guided by mere feeling, set in contrast with strict adherence to duty. In "Henrietta's Wish" the opposition is between wilfulness and submission—filial submission as required in the young people, and that of which it is a commencement as well as a type, as instanced in Mrs. Frederick Langford. The design of the "Castle Builders" is to show the instability and dissatisfaction of mind occasioned by the want of a practical, obedient course of daily life; with an especial view to the consequences of not seeking strength and assistance in the appointed means of grace.

And as the very opposite to Emmeline's feeble character, the heroine of the present story is intended to set forth the manner in which a Christian may contend with and conquer this world, living in it but not of it, and rendering it a means of self-renunciation. It is therefore purposely that the end presents no great event, and leaves Marian unrecompensed save by the effects her consistent well doing has produced on her companions. Any other compensation would render her self-sacrifice incomplete, and make her no longer invisibly above the world.

October 14th, 1852.

