---
title: "What Books to Lend and What to Give - Charlotte Mary Yonge (1884)"
year: 1887
slug: "what_books_to_lend"
format:
  html:
    toc: true
---


'So exciting and engrossing that it must be mentioned, but bringing the reader into rough company, among a good many horrors.'

(Yonge, writing about R. L. Stevenson's*Treasure Island*)

### Online text of***What Books to Lend and What to Give***from the Internet Archive (opens in new tab)

### *  
*

### [Click here to read or download](https://archive.org/details/whatbookstolendw00yong/page/n5/mode/2up)

Contents list for***What Books to Lend and What to Give***

SENIOR CLASSES

Charlotte Yonge's Introduction to***What Books to Lend and What to Give***

WHOLESOME and amusing literature has become almost a necessity among the appliances of parish work. The power of reading leads, in most cases, to the craving for books. If good be not provided, evil will be only too easily found, and it is absolutely necessary to raise the taste so as to lead to a voluntary avoidance of the profane and disgusting.

Books of a superior class are the only means of such cultivation. It has been found that where really able and interesting literature is to be had, there is much less disposition to prey upon garbage. And the school lessons on English have this effect, that they make book-language comprehensible far more widely than has hitherto been the case.

A library is an almost indispensable adjunct to a school, if the children are to be lured to stay at home instead of playing questionable games in the dark, or by gaslight, out of doors; and an amusing story is the best chance of their not exasperating the weary father with noise. If the boy is not to betake himself to 'Jack Sheppard' literature, he must be beguiled by wholesome adventure. If the girl is not to study the 'penny dreadful,' her notions must be refined by the tale of high romance or pure pathos.

The children at school are often eager readers, especially if they have sensible parents who forbid roaming about in the evening. There ought always to be a school library unless the children are provided for in the general parish library; but even this requires careful selection. Weak, dull, or unnatural books may be absolutely harmful when falling into rude or scornful hands. For instance, a country lad should not have a book where a farmer gives a prize for climbing an elm-tree to take a blackbird's nest, such a proceeding being equally against the nature of farmers, blackbirds, and elms. Seafaring lads should not have incorrectly worded accounts of wrecks; and where more serious matters come in, there should be still greater care to be strong, true, and real. Boys especially should not have childish tales with weak morality or 'washy' piety; but should have heroism and nobleness kept before their eyes; arid learn to despise all that is untruthful or cowardly and to respect womanhood. True manhood needs, above all earthly qualities, to be impressed on them, and books of example (not precept) with heroes, whose sentiments they admire, may always raise their tone, sometimes individually, sometimes collectively.

Men, however, must have manly books. Real solid literature alone will arrest their attention. They grudge the trouble of reading what they do not accept as truth, unless it is some book whose fame has reached their ears, and to have read which they regard as an achievement.

Where grown men are subscribers to a library, it should have standard works of well-known reputation.

Travels, biographies, not too long, poetry, histories of contemporaneous events, and fiction of the kind that may be called classical, should be the staple for them. It is hardly advisable to attempt to give a list for them. Their books belong to general literature, with which I do not wish to meddle, and besides, reading men mostly inhabit towns where there are generally Institutes from which they can obtain books. In the country, when the clever cobbler or gardener soars above the village library, he will generally have a decided notion of what he wants, and will respect a special loan from our own shelves. He may take to some line in natural science, or have some personal cause for interest in a colony; but in general, the labourer would rather smoke than read in his hours of rest, and even when laid aside in a hospital, newspaper scraps pasted into a book are often more welcome to him than more continuous subjects. Above all, he resents being written down to or laughed at; and calling him Hodge and Chawbacon is the sure way to alienate him.

Books with strong imitations of dialect are to be avoided. They are almost unintelligible to those who know the look of a word in its right spelling, though they might miscall it, and do not recognise it when phonetically travestied to imitate a local dialect, as for instance by ah for I. Moreover, they feel it a caricature of their language, and are very reasonably insulted. They do not appreciate simplicity, but are in the stage of civilisation when long words are rather preferred, partly as a compliment, partly as a new language. Complicated phrases are often too much for them, but polysyllables need not be avoided, if such are really needed to express an idea, and will do it better than any shorter word.

Though men either read with strong appetites or not at all, their wives, in these days of education, generally love fiction They do not want to be improved, but they like to lose their cares for a little while in some tale that excites either tears or laughter. It is all very well to say that they ought to have no time for reading. An industrious thrifty woman has little or none, but the cottager's wife who does as little needlework, washing, or tidying as possible, has a good many hours to spend in gossip or in reading. She may get cheap sensational novels, and the effects on a weak and narrow mind are often very serious. The only thing to be done is to take care that she has access to a full supply of what can do her no harm, and may by reiteration do her good, though the links between book and action are in man cases never joined. Sometimes they are not connected at all, sometimes a strong impression is unexpectedly made. But this class of women must have incident, pathos, and sentiment to attract them. The old-fashioned book where Betty rebukes Polly in set language for wearing a red cloak instead of a grey one, and eating new bread instead of old, will meet with no attention. But if the moral of the tale be sound, and the tone of the characters who bespeak sympathy, high, pure, and good, the standard of the reader, however frivolous, must be insensibly raised. At any rate, by withholding books because the cottage woman ought to be too busy to want them, we do not render her more industrious, but we leave her exposed to catering for herself in undesirable regions.

There remain the thrifty, sensible, good women who, if they read at all, do so in their Sunday leisure, and like a serious book. Neither variety of woman likes a book manifestly for children lent to themselves, though they do enjoy anything about a baby from the maternal point of view.

There are such different degrees of intelligence and civilisation among the women who frequent mothers' meetings that it is difficult to make suggestions applying to all. Some of these meetings are attended so irregularly that it is not possible to read anything continuous, whereas in others a sustained interest promotes regularity. A little religious instruction or exhortation, a little domestic or sanitary instruction, and a lively or pathetic narrative seem to answer best, and I have endeavoured to collect the titles of books useful in this respect. The two first, however, are best given extempore if a clergyman will come for the first, and a lady who has attended ambulance classes can be secured for the second.

The lad or young man species comes next. There are a few of these with a thirst for information, and it is important to supply this in a sound and wholesome form. Some like poetry, but the general run can only be induced to read at all by adventurous or humorous tales.

Those who act as Sunday school teachers may, however, be led to study books bearing on the subjects they have to teach, or to get up for certificates, and thus ma y be brought to take an interest in religious literature, which may deepen as they grow older.

There is always, too; a certain proportion who have a strong turn for fact, and like to have solid truth before them. Of course all these can read the same books as the elder men, and even more difficult ones, as their education has gone farther ; but they need more that is light, easy, and inviting, and a lending-library or reading-room requires a supply fitted for both.

It is a pity there is not more good biography suited for this purpose. The popularity of Miss Marsh's 'Hedley Vicars' showed what a book written without too much detail and with general interest might be. Some of Smiles's biographies come near the mark, also some American ones, and those shilling books of Cassell's called 'The World's Workers,' also some published by Nelson and by Blackie.

Good books of travels, too, are increasing favourites; also such books as 'Her Majesty's Mail,' and 'Engine-Driving Life.' In fact, whatever wholesomely interests our own households may well be sent into the club-room, provided it do not presuppose too much culture. Many of these books may be bought second-hand at a cheap rate from the Libraries. And there should be a good stock of standard fiction: Scott, Dickens, Fenimore Cooper, are all to be had at almost any price, and would pretty well supply in themselves the requirements of reading-room fiction.

The corresponding class of girls and young women are for the most part indiscriminate devourers of fiction, and, like the women before mentioned, need to have their appetite rightly directed. But there is more hope of them than of their elders, and their ideal is capable of being raised by high-minded tales, which may refine their notions. The semi-religious novel or novelette is to them moralising put into action, and the most likely way of reaching them.

We must not be too hasty to condemn their frivolous tastes. Whether in business or in service, they are tired, the book is recreation, and they cannot be expected to want to improve themselves when their brains and bodies are alike weary. Still we can supply them with books that will not give them false views of life, and that will foster enthusiasm for courage and truth, make vulgarity disgusting, and show religion as the only true spring of life. Through classes for Sunday teachers, and Communicants' or Bible classes, some spirit of religious study may be infused.

As to secular self-improvement, the students will always l)e few and far between, and the experience of most libraries is that there is little or no demand for improving books. So much is taught that there is little inclination to learn. A reaction sometimes comes to men, but seldom to women, whose home industries and occupations necessarily absorb them so that their reading must be either devotional or recreative.

Thus there is very little call for improving books in the lending library, in proportion to those meant for recreation; but I would urge that they should be used for prizes. At present, the usual habit is to choose gay outsides and pretty pictures, with little heed to the contents, but it should be remembered that the lent book is ephemeral, read in a week and passed on, while the prize remains, is exhibited to relatives and friends, is read over and over, becomes a resource in illness, and forms part of the possessions to be, handed on to the next generation. Therefore, after the infant period, the reward book should generally be of some worthiness, either religious, improving, or at least standard fiction. Weakness and poverty of thought should be avoided, especially as these books may fall into the hands of clever, ungodly men, and serve to excite their mockery. It should be remembered that the child to whom the book is given will not always remain a child, and therefore that it is better to let the new and cherished possession go beyond its present level of taste or capacity.

The elder lad, whose schooldays are over, sometimes begins to waken to intelligence, and to be ready to seek information, in some cases being glad of really deep reading on scientific, political, or theological subjects, and it is all-important to preoccupy his mind with sound views before he meets with specious trash. Many indeed both of lads and men are absorbed in actual practical life and never read at all, or nothing but newspapers. Yet even these when laid low by illness will accept a book. to pass away the weary hours.

Nothing, of course, can equal the effect of personal influence, from schoolmaster, clergyman, or lady, but each of these may find books, lent, recommended, or read aloud, of great assistance.

Some books of advice deprecate reading aloud in Sunday schools. My own experience, now of many years, is that it is of great assistance in impressing the scholars, and gives great pleasure. I have been told of my old pupils mentioning it as one of the enjoyments of their younger days; and when a part of a story has been missed by absence, the connection is eagerly supplied by the listeners who have been present. Moreover, those books in the lending library are always most sought after which have been read aloud, and sometimes elucidated, either at the Sunday school or at the mothers' meeting. But books for this purpose must be carefully selected, with a view to the capacities and tastes of the listeners, and be read really well and dramatically, watching the eyes of the hearers-a rapid or monotonous utterance is almost useless, and inattention leads to bad habits.

There is no reason against giving tales about persons in different stations of life from that of those who receive them, and in fact they are often preferred; but it is as well to avoid those that deal with temptations or enjoyments out of reach of the school-child; or which dwell on beauty, finery, dainties, or any variety of pomps or vanities as delights of wealth or rank. The enjoyment that authors have in describing a lovely, beautifully-dressed child in a charming attitude should be sacrificed in writing for children of any rank, unless they are to learn vanity and affectation, or else be set to covet such pleasures.

It is curious to find how many stories have become obsolete. Not only have the tales where vanity is displayed by wearing white stockings and

become archaic; but the stories of the good children who are household supports and little nurses, picking up chance crumbs of instruction, have lost all present reality such as the younger and less clever children require.

Elder ones, if they have any imagination, prefer what does not run in the grooves of their daily life, and some are much more willing to listen to, or to read, what is not too obviously written for them. A book labelled 'A tale for-' is apt to carry a note of warning to the perverse spirits of those to whom it is addressed.

Historical tales and those of other lands require a certain degree of cultivation and imagination, to be appreciated. To some, even the best are distasteful, to others they supply the element of romance. Those that have a charm about them of character and adventure, fitting them for almost all readers, have been put into the groups intended for the age they suit, as well as into their places as illustrations of history.

I endeavour to give here a classified list that may be an assistance in the choice of books. It is not an advertisement. Most of the books I have personally proved. No doubt many readers will be disappointed at omissions, but it is quite impossible to answer for all the books in existence, and my object here is to suggest the fittest for the purposes of lending, reading aloud, or giving, it is no condemnation of a work that its name does not appear in this list-only it has either not become known to me, or has not appeared to me so eminently desirable as the others.

The lists of books in the present work have been drawn up in different gradations, a great number of them having been actually proved by reading aloud. There are many very fairly suitable for lending, not equally good for reading aloud, as lengthiness, description, and over-moralising, hang on hand with a mixed class; and, in other cases, the reader seems to be inculcating with authority all that is uttered, and thus gives a sense of preaching instead of amusing.

The tales that have any dissenting bias, or which appear to involve false doctrine, are of course omitted, though all those here mentioned do not belong to the same school of thought within the Church.

The classified list then includes hooks for

*Little Ones*.— Fit to be read or given to children from four to eight.  
*Junior classes.*— Children from seven or eight to ten or eleven.  
*Senior Classes.*— From ten upwards.  
*Boys.*— The books may be read by girls also, but most boys will not read girls' books, therefore their literature is put separately.  
*Drawing Room Stories.*— The best are mentioned here, but all, though excellent, are, on experience, out of the ken of the school child.

It should be clearly understood that nobody is urged to have anything like all the books here mentioned, but that the object is to answer the oft-recurring question-Where shall I find a book suited for such and such a purpose?

I have added a few suggestions of extracts for penny readings, but it is not easy to collect enough that do not verge on buffoonery, or that have no element of vulgarity; and indeed there is so much variation of tastes according to the tone and training of the audience, that it is hardly possible to tell what will be suited for hearers of each degree of culture. Some delight in pathos or adventure, and others will do nothing but laugh, and become noisy at anything that is not highly comic. Such books for the purpose as I have seen, between difficulty about copyright and desire of novelty and drollery, do not avoid vulgarity. N.B.-It is advisable to inspect thoroughly everything offered by volunteers for reading, recitation, or singing.

It has, however, been thought better not to enter upon the tracts and sermons, such as a parish priest or district visitor would give for private use or specific purpose, as they are devotional, and scarcely to be spread broad-cast by the Library. Every librarian must cater for his own clients according to their tastes and needs. No doubt much is here left out that will be found useful in some places, but the attempt has been made to offer suggestions, and to collect, from various quarters, names that may serve to assist in the selection of books for the various needs of a parish.

