---
title: "Charlotte Mary Yonge Fellowship - Works available on-line"
slug: "works_on_line"
format:
  html:
    toc: true
---


#### Miss Yonge's books on the Internet

MISS YONGE'S books are now being published on the Project Gutenberg site on the Internet.

The books are available free for anyone in the world to download; you just need a computer with Internet access. When you have them downloaded, you can read them on the computer screen (uncomfortable), print them onto paper (expensive), or do as I have done – buy an electronic book, so you can read them in an armchair or in bed.

The Project Gutenberg site exists to publish works of literature on the Internet. It was founded by Michael Hart in the 1970s, and now has thousands of books available. Most are in English, but there are increasing numbers of foreign language books and technical books. The website is at:[http://www.promo.net/pg](http://www.promo.net/pg).

The address takes you to the search page, where you can enter the name of the author or the title of the book you want to look for. All the files are published in a very simple format: they download as text files and can be stored on the simplest computer. WinZip files are also available. Voluntary workers contribute to the site; there are about 6000 of us working on many different authors and texts. I have done a number of the Yonge titles now available, while my colleague, David Price, has contributed others.

The actual work of publishing the books begins with buying (or borrowing) old books that are no longer copyright. The book to be published is placed on a scanner, which takes a photograph of the pages – I do two pages at once. Then the photographic image is taken into a computer program, which is able to "read" the text by looking at the marks on the photograph and converting them into letters. When the result is obtained, I can read it on the screen, and compare it with the text in the book, and alter any mistakes. Then I convert the text into the format suitable for publishing on the Internet, Each double page takes about 20 minutes, depending on how good the original printed text was. When I have done the whole book, I send it to another volunteer who adds some extra text about the Gutenberg site, and he publishes it.

I also publish the text on my own web-site. I have created some web pages for Miss Yonge. At[http://www.menorot.com/cmyonge.htm](http://www.menorot.com/cmyonge.htm)you can find a biography, some photographs of Otterbourne, including the house where she was born, and a list of books I intend to publish. There are links on this page to the book files.

At the moment I have about thirty of her books, but when I have worked through them, I may be asking members of the CMY Fellowship to lend copies I have been unable to obtain.

If you would like further details about anything in this article, please[click here](contact_form.qmd)to contact me via the website contact form.

SANDRA LAYTHORPE

