---
title: "Young Stepmother: a Chronicle of Mistakes"
year: 1861
slug: "young_stepmother"
format:
  html:
    toc: true
---


#### Online text ofThe Young Stepmother

Click here for the latest version of*[The Young Stepmother](https://www.gutenberg.org/ebooks/5843)*online from Gutenberg  
(Many thanks to Sandra Laythorpe and others)

### From*The Young Stepmother*

"After all, childhood, if not the happiest, is the saddest period of life – pains, griefs, petty tyrannies, neglects, and terrors have not the alleviation of the experience that 'this also shall pass away'; time moves with a tardier pace, and in the narrower sphere of interests, there is less to distract the attention from the load of grievances".

With thanks to**Lesley Hall**for this quotation.

### Publication details, summary and further reading

Text kindly supplied by Amy de Gruchy,  
and prepared for the website by Esther McGilvray

Publication

April 1856 - December 1860 serialised in*The Monthly Packet*, published by John and Charles Mozley.  
1861 Published in book form by Parker and Son.  

Summary of Contents

#### 1. The Two Versions

C. M. Yonge always revised her serials for book publication, often considerably. Thus the book versions of The Daisy Chain and The Little Duke follow the main characters into adult life, the former doubling in length as a result. Grammatical and stylistic faults in all the serials were corrected: numerous errors of fact in the historical tales and contradictory statements in the contemporary ones were removed. Some historical, moral and religious propaganda was softened or excised: many descriptions and incidents were shortened or omitted altogether. The alterations vary in number between 8 and approximately 3,500 per serial of which The Young Stepmother had the greatest number.

The resulting book was between two thirds and three quarters of the length of the serial. Many of the cuts were necessary. Hundreds of awkward phrases were shortened. Thus 'not at all listened to' in the serial becomes 'disregarded' in the book. Unnecessary detail was removed, and fictitious dates removed, although many discrepancies remained.

However, the cuts were too drastic. The serial is diffuse and very badly written, but it is a richer and more complex work than the book.

The structure was weakened by the removal of various contrasts and parallels and the striking use of past memories which had helped to write the novel. More importantly the excision of much material about Sophie, the younger stepdaughter, makes her a less prominent character than her brother, so that in the book there is a hiatus after his death, and the switch to her concerns, though skilfully managed, seems somewhat contrived.

Characters lose some of their complexity, particularly those of the heroine, her husband and Sophie. Many minor characters shrink in importance or become mere names. The townspeople lose their choric role. Removal of much material about the slums over-simplifies the problems they present and weakens the ambiguity of the response of the major characters.

The book that resulted is a neater work than the serial, but a less powerful one. It is generally classed as one of C. M. Yonge's minor novels.

#### 2. Relevance

Both versions, but particularly the serial are of interest to the modern reader, having a noticeably feminist angle and dealing realistically with the problems of a second marriage and family and of urban deprivation. There is considerable humour and an awareness of the complexity of social and personal issues.

#### 3. The Plot

The heroine, Albinia Ferrars leaves her happy home with her Tractarian clergyman brother and his family to marry Edmund Kendal, a widower fifteen years older than herself with three surviving children. She assumes that her task in life will be to cheer and encourage her husband and be a loving stepmother to his children.

However she quickly finds additional tasks and formidable obstacles. Her husband is depressed, inert and remote, his children sickly and difficult, their maternal relations are suspicious of her, and like her other neighbours, ignorant, narrow and hostile to change. Her new home is gloomy and unhealthy and is close to a noisome slum from which had emanated the fever that killed Kendal's first wife and his favourite son. A grasping attorney administers the slum tenements on behalf of the landlord, who turns out to be Albinia's stepson Gilbert, while Mr Kendal himself has a life interest in the properties. The hearty Tractarian clergyman has few supporters in the town.

Albinia tackles all these problems and many others, though with more zeal than judgement, but after a few years things seem to have improved. However it is the calm before the storm. The step-children's unfortunate tendencies, apparently cured, return in adult form, and they fall in love with disastrous results. Albinia's own son is almost out of control. When a final solution is found for the slums the inhabitants respond with understandable violence.

At the close of the novel Albinia laments her errors, but her wise clergyman brother reassures her. Nevertheless the last words are hers, and they are ambiguous.

#### 4. The Theme

C. M. Yonge's fiction often has a subtitle which expresses the theme on moral teaching. The subtitle of The Young Stepmother (not found in the serial) is A Chronicle of Mistakes, and the heroine's errors of judgement are indeed censured in both versions. However the word 'illusions' better expresses the theme, for the novel is largely concerned with various illusions and misapprehensions, and the resultant mistakes and blunders and their effect on the characters and the environment.

The plot is set in motion by three illusions of Edmund Kendal. He marries young a beautiful girl from a narrow provincial background, but the happiness of his first marriage is an illusion (C. M. Yonge's word) based on the belief that all women are as dull and ignorant as his wife, and that no intellectual companionship can be expected of them. He also believes that he can enjoy peace and happiness pursuing learning while neglecting his family, social and religious responsibilities, and so loses his wife and favourite son. The novel opens two years later with his impending marriage to Albinia. Unable to recognise her intelligence and force of character he still sees her as 'the answer to everything', meaning that she will undertake all the household cares while he retires to his study and intellectual pursuits. Instead, once she has seen through her own illusions about him, she effectively destroys his peace and leads him to find happiness in a life of active usefulness.

Before that, Albinia's own belief that she can undertake many duties within and outside her home without neglecting any is shown to be a mistake. Her later illusions are concerned with her stepchildren and the slums and their inhabitants. Her worst error is to assume that Ulick O'More, the dashing devout young Irishman, is in love with Sophie, and to encourage the girl in this belief, but she has also to learn that there is no simple solution to the problem of the slums.

Other characters and groups are subject to illusions. Things are never quite what they seem. Gilbert, the timid stepson dies a hero of the Charge of the Light Brigade, appropriately for there too 'someone had blundered'.

Most events in the novel are seen through the heroine's eyes and she is far from infallible. The readers have to evaluate the available evidence and draw their own conclusions. Thus what may seem to be a warning against rash judgements aimed at well meaning but impetuous young women becomes a practical lesson for all.

#### 5. Characterisation

At the start of the novel the heroine is 23, and about to marry. At the end she is in her thirties and has some grey hairs. For the first time in C. M. Yonge's fiction the problems of adults are the main concern and those of late adolescence are shown from the viewpoint of those responsible for them. The long time span allows both characters and relationships to develop naturally, and these relationships between major and minor characters are complex, and fluctuate with time and changing circumstances.

The central relationship is that between Edmund and Albinia Kendal. She changes from a loving, high spirited, impulsive girl, eager to set the world to rights and to kick start her passive indolent husband into undertaking his responsibilities into a loving and dutiful wife, admiring him as he does so, while she confines herself to caring for the family. The characters of both are complex, particularly his. Thus in some situations he deals with his children with more understanding than she does.

Minor characters are equally well-drawn, and have a particular function in the novel. Thus Ulick O'More is not only the object of Albinia's grave mistake, and Mr Kendal's grave misunderstanding, but takes on the role of comic blunderer when Albinia lays it down. His wit and humour enliven the novel, and he serves as a contrast to Gilbert, the gentle spineless stepson.

Characters are shown in relation to the rest of the community. Each of the stepchildren has strong friendships outside the immediate family, unlike the young people in C. M. Yonge's previous works. The impact of the community on the newcomers (the clergyman and his wife, Albinia, Ulick, the French girl, Genevieve and her family, and Algernon Dusautoy) and vice versa is skilfully and sometimes amusingly described.

#### 6. The Setting

The setting, both physical and social is given more prominence in the serial than in the book. In both frequent allusions and occasional set descriptions build a picture for the reader of Bayford town and surrounding areas, of individual streets, houses, rooms and gardens, together with the local climate.

The physical setting is in part symbolic. The church stands on the breezy hill-top with a clear distant view, while below in the town the air is close and frequent fogs arise from the river and the Kendals' pond. Mr Kendal's study is a key to his state of mind. Laurels crowd the window, making the room dark and gloomy like himself, and preventing him from seeing the world outside.

Much material concerning the townsfolk is omitted in the book but enough remains to give a picture of a narrow, stratified provincial society, suspicious of new ideas and the strangers who introduce them, except when the stranger is a rich young man. These townsfolk are treated humorously. However, the portrayal of the slum dwellers is ambivalent. In the early chapters individuals are shown, good church-goers, the victims of poverty and exploitation. Later the slum dwellers are shown in the mass, as drunkards and violent rioters, whom Albinia dismisses as 'a horrid set.' The reader is left with conflicting evidence.

#### 7. Religious and ethical teaching

All C. M. Yonge's fiction has a didactic purpose, but in The Young Stepmother it is less overt and less severe in tone than in her previous works, and milder in the book than in the serial. Non-Tractarian elements in the Church of England are not mentioned openly and the only Roman Catholic to be criticised is a convert, who does not appear in person. The benefits of baptism and confirmation are shown, but not the dangers of their omissions as in The Daisy Chain and The Castle Builders. The religion shown is at times more personal and more emotional than in previous works.

The main fault under consideration (many others receive passing notice) is an intellectual not a moral failing, and in general characters criticise themselves, or their shortcomings are revealed by the author's arrangement of events rather than by her comments. The teaching is further tempered by the fact that some problems are shown as apparently insoluble, so that mistakes are inevitable.

However one possible error seems to pass unnoticed. A comparison with C. M. Yonge's surrounding works suggests that a better method of clearing Bayford's slums could have been found, but only by a degree of self-sacrifice not expected of the Kendals either by themselves or by their clerical adviser. It is not clear whether this represents the author's recognition of the unlikelihood of such a choice (implying a criticism of her own moral stance in other books) or her failure to think clearly about the issue. Again, the readers must judge for themselves.

Further Reading

For contemporary reviews see L. Madden,*J B Shorthouse and C. M. Yonge*unpublished thesis, University of London Diploma in Librarianship. 1964.

See also

Battiscombe, Georgina.*Charlotte Mary Yonge. The story of an uneventful life*(London: Constable, 1943). See index for numerous references and comments.  
Coleridge, Christabel.*Charlotte Mary Yonge. Her life and letters*. (London: Macmillan, 1903) pp. 197 and 245.  
Mare, Margaret and Percival, Alicia C.*Victorian best-seller. The world of Charlotte M. Yonge*(London: Harrap, 1947). See index for numerous references and comments.  
Romanes, Ethel.*Charlotte Mary Yonge. An appreciation*. (London and Oxford: Mowbray, 1908) pp. 104-108  
de Gruchy, Amy. "C. M. Yonge's Historical Novels - The Influence of Scott", 1837-1901 Journal of the Loughborough Victorian Studies Group No 5 pp. 91 - 92.

**In 'The Newsletter/Review of the The Charlotte M Yonge Fellowship'**

'The Young Stepmother. No 3 pp. 1 - 2  
The serial and the Book': No 5 p 8.  
'Two Versions of the Young Stepmother': No 6 p 6  
Letters to the Editor: No 12 pp. 2 - 3 'Mothers Brought to Judgement'.

### From: The Athenaeum December 21, 1861, pages 838-39

*The Young Stepmother: a Chronicle of Mistakes*  
By the Author of '[*The Heir of Redclyffe*](heir_of_redclyffe.qmd),' &c. (Parker, Son & Bourn.)

There is about as much reading in this one volume as in three ordinary three-volume novels, and no one can complain that, in making an investment in 'The Young Stepmother,' they have not got their money's worth of paper for their money. It would fill up a month of wet days in a country house. It is impossible not to become, to a certain degree, interested in the detail of the daily life of the luckless young stepmother; and yet it is real hard work to follow her through the minute history of every day, and almost of every hour of the day, in her dreary up-hill task of humanizing her step-children and taming and softening their melancholy, morose father. Albinia's is a fine character, - courageous, impetuous, full of life and spirit, with a restless craving for "work," and an unlimited supply of energy and good-nature. Full of ardour for "something to do," she leaves her bright and happy home in her brother's parsonage, where she is adored both by himself and his merry little Irish wife, for the sake of consoling an inconsolable elderly widower, in weak health, of a gloomy temperament, residing in a damp, dark, unwholesome house, in a dull country town, and possessing three of the most odious children it has ever been our fate to meet with, either in a book or in real life. At first Albinia looks forward with hope and resolution to her future fate. She intends to cure her husband of giving vent to "suppressed sighs," and speaking in "a voice of subdued melancholy." She makes up her mind that she "could bear to have his late wife's memory*first*with him," and she knows she "could not compensate to him for his loss," but trusts that in time he may appear a little less dejected. She vainly tries to coax the sulky schoolboy, with a toothache, into good humour; to put sense into the foolish, affected, gossipping Lucy; even hopes in time to make something out of the languid, sickly Sophia, with her downcast looks and forbidding manner. Nothing can be more unpromising than her commencement. Though Gilbert takes a fancy to her and soon becomes quite "her pet," he is weak, untruthful, and fond of low company. Lucy gossips away right and left, makes mischief between Albinia and the Meadowses (mother and sister of the first Mrs. Kendal), and spreads reports of her stepmother's sayings and doings all over Bayford. As for Sophy, she baffles all attempts at sociability, and till (in the course of a year or two) she half kills Albinia's baby and nearly breaks her own neck, she remains as perverse and moody as before. Worried and dispirited, Mr. Kendall gives happiness up as a bad job, and retires to his study, where he locks his door upon all intruders - his young wife included, - and takes heed of naught that passes in his uncongenial household.

Out of doors things are very little better; the town is dirty, and fevers abound; the pond exhales thick poisonous vapours. The neighbours are second-rate and meddlesome; the Meadows family interfering and censorious, and the children aggravating. After her first confinement, poor Albinia completely breaks down in health and spirits, and her brother and sister-in-law come to her assistance. They keep*her*quiet, rouse Mr. Kendal, get Gilbert sent off to a private tutor's, and take Lucy away with them on a visit. Winifred takes the opportunity of telling Sophy, in very plain terms, what she thinks of her conduct, and Maurice fills up the obnoxious pond, and from that hour matters improve with the young Stepmother. Then the elderly Miss Meadows marries a former lover of the days of her youth, and the old lady is imported into the house at Willow Bank - a great infliction in itself, but a blessing, inasmuch as she deprives Mr. Kendal of his beloved study, and thereby obliges him to consort more with the rest of the family. Backed up by her brother and Mr. Dusantoy, the excellent clergyman of Bayford, Albinia next induces her husband to take a little interest in public affairs, and he becomes in time a churchwarden, a magistrate, and a useful man of business in the parish. The stepchildren gradually grow up, and cause much anguish and tribulation of mind to poor Mr. Kendal by falling in love with all the wrong people. Lucy makes what is called "a good marriage," and is wedded to a rich man and a conceited fool, in spite of the indignant remonstrances and tearful entreaties of Albinia. Gilbert becomes enamoured of a fascinating French teacher, who wins the hearts of all the young men within her reach, and is really a charming little thing, and deservedly beloved by everybody in the book. Poor, ugly, morbid Sophy forms an attachment to a rollicking young Irishman, but Ulrick O'Moore has the good taste to prefer Genevieve; and Sophy finds out she has chosen the Human and left the Divine, and makes up her mind to be a very hard-working old maid, and takes to Albinia's children and makes herself generally useful in the world. Of course, poor Mrs. Kendal takes blame to herself for everything that goes wrong, and her feelings of remorse at every slight*contretemp*s are bitter and exaggerated. Her brother endeavours to persuade her, that, although she may have made a few blunders here and there, still, take it all in all, she has faithfully and earnestly done her best, and the result lies in other hands than her own. This is, we presume, the moral of the book; but we have our doubts whether these kind of books, good and useful as they doubtless are in many ways for young ladies who are not allowed to peruse regular novels, may not tend to encourage in others too close a scrutiny into the various shades of their own and their neighbours' characters. Each little failing, merit, tendency or habit, is here examined under a powerful microscopic lens, and analyzed and commented on till one becomes fairly confused as to the relative degrees of right and wrong; and if the plan be acted upon and carried out in real life, the process can scarcely be a wholesome one to a young mind.

'The Young Stepmother' is far from being so interesting as '[*Heartsease*](heartsease.qmd),' or '[*The Heir of Redclyffe*](heir_of_redclyffe.qmd);' but it is much of the same calibre as '*[Dynevor Terrace](dynevor_terrace.qmd)*' and '[*The Daisy Chain*](daisychain.qmd),' and as such will, we have no doubt, meet with its circle of admiring readers.

### Poirot moves in on*The Young Stepmother*

#### **This extract from Agatha Christie's*Evil Under the Sun****:*****Chapter 8******

To the left of the mantelpiece there were some shelves with a row of books. Hercule Poirot looked thoughtfully along the titles.

A Bible, a battered copy of Shakespeare's plays,*The Marriage of William Ashe*, by Mrs. Humphry Ward.*The Young Stepmother*, by Charlotte Yonge.*The Shropshire Lad*. Eliot's*Murder in the Cathedral*. Benard Shaw's*St Joan*.*Gone With the Wind*, by Margaret Mitchell.*The Burning Court*, by Dickson Carr.

Poirot took out two books.*The Young Stepmother*and*William Ashe*, and glanced inside at the blurred stamp affixed to the title page. As he was about to replace them, his eye caught sight of a book that had been shoved behind the other books. It was a small dumpy volume bound in brown calf ...

#### Yonge, Dumas and R L Stevenson

#### This extract is from Robert Louis Stevenson'sMemories and Portraits.

#### Chapter XIV: A Gossip on a Novel of Dumas's

My acquaintance with the Vicomte began, somewhat indirectly, in the year of grace 1863, when I had the advantage of studying certain illustrated dessert plates in a hotel at Nice. The name of d'Artagnan in the legends I already saluted like an old friend, for I had met it the year before in a work of Miss Yonge's. My first perusal was in one of those pirated editions that swarmed at that time out of Brussels, and ran to such a troop of neat and dwarfish volumes ...

(and a little further down the same page)

Yes; in spite of Miss Yonge, who introduced me to the name of d'Artagnan only to dissuade me from a nearer knowledge of the man, I have to add morality. There is no quite good book without a good morality; but the world is wide, and so are morals.

