project:
  type: website
  output-dir: docs

website:
  title: "Charlotte M. Yonge — Works"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: custom.css
    toc: false
    template-partials:
      - title-block.html